### ISSUE TITLE
Updates with a partial document

### ISSUE THREAD

**Issue by arkmuay** [FriendsOfSymfony/FOSElasticaBundle#1003]
Hi,

How to update partial document ?

Actually, when I update a field, the entire document is updated and generates a lot of queries because of dependencies (object, nested in another tables).

Thanks,

**Comment by arkmuay** [comment]
:)

**Comment by rushi** [comment]
I'm interested in finding out about this as well. A partial update would solve a lot of problems because it would save on DB calls (for relationships) and if Doctrine is involved it would reduce memory usage as well.

**Comment by XWB** [comment]
Partial updates is out of scope for this bundle.

**Comment by arkmuay** [comment]
Ok... So, no solution...
