### ISSUE TITLE
minimum score

### ISSUE THREAD

**Issue by gfrancqu** [FriendsOfSymfony/FOSElasticaBundle#1004]
Hi,

i'm trying to get only pertinent result 

``` php
 $finder = $this->container->get('fos_elastica.finder.app.plat');
    $boolQuery = new \Elastica\Query\Bool();

    $fieldQuery = new \Elastica\Query\Match();
    $fieldQuery->setFieldQuery('title'.$upperlocale, $searchTerm);
    $fieldQuery->setFieldParam('title'.$upperlocale, 'analyzer', 'custom_analyzer');
    $boolQuery->addShould($fieldQuery);

    $fieldQuery = new \Elastica\Query\Match();
    $fieldQuery->setFieldQuery('synonymes', $searchTerm);
    $boolQuery->addShould($fieldQuery);

    $plats = $finder->find($boolQuery,100);
```

elastica is doing his job perfectly, correcting mistakes though my custom analyzer, but he is doing his job to much perfectly he always find results whatever I type. 
I don't want elastica to find result on stupid search query so I would like to set a minimum score (I know this is possible with elastica) but i have no idea on how to deal with score though foselastica bundle.

any idea would be appreciated

**Comment by jasonquick** [comment]
Wrap your BoolQuery in a Query, which has a setMinScore() property. So the last few lines of your code would look like:

```php
$boolQuery->addShould($fieldQuery);

$query = new \Elastica\Query($boolQuery);
$query->setMinScore(0.65); // Or whatever

$plats = $finder->find($query,100);
````

**Comment by XWB** [comment]
This belongs in https://github.com/ruflin/Elastica
