### ISSUE TITLE
[RFC] Introduce `hybrid` argument on `findPaginated` method finder class

### ISSUE THREAD

**Issue by koemeet** [FriendsOfSymfony/FOSElasticaBundle#1005]
Since there are a lot of requests to have a hybrid result set when you call `findPaginated`, I think it might be appropriate to change the `PaginatedFinderInterface` to:

``` php
public function findPaginated($query, $options = array(), $hybrid = false);
```

Also the `TransformedPaginatorAdapter` should have an extra constructor argument `hybrid`

``` php
public function __construct(SearchableInterface $searchable, Query $query, array $options = array(), ElasticaToModelTransformerInterface $transformer, $hybrid = false)
```

When you pass in hybrid `true`, it will then create `TransformedPartialResults` with also `hybrid` set to `true`. So the final method `toArray` will then use the appropriate transformation strategy.

``` php
public function toArray()
{
    if (true === $this->hybrid) {
        return $this->transformer->hybridTransform($this->resultSet->getResults());
    }

    return $this->transformer->transform($this->resultSet->getResults());
}
```

@merk WDYT about this approach? If you like it, I can make a PR. It's a small change but will fill the missing piece in the finder classes.

We could also introduce a new method, like `findPaginatedHybrid`, instead of the extra argument.

**Comment by XWB** [comment]
You can use the `createHybridPaginatorAdapter` method.
