### ISSUE TITLE
Profiler timing is incorrect on the toolbar

### ISSUE THREAD

**Issue by joshuataylor** [FriendsOfSymfony/FOSElasticaBundle#1009]
I'm using Symfony 2.8, and the latest dev-master of the bundle.

At the bottom of the page, it shows 1 query was executed in 2000.00ms (http://i.imgur.com/UPsZ0iJ.png)

However, going into the profiler shows the correct time:

http://i.imgur.com/fQRuxQj.png

**Comment by bgaleotti** [comment]
Can you check if #1011 fixes the issue?

**Comment by jaikdean** [comment]
#1011 Fixes the problem for me.
