### ISSUE TITLE
Populate hangs when indexing large table

### ISSUE THREAD

**Issue by edhgoose** [FriendsOfSymfony/FOSElasticaBundle#1022]
Hi,

I'm simplifying, but we have a production environment running a MySQL database and ElasticSearch and then a Staging environment running exactly the same.

Every now and again, we anonymise our production database and copy it over to Staging. We then blow away the Staging ElasticSearch data and reset a _small portion_ of the data (we don't need ElasticSearch to be exactly up to date due to the nature of our application).

To do this, we run a command like:

```
 php app/console fos:elastica:populate --index="indexName" --no-debug
```

Unfortunately, our production database is pretty large. One of the ElasticSearch indexes is a join between two tables which each have several million rows.

The index resets fine, but as soon as it tries to run the [countObjects](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Doctrine/ORM/Provider.php#L51) query (we're using Doctrine btw), the database hangs. This happens just after it resets the database, and just before the first "populating" appears on the console.

We ended up killing the query after an hour and instead hacked the code to do the following:

``` php
     /**
      * @see FOS\ElasticaBundle\Doctrine\AbstractProvider::countObjects()
      */
     protected function countObjects($queryBuilder)
     {
        return 1000000; 
     }
```

I'm aware that this only makes sense in our case where I'm going to arbitrarily kill the populate command at some point after a few thousand have been populated as the nbObjects is used for calculating when to stop, but wondering if there is something that can be done instead (e.g. could I provide the count from our production db which is faster?). Or is there some other way of calculating the total instead, such as providing an index that can help with the query?

Bit of an edge case, but thought I'd add it incase anyone else comes across something similar.

Cheers,
Ed

**Comment by makasim** [comment]
The provider API was completely re-written in v5 of the bundle. Now it relies on pager abstraction and by default uses pagerfanta. 

It might be that the problem disappears on its own. Though there is a possibility to implement your own pager provider with custom logic.

**Comment by edhgoose** [comment]
Thanks @makasim - we actually eliminated this whole problem by no longer copying our data between environments and so that's solved the problem but I'll keep that in mind for v5. Cheers!
