### ISSUE TITLE
How if i need  elastica 3.1 ?

### ISSUE THREAD

**Issue by truonghoang** [FriendsOfSymfony/FOSElasticaBundle#1029]
why is ruflin/elastica still ~2.1 in composer.json  ?,
 I need  [ruflin/elastica](https://packagist.org/packages/ruflin/elastica)  3.1 support elasticsearch 2.x,

**Comment by mvrhov** [comment]
Browse the issues and you'll find the answer.

**Comment by AliHichem** [comment]
@mvrhov that's a very rude way to help others find answers .. 
@truonghoang upgraing to elastica 3.x was requested many time and mentioned on many issues here which you can follow the main discussion here https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/996.

**Comment by truonghoang** [comment]
okies, sorry had duplicated the issue.

**Comment by mvrhov** [comment]
@AliHichem I'm sorry you feel offended, but the sad realty is that people now-days, they just ask the question, without using the search, or look at the open/closed issues.
