### ISSUE TITLE
FantaPaginatorAdapter does not implement getTotalHits and getResults

### ISSUE THREAD

**Issue by ruudvanderweijde** [FriendsOfSymfony/FOSElasticaBundle#1040]
In a change (https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/50bd328191f0339dc290b8897b0a5176aee3f2e8) the [`PaginatorAdapterInterface`](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Paginator/PaginatorAdapterInterface.php) was added to [`FantaPaginatorAdapter`](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Paginator/FantaPaginatorAdapter.php) class. But the required methods were not added.

Code to reproduce the error:
```
<?php

use FOS\ElasticaBundle\Paginator\PaginatorAdapterInterface;

require_once('vendor/autoload.php');

class FakePaginatorAdapter implements PaginatorAdapterInterface {
    public function getTotalHits() { }
    public function getResults($offset, $length) { }
    public function getFacets() { }
    public function getAggregations() { }
}

new \FOS\ElasticaBundle\Paginator\FantaPaginatorAdapter(new FakePaginatorAdapter());
```

Which provides the error:
```
Fatal error: Class FOS\ElasticaBundle\Paginator\FantaPaginatorAdapter contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (FOS\ElasticaBundle\Paginator\PaginatorAdapterInterface::getTotalHits, FOS\ElasticaBundle\Paginator\PaginatorAdapterInterface::getResults) in FOSElasticaBundle/Paginator/FantaPaginatorAdapter.php on line 63
```

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/3030cd8aca9ec9fd7d8f94eb882d75428f96e5b8
