### ISSUE TITLE
Please add version tag for composer

### ISSUE THREAD

**Issue by ismailbaskin** [FriendsOfSymfony/FOSElasticaBundle#1057]

**Comment by COil** [comment]
:+1:  , so we can use with Symfony3. Thanks.

**Comment by michaelperrin** [comment]
Symfony 3 was released almost 6 months ago now...

**Comment by jxmallett** [comment]
So, does anyone know what needs to be done to make this happen? I assume the new tag will be `3.2.0` or, if it breaks backwards compatibility, `4.0.0`.

Does the test suite need to be updated?

**Comment by XWB** [comment]
Version 3.2.0 has been released.
