### ISSUE TITLE
pass more options to connection (server)

### ISSUE THREAD

**Issue by wodka** [FriendsOfSymfony/FOSElasticaBundle#1060]
Hi, 

is it possible to pass more options to the server?

right now the following parameters are supported (as far as I can see):

- url
- host
- port
- proxy
- logger
- headers
- transport (this is the reason I'm asking this)
- timeout

a few days ago the transport "AwsAuthV4" was added (https://github.com/ruflin/Elastica/pull/1056)

this specific transport checks a few more params of the connection:

- aws_region
- aws_access_key_id
- aws_secret_access_key
- aws_session_token

I know those values are also read from the env variables (with a few fallbacks) but I would like to pass them to the connection directly.

could we perhaps add a new parameter "params" where arbitrary key/value pairs could be defined?

**Comment by wodka** [comment]
right now I'm using the following class (override the parameter fos_elastica.client.class with your classname). I'm using this because the AWS SDK did not pick up the environment variables...

```php
use Elastica\Connection;
use FOS\ElasticaBundle\Elastica\Client as BaseClient;

/**
 * Class Client
 */
class Client extends BaseClient
{
    /**
     * Inits the client connections.
     *
     * @param array $config
     * @param null  $callback
     */
    public function __construct(array $config = array(), $callback = null)
    {
        parent::__construct($config, $callback);

        if (!getenv('AWS_ACCESS_KEY_ID')) {
            return;
        }

        /** @var Connection $connection */
        foreach ($this->_connectionPool->getConnections() as $connection) {
            if ($connection->getTransport() == 'AwsAuthV4') {
                $connection->setParam('aws_access_key_id', getenv('AWS_ACCESS_KEY_ID'));
                $connection->setParam('aws_secret_access_key', getenv('AWS_SECRET_ACCESS_KEY'));
                $connection->setParam('aws_region', getenv('AWS_REGION'));
            }
        };
    }
}
```

**Comment by ppounder** [comment]
Did you hear anything further regarding this enhancement or are you still successfully overriding the Elastica/Client?

**Comment by wodka** [comment]
didn't hear anything related to it yet and it is still working :)
