### ISSUE TITLE
Elastic Search not updating when relationship data has been modified

### ISSUE THREAD

**Issue by bertoost** [FriendsOfSymfony/FOSElasticaBundle#1063]
I have indexed my entity and all is working great when you add, change or remove the main entity. But when a related entity is changed, and nothing is changed in the main entity, nothing happens in the search index.

Maybe I am missing something but I couldn't find anything about it.

**Comment by Nightbr** [comment]
Hey, you need to override the listener to take into account related entities. I made this gist I use for my application: https://gist.github.com/Nightbr/ddb586394d95877dde8ed7445c51d973
Feel free to complete it.

**Comment by greg0ire** [comment]
See #824

**Comment by Tobion** [comment]
Closing as duplicate
