### ISSUE TITLE
Allow use of groups with Symfony serializer

### ISSUE THREAD

**Issue by mickadoo** [FriendsOfSymfony/FOSElasticaBundle#1085]
Currently the mapping by serializer groups is only supported by the JMS Serializer.

The Symfony serializer is perfectly acceptable for many projects and I think it would be nice if it supported mapping by groups too.

This was also mentioned in the [comments for the road map](https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/986#issuecomment-166466552) by @damienalexandre

**Comment by Tobion** [comment]
Seems to be possible since https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/3e021f28e742f4edcb1ff00b782fe3f4bad3abf2
