### ISSUE TITLE
Declare index with "dynamic" name + query on multiple indexes

### ISSUE THREAD

**Issue by j-datadome** [FriendsOfSymfony/FOSElasticaBundle#1087]
Hello,

**Question 1: declare index with "dynamic" name**

I'd like to use the bundle to map my ES indexes.
All my indexes have the same type, so the same entity, with a name with this pattern: myindex_{CUSTOMER_ID}_YYYY-MM-DD
Of course, I cannot fusion these data to a single index because of the volume.

As I understand for now, this is only possible to define the indexes in the config file, but I have hundreds of indexes and there are created each day at any time (this is created by action of each customer).

Is there a way to handle this?

**Query on multiple indexes**

If the first question can have a solution, is there a way to query several indexes in the same time. In my case, I need to query several indexes as it can handle several days of data.

Thank you a lot for helping
Jourdan

**Comment by oleg-andreyev** [comment]
All indices already have dynamic name with Y-m-d-His as prefix, see https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Index/AliasProcessor.php#L40 I think you can reuse it.

You can query multiple indices and types https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-multi-index-type

But IIRC ruflin/Elastica doesn't support that, but you can achieve that by querying indices with same alias.

**Comment by The-Don-Himself** [comment]
> Query on multiple indexes

This is unfortunately not easy to do with Ruflin/Elastica which FOSElastica relies on, but Elasticsearch supports it and has so for ages.

@oleg-andreyev workaround will work, but I would suggest something else, get your hands a little dirty and use the official Elasticsearch PHP client specifically for this feature https://github.com/elastic/elasticsearch-php.

Querying against multiple indices and/or types becomes very simple
````
$params['index'] = "index1,index2";//array of indices
$params['type']  = "type1,type2";//array of types
$params['body']  = $q;//query body
//request elasticsearch for matched documents
$results = $client->search($params);
````
re: http://stackoverflow.com/questions/27021693/using-multiple-types-or-indexes-in-elasticsearch-php-api

This is what I do, but I still use this very useful bundle, it makes stuff so easy to manage in a Symfony context especially for populate commands. There's no harm in using both :)

**Comment by The-Don-Himself** [comment]
Also note, this is the general direction Ruflin/Elastica is heading, so might be nice to now a little about the official client now.

https://github.com/ruflin/Elastica/issues/944

**Comment by oleg-andreyev** [comment]
@The-Don-Himself I wanted to post that discuss here also. This bundle doesn't provide any fetch functionality by it's self, it depends on ruflin/Elastica. And you probably could do the same with calling `Client::request` with correct $path

**Comment by Brah0um** [comment]
> Hello,
> 
> **Question 1: declare index with "dynamic" name**
> 
> I'd like to use the bundle to map my ES indexes.
> All my indexes have the same type, so the same entity, with a name with this pattern: myindex_{CUSTOMER_ID}_YYYY-MM-DD
> Of course, I cannot fusion these data to a single index because of the volume.
> 
> As I understand for now, this is only possible to define the indexes in the config file, but I have hundreds of indexes and there are created each day at any time (this is created by action of each customer).
> 
> Is there a way to handle this?

Hello @j-datadome,

Did you find any solution for this ?

Thanks

**Comment by vardius** [comment]
> > Hello,
> > **Question 1: declare index with "dynamic" name**
> > I'd like to use the bundle to map my ES indexes.
> > All my indexes have the same type, so the same entity, with a name with this pattern: myindex_{CUSTOMER_ID}_YYYY-MM-DD
> > Of course, I cannot fusion these data to a single index because of the volume.
> > As I understand for now, this is only possible to define the indexes in the config file, but I have hundreds of indexes and there are created each day at any time (this is created by action of each customer).
> > Is there a way to handle this?
> 
> Hello @j-datadome,
> 
> Did you find any solution for this ?
> 
> Thanks

if anyone came up with nice solution how to do it, please let me know
