### ISSUE TITLE
Bulk Insert failing `ElasticsearchIllegalArgumentException[explicit index in bulk is not allowed]`

### ISSUE THREAD

**Issue by joshughes** [FriendsOfSymfony/FOSElasticaBundle#1091]
This seems to be an issue when Elasticsearch has URL security turned on. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/url-access-control.html

In our case we are using AWS Elastic Search service, which locks down URL access to ensure only our applications can communicate with Elastic Search. 

The problem seems to come from including the index name in the bulk insert instead of using the index url. If the index name is not in the document body then elasticsearch automatically falls back to the URL for deciding how to index the bulk insert. 

https://github.com/elastic/elasticsearch-net/issues/870

Its not clear if there is a configuration option to avoid this issue. It seems like the easiest thing to do is to change the content of the bulk data to not include the index data and ensure to use the `_bulk` endpoint on the index URL... which should work in all scenarios.

**Comment by sallyx** [comment]
Hi,
is there any solution to this bug?

**Comment by NoScopie** [comment]
@joshughes did you solve this issue? Since you closed it.

**Comment by joshughes** [comment]
No I never found a solution to this issue
