### ISSUE TITLE
Elasticsearch 1tomany updating child objects

### ISSUE THREAD

**Issue by rdksgit** [FriendsOfSymfony/FOSElasticaBundle#1092]
Hi,
I have got a form entity which has got fields, 

This is my config.yml, where formval is the main object and fieldvalue is where all the fields for the form are stored, now using the standard foselastica bundle configuration it indexes all the top level objects perfectly but not the fieldvalue object which is a nested object and has got a 1 to many relationship which formval( so 1 formval can have many fieldval)
formval:
                    mappings:
                        createdAt: ~
                        updatedAt: ~
                        id: ~
                        form:
                            type: "object"
                            properties: 
                               id: ~
                        usercreated: 
                            type: "object"
                            properties: 
                               username: ~
                               id: ~
                        userassigned:
                            type: "object"
                            properties: 
                               username: ~
                               id: ~
                        formstatus:
                            type: "object"
                            properties:
                                name: ~
                                id: ~
                        fieldvalue:
                            type: "nested"
                            properties:
                                id: ~
                                value_text: ~
                                value: ~
                                field: ~

I have read about listeners but couldnt get it to work, any pointers would be great

tks

**Comment by greg0ire** [comment]
See #1063 ?

**Comment by Tobion** [comment]
Closing as duplicate
