### ISSUE TITLE
MapperParsingException

### ISSUE THREAD

**Issue by crashbtz** [FriendsOfSymfony/FOSElasticaBundle#1096]
Hello,
I'm not sure my problem comes from this bundle but maybe someone here could help me to solve it.
I have a Symfony project and I was trying to index a custom field with the "property_path" option.
I have an attribute "tags" in my entity which is an array and I try to index it in two differents way.
Here is my conf:

`
tags: { type: string, search_analyzer: brut_analyser, index_analyzer: brut_analyser, boost: 15 }

tagsSearch: { type: "nested", index: "not_analyzed", property_path: "tags" }
` 

The indexation works pretty fine except for one data which throw an exception:

`[Elastica\Exception\Bulk\ResponseException]                                                                          
  Error in one or more bulk request actions:                                                                           
  index: /dev_ftve/video/5579b7a195ac3240978b5812 caused MapperParsingException[object mapping for [video] with array  
   for [tagsSearch] tried to parse as array, but got EOF, is there a mismatch in types for the same field?]`

Here is the curl request I got from the symfony profiler:

`curl -XPUT 'http://localhost:9200/_bulk' -d '"{\"update\":{\"_index\":\"dev_ftve\",\"_type\":\"video\",\"_id\":\"5579b7a195ac3240978b5812\"}}\n{\"doc\":{\"title\":\"A quoi \u00e7a sert de faire du sport ? - 1 jour, 1 question V2\",\"subtitle\":null,\"strapline\":null,\"type\":\"video\",\"headline\":\"<p>Marcher, courir, p&eacute;daler, jouer au foot : le sport, tu en fais tous les jours. Pourtant, s&rsquo;agiter autant, c&rsquo;est fatigant ! Et puis, tu pourrais te blesser...Certains pensent d&rsquo;ailleurs que faire du sport, &ccedil;a ne sert &agrave; rien. Alors pourquoi c&rsquo;est important de faire du sport ?<\/p>\",\"tags\":\"1 jour 1 question, sant\u00e9\",\"tagsSearch\":[{\"slug\":\"1-jour-1-question\",\"title\":\"1 jour 1 question\",\"taxoId\":\"56e17a66cc66864de08b4606\",\"nbUsed\":313,\"preferredTag\":null,\"parentTags\":[],\"status\":\"new\",\"createdBy\":null,\"modifiedBy\":\"pauline.jacob\"},{\"slug\":\"sante\",\"title\":\"sant\u00e9\",\"taxoId\":\"5477566ecc668699938b482e\",\"nbUsed\":78,\"preferredTag\":\"Array\",\"parentTags\":[{\"id\":\"5477566acc668699938b4567\",\"status\":\"shared\",\"type\":\"topic\",\"label\":\"Th\u00e9matique\",\"comment\":null,\"author\":\"Sandrine GARRIGUES <sandrine.garrigues@francetv.fr>\",\"product\":\"taxonomie\",\"parent_tags\":[],\"preferred_tag\":null}],\"status\":\"rejected\",\"createdBy\":null,\"modifiedBy\":\"monika.keler\"}],\"mainThematic\":\"Actualit\u00e9\",\"mainThematicSlug\":\"actualite\",\"mainSchoolLevel\":\"ce1\",\"mainSchoolLevelSlug\":\"ce1\",\"secondaryThematic\":\"Sport\",\"secondaryThematicSlug\":\"sport\",\"secondarySchoolLevels\":\"ce2, cm1, cm2, cp, sixi\u00e8me, sixi\u00e8me\",\"key\":85,\"series\":\"{\\\"key\\\":\\\"0000\\\",\\\"title\\\":null}\",\"program\":\"{\\\"key\\\":\\\"0000.1907\\\",\\\"title\\\":\\\"1 jour, 1 question\\\"}\",\"slug\":\"a-quoi-sert-de-faire-du-sport-1-jour-1-question\",\"publicationStatus\":\"online\",\"thumbnail\":[],\"createdAt\":\"2015-06-11T18:30:25+02:00\",\"modifiedAt\":\"2016-06-15T16:23:47+02:00\",\"publishedAt\":\"2015-06-11T18:30:25+02:00\",\"releasedAt\":null},\"doc_as_upsert\":true}\n"'`

Here is the array representation I took from the mongo database:
`[ 
        {
            "slug" : "1-jour-1-question",
            "title" : "1 jour 1 question",
            "taxoId" : "56e17a66cc66864de08b4606",
            "nbUsed" : 313,
            "preferredTag" : null,
            "parentTags" : [],
            "status" : "new",
            "createdBy" : null,
            "modifiedBy" : "pauline.jacob"
        }, 
        {
            "slug" : "sante",
            "title" : "santé",
            "taxoId" : "5477566ecc668699938b482e",
            "nbUsed" : 78,
            "preferredTag" : "Array",
            "parentTags" : [ 
                {
                    "id" : "5477566acc668699938b4567",
                    "status" : "shared",
                    "type" : "topic",
                    "label" : "Thématique",
                    "comment" : null,
                    "author" : "Sandrine GARRIGUES <sandrine.garrigues@francetv.fr>",
                    "product" : "taxonomie",
                    "parent_tags" : [],
                    "preferred_tag" : null
                }
            ],
            "status" : "rejected",
            "createdBy" : null,
            "modifiedBy" : "monika.keler"
        }`

The problem comes from the second entry because that works when I remove it.

I don't know where the "EOF" problem is because the array seems to be valid and the curl query to.

Is anyone has an idea?

**Comment by Tobion** [comment]
I cannot pinpoint the problem. But it must have to do with the mapping not being in sync with the document you try to index. Also I don't see the relation to "tags" and "tagsSearch". tags is an array of string according to your mapping. But tagsSearch isn't. It an array of objects. Those obect properties are not in your mapping. maybe there is the problem. Closing as this is not related to FosElasticaBundle.
