### ISSUE TITLE
Please HELP ME! How update after entity change

### ISSUE THREAD

**Issue by oscarjg** [FriendsOfSymfony/FOSElasticaBundle#1098]
Hi everyone. I need some help about my common (I guess) problem. This is an example of the situation.

Articles (news) with Authors (N-1)
Articles (news) with Tags (N-N)

My search model looks like:
id | entity_id | entity_type | title | authors | tags | .....

In my search model I have an entry for each entity (One row for each Article, Author and Tag). Ok, so when the user update the Article then my search model is updated and elasticsearch updates the article. Perfect! 
Now the user update the Author (the name for example). Elastic updates the Author entry as we expected but the Article entry still with the old author  name.

I tried to use parent and children, nested, object, creating separated models to authors and tags etc etc but I still have my problem, update the Article when the user updates authors or tags

Please, help me to see the light of this common problem. I need some approach to open my mind.

Thank you!

**Comment by alex751m** [comment]
Hello! Did you manage to solve this problem?
