### ISSUE TITLE
parent-child mapping doesn't work, triggers exception when running 'populate'

### ISSUE THREAD

**Issue by rparsi** [FriendsOfSymfony/FOSElasticaBundle#1100]
Using:
- php 7.0
- symfony 3.0.x
- FOSElasticaBundle 'dev-master', which in turn uses Elastica 2.1
- elasticsearch 2.3

Using following mapping:
[https://gist.github.com/rparsi/7113704db69495274104316123e7d423](url)

When running `php bin/console fos:elastica:populate -vvv`
I get following:

`Resetting app
[2016-06-24 11:06:22] elastica.DEBUG: logging Request {"path":"app/","method":"DELETE","data":[],"query":[],"connection":{"config":{"headers":[]},"host":"localhost","port":9200,"logger":"fos_elastica.logger","compression":false,"retryOnConflict":0,"enabled":true}}
[2016-06-24 11:06:22] elastica.INFO: app/ (DELETE) 18.09 ms
[2016-06-24 11:06:22] elastica.DEBUG: logging Request {"path":"app/","method":"PUT","data":{"mappings":{"company":{"properties":{"id":{"type":"integer"},"name":{"type":"string","analyzer":"english"},"deleted":{"type":"boolean"}},"dynamic_date_formats":[],"_meta":{"model":"AppBundle\Entity\Company"}},"strain":{"properties":{"id":{"type":"integer"},"name":{"type":"string","analyzer":"english"},"deleted":{"type":"boolean"}},"dynamic_date_formats":[],"_meta":{"model":"AppBundle\Entity\Strain"}},"user":{"properties":{"id":{"type":"integer"},"username":{"type":"string","index":"not_analyzed"}},"dynamic_date_formats":[],"_meta":{"model":"AppBundle\Entity\User"}},"location":{"properties":{"id":{"type":"integer"},"address":{"type":"string"},"description":{"type":"string","analyzer":"english"},"geo":{"type":"geo_point"},"deleted":{"type":"boolean"}},"_parent":{"type":"company","property":null,"identifier":"id"},"dynamic_date_formats":[],"_meta":{"model":"AppBundle\Entity\Location"}}}},"query":[],"connection":{"config":{"headers":[]},"host":"localhost","port":9200,"logger":"fos_elastica.logger","compression":false,"retryOnConflict":0,"enabled":true}}

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Wrong parameters for Elastica\Exception\ResponseException([string $message [, long $code [, Throwable $previous = NULL]]])`

If I comment out the `_parent` setting then I don't get any error.

What is the correct yml setting to make my Company entity parent of Location entity?

**Comment by oleg-andreyev** [comment]
What version of ruflin\elastica you are using?
Regarding issue with `_parent` it's caused by:

```
[Elastica\Exception\ResponseException]
  Mapping definition for [_parent] has unsupported parameters:  [identifier : id] [property : null]
```

**Comment by rparsi** [comment]
@oleg-andreyev I'm using FOSElasticaBundle 'dev-master' which is alias for version 3.2.x, which in turn uses Elastica 2.1.  I'm using ElasticSearch 2.3.
I gave up on using the `_parent` feature, instead I've implemented a property listener to inject my required fields.  For future projects I'm not going to use FOSElasticaBundle as it's way behind in the Elastica version being used; for my current project I have no choice nor time to undo work already done.

**Comment by ChristianVermeulen** [comment]
I'm not sure if this is fixed or not.. According to the merge it should be, but I'm having the same problem still... I am doing a clean setup and get to the same version numbers:

- SF 3.0
- PHP 5.6
- friendsofsymfony/elastica-bundle v3.2.1
- ruflin/elastica 2.3.1
- Elastic Search 5.0.1

```
PHP Fatal error:  Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /vagrant/vendor/ruflin/elastica/lib/Elastica/Exception/ResponseException.php on line 34
PHP Stack trace:
PHP   1. {main}() /vagrant/bin/console:0
PHP   2. Symfony\Component\Console\Application->run() /vagrant/bin/console:29
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
PHP   4. Symfony\Component\Console\Application->doRun() /vagrant/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
PHP   5. Symfony\Component\Console\Application->doRunCommand() /vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
PHP   6. Symfony\Component\Console\Command\Command->run() /vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:831
PHP   7. FOS\ElasticaBundle\Command\PopulateCommand->execute() /vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
PHP   8. FOS\ElasticaBundle\Command\PopulateCommand->populateIndex() /vagrant/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:124
PHP   9. FOS\ElasticaBundle\Index\Resetter->resetIndex() /vagrant/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:144
PHP  10. Elastica\Index->create() /vagrant/vendor/friendsofsymfony/elastica-bundle/Index/Resetter.php:100
PHP  11. Elastica\Index->delete() /vagrant/vendor/ruflin/elastica/lib/Elastica/Index.php:257
PHP  12. Elastica\Index->request() /vagrant/vendor/ruflin/elastica/lib/Elastica/Index.php:183
PHP  13. FOS\ElasticaBundle\Elastica\Client->request() /vagrant/vendor/ruflin/elastica/lib/Elastica/Index.php:496
PHP  14. Elastica\Client->request() /vagrant/vendor/friendsofsymfony/elastica-bundle/Elastica/Client.php:47
PHP  15. Elastica\Request->send() /vagrant/vendor/ruflin/elastica/lib/Elastica/Client.php:621
PHP  16. Elastica\Transport\Http->exec() /vagrant/vendor/ruflin/elastica/lib/Elastica/Request.php:171
PHP  17. Elastica\Exception\ResponseException->__construct() /vagrant/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:159
PHP  18. Exception->__construct() /vagrant/vendor/ruflin/elastica/lib/Elastica/Exception/ResponseException.php:34
```

According to ruflin docs it should be compatible with ES 5.0.1.

**Comment by oleg-andreyev** [comment]
ruflin could be compatible with 5.x, but not sure about bundle

**Comment by rparsi** [comment]
@oleg-andreyev 
@ChristianVermeulen 
FYI the project affected by this was finished a while ago; I used denormalized fields in the ES documents instead of `_parent` to get around the problem (though that created extra work for me).  However it would be very helpful for other users of this bundle to get this resolved in some way.  Either update the unit tests with comments or add notes somewhere (ie in readme), indicating which combination of versions (ruflin, bundle, ES, etc) is required for the `_parent` feature to work.

At the very least flag the `_parent` feature as volatile or dependent on package versions so that other devs don't end up wasting a lot of time/effort troubleshooting this.

**Comment by vinod1054** [comment]
can someone plz post version dependencies here

**Comment by padalec** [comment]
I have the same issues. Any plane to fix this bug?
