### ISSUE TITLE
Pagerfanta options

### ISSUE THREAD

**Issue by j-datadome** [FriendsOfSymfony/FOSElasticaBundle#1102]
Hello,

I'd like to know the set of options available to use with Pagerfanta.
There is the doc there: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/usage.md
but it doesn't explain this.

More, I can't figure to get the total of hits. I mean the real total of hits.

Thank you a lot

Jourdan

**Comment by rparsi** [comment]
@j-datadome I'm in the same boat...the lack of clear documentation is frustrating.
I have pagination working in following manor, may help you as well:

Based on the source code I read you can call `$query->setFrom(...)` and `$query->setSize(...)`
in the Elastica library.  However in my testing it doesn't seem to be applied by the Pagerfanta library.
So based on the Pagerfanta source code you need to call `$pagerfanta->setCurrentPage(...)` and `$pagerfanta->setMaxPerPage(...)`.  `Pagerfanta` does not immediately fetch the results, so by calling those setter methods first (before calling `$pagerfanta->getCurrentPageResults()`) you will not incur unnecessary performance penalties.

Out of sheer paranoia and not wanting to waste more time on this matter I call both sets of `Elastica\Query` and `Pagerfanta\Pagerfanta` methods in my code, which looks like this:
`$query = $this->buildQuery($searchCriteria);`
`$query->setFrom($searchCriteria->page->getOffset());`
`$query->setSize($searchCriteria->page->size);`
`/** @var Pagerfanta $pagerfanta */`
`$pagerfanta = $this->findPaginated($query);`
`$pagerfanta->setCurrentPage($searchCriteria->page->current);`
`$pagerfanta->setMaxPerPage($searchCriteria->page->size);`
`return $pagerfanta->getCurrentPageResults();`

Source codes:
https://github.com/whiteoctober/Pagerfanta/blob/master/src/Pagerfanta/Pagerfanta.php
https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query.php

**Comment by j-datadome** [comment]
Thanks for the tip Rahi! :-)
Very usefull
Finally, I decided to use elasticsearch-php instead and did my own wrapper...

**Comment by rparsi** [comment]
@j-datadome What's the github url for `elasticsearch-php` if you don't mind me asking

**Comment by j-datadome** [comment]
@rparsi Here it is: https://github.com/elastic/elasticsearch-php

**Comment by XWB** [comment]
Thanks.
