### ISSUE TITLE
Unrecognized option "immediate" under "fos_elastica.indexes.INDEX_NAME.types.ENTITY_NAME.persistence.listener"

### ISSUE THREAD

**Issue by OskarStark** [FriendsOfSymfony/FOSElasticaBundle#1113]
Works with FOSElasticaBundle `3.1.8`, but fails with `3.2.0`

This change should be reverted and released in major version IMO

**Comment by OskarStark** [comment]
The change was introduced here: #1071

**Comment by XWB** [comment]
Let me see if I can revert the commit and push it to master.

**Comment by alekitto** [comment]
I think the commit should be reverted and the option deprecated in the `3.2.x` branch, not in master (next release from master should be 4.0, right?)

**Comment by OskarStark** [comment]
> I think the commit should be reverted and the option deprecated in the 3.2.x branch, not in master (next release from master should be 4.0, right?)

yes 👍

**Comment by XWB** [comment]
@OskarStark Can you test the latest updates in the 3.2 branch? https://github.com/FriendsOfSymfony/FOSElasticaBundle/commits/3.2.x Will tag 3.2.1 afterwards.

**Comment by crashev** [comment]
Any updates here ? 

@XWB Any plans for new release ?

**Comment by XWB** [comment]
@crashev Please try the latest 3.2.x branch.

**Comment by XWB** [comment]
@OskarStark @crashev Any luck?

**Comment by crashev** [comment]
Actually I've just removed all immediate options from my code and moved on, it will be gone soon anyway. So others have to report back. And for now I've switched to dev-master version and it works just fine.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/releases/tag/3.2.1
