### ISSUE TITLE
update_all_types  mapping issue..  

### ISSUE THREAD

**Issue by hsb1007** [FriendsOfSymfony/FOSElasticaBundle#1129]
Hi all.

I am on Ubuntu with Elasticsearch not being able to start due to 'update_all_types' issue at the moment.

WIth Elasticsearch not running at all, how do we clear all index data? 

I am using Symfony elasticabundle to 'populate' the index.

With elastcisearch not running, it's hard to find its version as well but I assume it's above 2.0 because we have update_all_types mapping issue if I understand correctly.

And also I have removed all conflicting property as well but the same message keeps coming up 

[mapper [description] is used by multiple types. Set update_all_types to true to update [boost] across all types.]]

Any advice would be so much appreciated!

**Comment by jlamur** [comment]
Same problem here !

**Comment by Luciam91** [comment]
Upgraded to 4.0.* to get the 2.x support for Elasticsearch and now running into this same issue, exception being thrown is:

```
 [mapper [title] has different [analyzer], mapper [title] is used by multiple types. Set update_all_types to true to update [search_analyzer] across all types., mapper [title] is used by multiple types. Set update_all_types to true to update [search_quote_analyzer] across all types.]  
```

Does anyone have any fixes for this / is it something that's going to be required to be added as an option?

**Comment by giovannialbero1992** [comment]
Can you do an example to reproduce this error? Thanks

**Comment by nediam** [comment]
Had the same problem today and hot fix fot this:
add to `vendor/ruflin/elastica/lib/Elastica/Type.php:300`: `return $mapping->send(['update_all_types' => true]);`
and  `vendor/ruflin/elastica/lib/Elastica/Client.php:318`: `$bulk->setRequestParam('update_all_types', true);`

**Comment by XWB** [comment]
The change is related to Elastica itself.
