### ISSUE TITLE
How to override Elastica\Type?

### ISSUE THREAD

**Issue by olchick** [FriendsOfSymfony/FOSElasticaBundle#1130]
I try override `fos_elastica.type.class`,  but I still get instance of Elastica\Type. I found method getType() in index class, where hard created instance of Elastica\Type.

Is there any other way to do it?

**Comment by AAstakhov** [comment]
@olchick, I assume that I have similar issue: https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1127

What I need is modify type mapping based on some data that is not available during design phase. To be more precise, I construct types using an information stored in DB. 
Is it also your case?

**Comment by olchick** [comment]
@a-ast, thank you for your answer, but our issues don't the same. 
I need to override methods of Type class. I found that I can override service fos_elastica.type_prototype, add my custom class and all work fine. But method getType in Index class return new instance of Elastica\Type and I can't override this.
As for me it's not flexible, if I can override fos_elastica.type_prototype with my own Type class, why Index class create instance of standart class? 

As I can see your problem, you can override MappingBuilder class (fos_elastica.mapping_builder service) and in method buildTypeMapping add your logic with db for properties.

**Comment by Tobion** [comment]
`fos_elastica.type.class` is not an extension point that should be used.  FYI, all class params got removed in symfony 3 for this reason. And for bundles this should be done as well. I might create a PR to do so.

So there is no way to change the type class. Maybe you should consider using composition instead where needed.

**Comment by XWB** [comment]
:+1: Thanks Tobion.
