### ISSUE TITLE
Transformer fail with false hydrate option

### ISSUE THREAD

**Issue by istvankis** [FriendsOfSymfony/FOSElasticaBundle#1133]
Cannot read property "id" from an array. Maybe you intended to write the property path as "[id]" instead.
vendor/friendsofsymfony/elastica-bundle/Doctrine/AbstractElasticaToModelTransformer.php at line 114

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1134
