### ISSUE TITLE
How to retrieve only selected fields?

### ISSUE THREAD

**Issue by ASacanell** [FriendsOfSymfony/FOSElasticaBundle#1136]
Hello,

I need to use only one field ("status") from an object but elastica retrieves all the fields. How do I get only that field after the query with the bundle?

I've seen this [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-fields.html), but I dont know how to use it in the bundle.

Thanks!

**Comment by giovannialbero1992** [comment]
You can see how to mapping an entity by bundle's documentation.
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/3.2.x/Resources/doc/usage.md#advanced-searching-example
