### ISSUE TITLE
Latest 3.2.* release break back compatibility

### ISSUE THREAD

**Issue by Troytft** [FriendsOfSymfony/FOSElasticaBundle#1141]
You need to include this commit https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/1a1e985d4a17005534141ed7e2d6102c98890f32

**Comment by giovannialbero1992** [comment]
Can you give more information about this problem? Thanks

**Comment by alekitto** [comment]
Duplicate of #1113

**Comment by Troytft** [comment]
if i specify dependency as "friendsofsymfony/elastica-bundle": "^3.1"
And execute "composer update friendsofsymfony/elastica-bundle"
I'll get the update-breaking backward compatibility. 
This contradicts the the rules of the semver.

**Comment by Troytft** [comment]
@alekitto bug fixed, but don`t released

**Comment by Troytft** [comment]
It is not appropriate to make this kind of changes within a minor release neglecting backwards compatibility

**Comment by XWB** [comment]
Did you try the latest 3.2 branch? I cannot release a new version as long as nobody is willing to test it.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/releases/tag/3.2.1
