### ISSUE TITLE
Dynamic index names?

### ISSUE THREAD

**Issue by rwpino** [FriendsOfSymfony/FOSElasticaBundle#1143]
This is the same question as the issue #279 
I need to handle in a dynamic way the index that I have in my elasticsearch... I m working with symfony 3.1.  @merk said that this feature is in the bundle but I cannot found where is it or how to use it. Will be great if I can see a small example about how  to implement or use this feature

**Comment by claudiobizzotto** [comment]
Any updates on this one? Just a pointer as to what classes to use/methods to call would already be of great help.

**Comment by mikaelcom** [comment]
I'm not sure that this is the same case I needed to to but what I wanted to have an index timestamped as logstash/filebeat do such as `my-index-%kernel.environment%-YYYY.MM.DD` that would be for example `my-index-prod-2017.08.03` based on the current day. As it seems impossible to do so just using the yml configuration, here is what I did using the current `dev-master` branch:

**AppCompilerPass.php**
```php
<?php
namespace AppBundle\DependencyInjection\Compiler;

use AppBundle\Elastic\Client;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;

class AppCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $definition = $container->getDefinition('fos_elastica.client.default');
        $definition->setClass(Client::class);
    }
}
```

**Client.php**
```php
<?php
namespace AppBundle\Elastic;

use FOS\ElasticaBundle\Elastica\Client as EsClient;

class Client extends EsClient
{
    public function getIndex($name)
    {
        $currentDateTime = new \DateTime();
        $currentDateTime->setTimezone(new \DateTimeZone(date_default_timezone_get()));
        $name = str_replace('yyyy.mm.dd', $currentDateTime->format('Y.m.d'), $name);
        return parent::getIndex($name);
    }
}
```

**config.yml**
```yml

fos_elastica:
    indexes:
        app:
            index_name: my-index-%kernel.environment%-yyyy.mm.dd
```

Fortunately it generated me the correct index with the current date.

**Comment by Tobion** [comment]
Using parameters in `index_name` is possible and we use it alot. If that is not what you are looking for, feel free to create a new issue.

**Comment by mikemix** [comment]
Parameters are required to have a value at compile time. I for instance needed a runtime parameter (eg. user's locale).

**Comment by David-Crty** [comment]
@mikemix did you find a solution about this ?
