### ISSUE TITLE
Override Listener: isObjectIndexable is private

### ISSUE THREAD

**Issue by jewome62** [FriendsOfSymfony/FOSElasticaBundle#1147]
Hi everyone,

I must override Listener in my case, and i will use the `listener` in yaml config.
But in my service, who extends `FOS\ElasticaBundle\Doctrine\Listener`.

I would change the method `isObjectIndexable` because in my case, some entity are push into localised index (we are language stremmer,snowball, synonyme, etc)

But I cant do this because `isObjectIndexable` and attribute `indexable` are private.

Do you have any objection to spend at least the private method to protected ?
If this was ok, i make a pull request.

Thanks

**Comment by behram** [comment]
I can not figure out your problem exactly but you can use `indexable_callback` maybe.

Related links;
 - https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/types.md#testing-if-an-object-should-be-indexed
 - https://github.com/ojs/ojs/blob/master/app/config/elastica.yml#L20
 - https://github.com/ojs/ojs/blob/master/src/Ojs/UserBundle/Entity/User.php#L1068

**Comment by XWB** [comment]
See first comment.
