### ISSUE TITLE
Question about the populate command

### ISSUE THREAD

**Issue by loverg-c** [FriendsOfSymfony/FOSElasticaBundle#1148]
Hi,

I'm actually testing FOSElastica (dev-master version) for a symfony 3.1.4 project and elasticsearch-2.4.0;

I'm just asking why the fos:elastica:populate emptying all my data in elasticsearch server but still  remaining in my mysql database ?

I'm trying the no-reset option, but still the same.

Is it a normal behaviour from elasticsearch ?
Is there a manner to keep the data indexing or a bash script to re-post all the data from the database when I populate it ?

(PS: this is my elastica yml config: )
![capture d ecran 2016-09-28 a 12 21 24](https://cloud.githubusercontent.com/assets/4719382/18909977/34917996-8576-11e6-9436-16d2f5aae076.png)

**Comment by behram** [comment]
bundle only cleans current population node. For example if you do like 
`php bin/console f:e:p --env=prod --no-debug --batch-size=500 --type=user --index=search`
This will empty user type first and populate user objects.

**Comment by loverg-c** [comment]
Just try with another project, and this one take the mysql data to populate the indexing
