### ISSUE TITLE
Question: Timing 4.0 release?

### ISSUE THREAD

**Issue by thim81** [FriendsOfSymfony/FOSElasticaBundle#1150]
Is there any timing when there will be an 4.0 release?

Or am I missing how to install the stable 4.0 via composer?

**Comment by skonsoft** [comment]
👍

**Comment by philippecarle** [comment]
It's even more disturbing when a link to 4.x documentation is in the README. + dependency to ruflin/elastica is really outdated in stable version, making use of this bundle impossible with up-to-date version of elasticsearch, and forcing us to rely on dev-master :(

**Comment by XWB** [comment]
Work on 4.0 has just started and is far from ready.

**Comment by philippecarle** [comment]
So wouldn't it make sense at least to tag the current master as 3.3 for the minimum requirement for ruflin/elastica to be increased ? I just made a fresh install yesterday of your bundle and ran into troubles just because of that, and i kind of dislike to get dev-master as version for any bundle in my composer.json... just sayin' ;)

**Comment by saintberry** [comment]
How safe is it to use dev-master if we have really simple mappings / requirements? 

We're working on a legacy system that is using ES 1.5 and being forced to adopt 2+. We can either strip out this bundle or try and make it work with the 4.x code.

**Comment by romaricdrigon** [comment]
+1 for @saintberry question  
What is the recommended way to work with ElasticSearch 2.0+? 1.7 is getting old, next ES major version is around the corner.

**Comment by thim81** [comment]
The current master branch is stable, so it can perhaps be tagged as a separate 3.3 release?

That way we can use it while the 4.x branch is being developed.

**Comment by XWB** [comment]
Current master branch is incompatible with 3.x hence it cannot be tagged as 3.3.

**Comment by csteins** [comment]
Any news on this issue?
How stable is the 4.x branch?
Are there any plans of a release date for the 4.x branch?

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/releases/tag/v4.0.0
