### ISSUE TITLE
Incorect mapping

### ISSUE THREAD

**Issue by portey** [FriendsOfSymfony/FOSElasticaBundle#1152]
Hi,

I have some problems with data mapping, the flow is next:
1. Start: database is empty, index empty
2. In my command I create documents
3. I get current mapping info:  curl -XGET 'http://localhost:9201/_mapping/letter', the result is http://take.ms/VbA0e
4. Then I do query to elastica, witch fails: 

``` json
{
    "suggest":{
        "suggest":{
            "completion":{
                "field": "suggest"
            },
            "text":"goog"
        }
    }
}
```

Error:

``` json
{
            "type": "class_cast_exception",
            "reason": "org.elasticsearch.index.mapper.core.StringFieldMapper$StringFieldType cannot be cast to org.elasticsearch.index.mapper.core.CompletionFieldMapper$CompletionFieldType"
}
```
1. Then I do command fos:elastica:populate and take current mapping again (the same documents), the result is http://take.ms/RwsQ5
2. Mapping is correct now, so query no fails any more.

How can I create correct mapping when my index not created and database empty? Or how to resolve this?

**Comment by Tobion** [comment]
Elasticsearch can either guess the mapping based on the documents. Or, which is what you need to do, set the mapping explicitly. How to set the mapping is for example explained in https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/types.md#nested-objects-in-foselasticabundle

For completion, you need to set the mapping type to completion as explained in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html#completion-suggester-mapping

I hope this answers your questions.
