### ISSUE TITLE
Search annotation seems to not be working

### ISSUE THREAD

**Issue by gagaXD** [FriendsOfSymfony/FOSElasticaBundle#1154]
Hi,

We recently moved our version to dev-master. In our application, we use a custom repository, declared with the "Search annotation" : 

    /**
     * Proposition
     *
     * @ORM\Table(name="proposition")
     * @ORM\Entity(repositoryClass="AppBundle\Repository\PropositionRepository")
     * @Search(repositoryClass="AppBundle\SearchRepository\PropositionRepository")
     *
     * @Serializer\ExclusionPolicy("all")
     */
    class Proposition extends Announce{...}`

Here is the corresponding part in our configuration : 
        
    proposition:
        mappings:
            id: {type: integer}
            place_geopoint: { type: geo_point }
            title:
                type: multi_field
                fields:
                    title: { type: string, index: analyzed, analyzer: autocomplete_analyzer }
                    raw: { type: string, index: not_analyzed }
                description:
                    type: string
                    index: analyzed
                    analyzer: text_analyzer
            serializer:
                groups: [elastica]
            persistence:
                driver: orm
                model: AppBundle\Entity\Proposition
                provider:
                    batch_size: 10
                listener: ~
                finder:
                    service : app.propositions.paginated.finder

Finally, here is the custom repository : 

    namespace AppBundle\SearchRepository;
    
    class PropositionRepository extends Repository
    {
        public function search(Array $parameters)
        { .... }
    }

It was working like that when using the previous version, but now, the search annotation seems to not be taking into account. If we use this to call the search function : 

    $elasticaManager = $this->container->get('fos_elastica.manager');
    $entities = $elasticaManager->getRepository('AppBundle:Proposition')->search($params);

we get the following error : 
`Attempted to call an undefined method named "search" of class "FOS\ElasticaBundle\Repository`

But, if I remove the annotation, and declare the custom repository in the configuration file like this :
`repository: AppBundle\SearchRepository\PropositionRepository`
It work like a charm.

Is this a bug, or have I miss something during the migration ?

With kindest regards,

Gaetan

**Comment by giovannialbero1992** [comment]
This BC was introduced by PR #1119

**Comment by alekitto** [comment]
The Search annotation support has been removed, as the repository should be no more accessed through the `Bundle:Entity` notation, but requesting `index/type`.
This is necessary to allow multiple type to be attached to the same entity.

Probably we should remove the annotation class too...

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1119
