### ISSUE TITLE
Using the search_after parameter

### ISSUE THREAD

**Issue by tzfrs** [FriendsOfSymfony/FOSElasticaBundle#1165]
Hello, I'm using version 3.2. of your bundle and I wanted to try out the `search_after` parameter of Elastic Search https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-search-after.html

But when I'm using it I'm getting the error

> failed to parse search source. unknown search element [search_after]

with this code
```
$query = new Query();
$query = $sortedQuery;
$query->setParam('search_after', 123456789);
```

The value of the parameter key `search_after` is a value I have from a previous result's sort

```
{
    "took": 111,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 27704,
        "max_score": null,
        "hits": [
            {
                "_index": "app_dev",
                "_type": "product",
                "_id": "10054",
                "_score": null,
                "_source": {
                    // some data
                },
                "sort": [
		    "123456789"
                ]
            }
        }
    }
}
```

Does the version 3.2 not support `search_after` or how am I supposed to implement it?

**Comment by giovannialbero1992** [comment]
`search_after` is not present in elasticsearch <5.0.

**Comment by tzfrs** [comment]
Okay, thank you.
