### ISSUE TITLE
[RFC] Elasticsearch 5.x support roadmap

### ISSUE THREAD

**Issue by alekitto** [FriendsOfSymfony/FOSElasticaBundle#1170]
I'm currently testing this bundle with Elastica 5.0.0-beta1 which adds support for ES 5.x (WIP PR will be submitted shortly)

I think we should define a roadmap, since no release has been published with ES 2.x support.
Now i see two options:

- immediately tag a 4.0 release to support ES 2, bump master version to 5.x and work on ES 5 support
- work on a BC layer to support both ES 2 and 5

I prefer the first one to avoid doing conversions on mapping to maintain BC

**Comment by kironet** [comment]
I've installed elasticasearch last version. Looks like this bundle doesn't support version 5.0.2? Cause  I've got this error 

> [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                     
>   Wrong parameters for Elastica\Exception\ResponseException([string $message [, long $code [, Throwable $previous = NULL]]])

**Comment by XWB** [comment]
There are some things I want to have in 4.0:

https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/559
https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/557
https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/689

Maybe someone is willing to help?

**Comment by p365labs** [comment]
Wouldn't be better to tag a version for Elasticsearch 2.x (which in fact is an older version), and trying to implement (if necessary) the 
#559 
#557 
#689 

in the newest release for Elasticsearch 5.0 ?

what do u think @XWB

**Comment by XWB** [comment]
How difficult would it be to make a BC layer for both ES 2 and 5?

**Comment by thanosp** [comment]
If Elastica is not being BC with 2 why try making the bundle?
In fact why not join their and elasticsearch's versioning schema even and release 5.0 for 5.0?

**Comment by alekitto** [comment]
I agree with @thanosp.
Building a BC layer for both ES 2.x and 5.x implies transformations on mapping and can lead to issues and undefined/unwanted behaviors.

In my opinion we should tag a 4.0 release ASAP for ES 2.x and develop a stable version (5.0) for ES 5 very quickly as Elastica 5.0 is stable and ES has now reached 5.1.

**Comment by bitgandtter** [comment]
Im using this bundle, as a fork; with elastica 5.x with elastic 5.x and its working just fine, i understand that there are a lot of things that need to be improved and integrated to better handling next version but as @alekitto mention 5.x release of elastic its going to be use really quick because its speed, so it will be nice to put some effort into increase version on this

**Comment by The-Don-Himself** [comment]
@bitgandtter I have also used this bundle on my dev machines with Elasticsearch 5.1.1. For simple use cases it pretty much works without much modifications. For a bit more advance uses there are a few issues I found for example if you follow the dos for efficient bulk indexing https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/cookbook/populate-events.md, the method _optimize?max_num_segments=5 should now be _forcemerge?max_num_segments=5, also Elasticsearch 5.x changed the 'fields' parameter when querying docs fields to 'stored_fields'. These issues will be solved when FOSElastica updates the underlying https://github.com/ruflin/Elastica which is where most of the BC lies anyway, a proper list of which you can find on the 5.0.0-beta 1 release https://github.com/ruflin/Elastica/releases/tag/5.0.0-beta1

**Comment by giovannialbero1992** [comment]
Any news? I've received feedbacks by email that says the fork to take elasticsearch 5.* into bundle it works. We would like to see more activities on this bundle but it's impossible with this approach.
A solution can be that you give us write permission or otherwise we can leave this bundle to came back on our FazlandElasticaBundle.

**Comment by giovannialbero1992** [comment]
@XWB Have you read my comment? Do you have some news?

**Comment by XWB** [comment]
If we tag 4.0, does the current master branch fully works with elasticsearch 2.x ?

**Comment by XWB** [comment]
Please use master branch for ES 5 support.
