### ISSUE TITLE
Using --no-reset on an aliased index

### ISSUE THREAD

**Issue by PharaohAsh** [FriendsOfSymfony/FOSElasticaBundle#1176]
I use an alias for my elastic search index (`use_alias: True`) and I ran the populate command like this:

```app/console f:e:p --no-reset```

All was well, as the count started to go up. It wasn't until it finished that I went to check our catalogue and nothing worked. Went back to check the indexes and realised there was nothing there.

So it looks like, upon completion, the index is deleted? I'm assuming it's deleting the old index to alias itself to the new index, but since I've set a `--no-reset` flag, it doesn't recognise I want to keep my existing index.

Let me know if I'm missing understanding anything, thanks!

**Comment by oleg-andreyev** [comment]
Seems as #1178
