### ISSUE TITLE
ResponseException Fatal error: Wrong parameters for Exception

### ISSUE THREAD

**Issue by SerzhEvtushenko** [FriendsOfSymfony/FOSElasticaBundle#1177]
ResponseException class __construct method process exception incorrect for me.

$response->getError() containts array i.e. 
```
[type] => index_not_found_exception
[reason] => no such index
[resource.type] => index_or_alias
[resource.id] => app
[index_uuid] => _na_
[index] => app
```
Parent constructor (class Exception) expects string
`public function __construct($message = "", $code = 0, Exception $previous = null) { }`

so this line 35 of the ResponseException class  `parent::__construct($response->getError());`
throw the exception 

> Call Stack:
>     0.0044     229112   1. {main}() /work/www/shirtshop/app/console:0
>     0.0594    3242560   2. Symfony\Component\Console\Application->run(???, ???) /work/www/shirtshop/app/console:23
>     0.0635    3465800   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun(???, ???) /work/www/shirtshop/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:120
>     0.3620   19798536   4. Symfony\Component\Console\Application->doRun(???, ???) /work/www/shirtshop/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:90
>     0.3623   19799504   5. Symfony\Component\Console\Application->doRunCommand(???, ???, ???) /work/www/shirtshop/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:189
>     0.3665   20049656   6. Symfony\Component\Console\Command\Command->run(???, ???) /work/www/shirtshop/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:852
>     0.3742   20817208   7. FOS\ElasticaBundle\Command\PopulateCommand->execute(???, ???) /work/www/shirtshop/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
>     0.3743   20818432   8. FOS\ElasticaBundle\Command\PopulateCommand->populateIndex(???, ???, ???, ???) /work/www/shirtshop/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:124
>     0.3753   20839776   9. FOS\ElasticaBundle\Index\Resetter->resetIndex(???, ???, ???) /work/www/shirtshop/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:144
>     0.3761   20857432  10. Elastica\Index->create(???, ???) /work/www/shirtshop/vendor/friendsofsymfony/elastica-bundle/Index/Resetter.php:100
>     0.3761   20857664  11. Elastica\Index->delete() /work/www/shirtshop/vendor/ruflin/elastica/lib/Elastica/Index.php:257
>     0.3764   20892744  12. Elastica\Index->request(???, ???, ???, ???) /work/www/shirtshop/vendor/ruflin/elastica/lib/Elastica/Index.php:183
>     0.3764   20893368  13. FOS\ElasticaBundle\Elastica\Client->request(???, ???, ???, ???) /work/www/shirtshop/vendor/ruflin/elastica/lib/Elastica/Index.php:496
>     0.3764   20894328  14. Elastica\Client->request(???, ???, ???, ???) /work/www/shirtshop/vendor/friendsofsymfony/elastica-bundle/Elastica/Client.php:47
>     0.3765   20895880  15. Elastica\Request->send() /work/www/shirtshop/vendor/ruflin/elastica/lib/Elastica/Client.php:621
>     0.3776   21018936  16. Elastica\Transport\Http->exec(???, ???) /work/www/shirtshop/vendor/ruflin/elastica/lib/Elastica/Request.php:171
>     0.3806   21129848  17. Elastica\Exception\ResponseException->__construct(???, ???) /work/www/shirtshop/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:159
>     2.2464   21138064  18. Exception->__construct(???) /work/www/shirtshop/vendor/ruflin/elastica/lib/Elastica/Exception/ResponseException.php:35
> 
> 
>                                                                                                             
>   [Symfony\Component\Debug\Exception\FatalErrorException]                                                   
>   Error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]])

**Comment by ragusa87** [comment]
Hello,

I got the same issue. Downgrading to elasticsearch version 1.7 solved it, as elastica-bundle version 3.2.1 is using ruflfin/elastica version 2.3.1, which require elasticseach version 1.7.x. (https://github.com/ruflin/Elastica/blob/2.3.1/README.md)

``` bash
composer show | grep "elastic"
# friendsofsymfony/elastica-bundle        v3.2.1             Elasticsearch PHP integration for your Symfony2 project using Elastica
# ruflin/elastica                         2.3.1              Elasticsearch Client
```

**Comment by giovannialbero1992** [comment]
Seems a bundle's version problem. If you use elasticsearch 2.*, you must use elastica-bundle dev-master / 4.0.x-dev

**Comment by oleg-andreyev** [comment]
Same issue as #1200

**Comment by XWB** [comment]
Refer to https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1200 for the answer.
