### ISSUE TITLE
Allow adding new mapping fields without resetting the index

### ISSUE THREAD

**Issue by vmattila** [FriendsOfSymfony/FOSElasticaBundle#1179]
I do occassionally implement adding a new mapping field to documents. Currently there is no (?) way to put new fields to the mapping using the bundle without resetting the whole index.

PUT mapping API (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html) allows adding new fields to existing mappings without reindexing.

**Comment by fdellutri** [comment]
+1

**Comment by blackarcanis** [comment]
+1

**Comment by AlexeyKosov** [comment]
It's closed as completed, but I don't see any console command to update an index. So, was this feature actually added?
