### ISSUE TITLE
Search in related entity.

### ISSUE THREAD

**Issue by kironet** [FriendsOfSymfony/FOSElasticaBundle#1180]
Hey, how can I search with multiple parameters?
Example: I have an Entity "Posts" and related entity "Region" and I also want results based on region id. 

If I type: posts->title = "something" and region->id = 1 
or posts->title = "something"
or just region->id = 1 

Thanks

**Comment by Tobion** [comment]
You can use elasticsearch bool query for this: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html
It's available in Elastica with https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query/BoolQuery.php
