### ISSUE TITLE
ModelToElasticaAutoTransformer exception with DateTimeImmutable

### ISSUE THREAD

**Issue by icedevelopment** [FriendsOfSymfony/FOSElasticaBundle#1182]
When working with DateTimeImmutable objects the [ModelToElasticaAutoTransformer](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Transformer/ModelToElasticaAutoTransformer.php) throws the following exception: 

> Catchable Fatal Error: Object of class DateTimeImmutable could not be converted to string

In the [normalizeValue ](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Transformer/ModelToElasticaAutoTransformer.php#L110)method I think the following test

```php
if ($v instanceof \DateTime) {
    $v = $v->format('c');
```

should rather be

```php
if ($v instanceof \DateTimeInterface) {
    $v = $v->format('c');
```

**Comment by XWB** [comment]
@icedevelopment Can you have a look at https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1213?

**Comment by icedevelopment** [comment]
This fixes my problem.
Thank you !
