### ISSUE TITLE
PropertyAccessor magic_call param

### ISSUE THREAD

**Issue by delormejonathan** [FriendsOfSymfony/FOSElasticaBundle#1183]
Hi,

(Tell me if I'm wrong)
In Resources/config/config.xml, you are calling statically the PropertyAccessor instead of using the internal Symfony service.
So, you are by-passing the parameters defined in config.yml ([http://symfony.com/doc/current/reference/configuration/framework.html#property-access](http://symfony.com/doc/current/reference/configuration/framework.html#property-access))

I'm using a library which works with __call function and it needs to have magic_call enabled for attributes access.

Is there a way to modify the way PropertyAccessor is included to read global configuration ?

Thanks

**Comment by XWB** [comment]
Would you be able to make a PR?

**Comment by Tobion** [comment]
You can overwrite the parametes: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blame/master/src/Resources/config/config.xml#L8
Or even better, you can overwrite the `fos_elastica.property_accessor` and configure it differently. So I don't see the need to force using the symfony service.
