### ISSUE TITLE
[field_sort] unknown field [ignore_unmapped], parser not found

### ISSUE THREAD

**Issue by rubiodamian** [FriendsOfSymfony/FOSElasticaBundle#1188]
i get this error on FOS\ElasticaBundle\Subscriber\PaginateElasticaQuerySubscriber

`
protected function getSort($sortField, array $options = [])
    {
        $ignoreUnmapped = isset($options['sortIgnoreUnmapped']) ? $options['sortIgnoreUnmapped'] : true;
        $sort = [
            'order' => $this->getSortDirection($sortField, $options),
            'ignore_unmapped' => $ignoreUnmapped,
        ];
`
Is always adding the ignore_unmapped field and Elasticsearch Does not recognize it.
the trigger is "        $results = $this->getFinder()->createPaginatorAdapter($request->get('term'));
"

**Comment by XWB** [comment]
What Elasticsearch version are you using?

**Comment by rubiodamian** [comment]
@XWB Already try in its moment with all the stable versions of elasticsearch (2.4 and 4 )
And they all threw the same error
The problem occurs when you want to sort the results through the pager 
" $results = $this->getFinder()->createPaginatorAdapter($request->get('term'))"
And , although,you do not want to order by any criteria
The pager always tries to sort by some criterion and sends that extra field "ignore_unmapped"

So, when I try to use the example of the documentation
```
// Option 3b. KnpPaginator resultset
$paginator = $this->get('knp_paginator');
$results = $finder->createPaginatorAdapter('bob');
$pagination = $paginator->paginate($results, $page, 10);
```
This error appears

That's what i remember about this problem
I did not try to correct it since I wrote this issue

**Comment by XWB** [comment]
The `ignore_unmapped` was removed in the master branch. Can you try to update to the latest master branch?

**Comment by Tobion** [comment]
The ignore_unmapped option is only part of the 3.2 release, see https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/3.2.x/Subscriber/PaginateElasticaQuerySubscriber.php#L92

FosElasticaBundle 3.2 requires Elastica 2.* which is only compatible with elasticsearch 1.*
So you cannot use it with elasticsearch 2 as you tried. Please upgrade to the version `^5.0@dev` of FosElasticaBundle which will soon be released as stable.
