### ISSUE TITLE
Missing Pagerfanta dependency

### ISSUE THREAD

**Issue by werdlv** [FriendsOfSymfony/FOSElasticaBundle#1189]
`TransformedFinder` clearly depends on [Pagerfanta](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Finder/TransformedFinder.php#L92) however such dependency is missing.

However there is a `dev` [dependency](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/composer.json#L31) on it.

There is no mentions of `Pagerfanta` in Setup nor Usage sections of documentation.

The same applies for `knplabs/knp-paginator-bundle`.

**Comment by Tobion** [comment]
It's an optional dependency you have to install on your own.

**Comment by XWB** [comment]
See first comment.
