### ISSUE TITLE
New release (for 3.2.x branch)

### ISSUE THREAD

**Issue by thePanz** [FriendsOfSymfony/FOSElasticaBundle#1191]
Could you please release a new version for this bundle?
The latest changes from #1164 (commit a81d1c96) should be included as they fix quite an important issue :) thank you!

**Comment by lsmith77** [comment]
@XWB could we get a fresh bug fix release for this? if you want I can take care of this.

**Comment by XWB** [comment]
Here you go: https://github.com/FriendsOfSymfony/FOSElasticaBundle/releases/tag/3.2.2 :)

**Comment by thePanz** [comment]
Thank you! :)
