### ISSUE TITLE
Version 4.* : problem with attachement handling documentation

### ISSUE THREAD

**Issue by PierreNansot** [FriendsOfSymfony/FOSElasticaBundle#1194]
Just want to point out that ruflin/elastica v3.2 is already base64_encoding file

https://github.com/ruflin/Elastica/blob/3.2.0/lib/Elastica/Document.php#L188

So, by following your documentation, file are encoded twice. Making the search action non-functional.

I'm using vichuploader to manage my upload.
`public function getContent()
    {
        return file_get_contents($this->uploadedFile, 'r');
    }`

This is enough to correctly populate index with your file content.

Also, i think it would be a great addition to state which version of elasticsearch are functioning with foselasticabundle. As a complete new user, i installed 5.2 at first. It took me 3hours to understand why it didn't work and that i needed a previous version.

Anyway, thanks for everything. That's a very nice bundle.

**Comment by XWB** [comment]
Thanks https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/bed4f83d3bef7cfbf651e26abfe05bcf03fb8ba8
