### ISSUE TITLE
Doctrine Composite Key Compatibility

### ISSUE THREAD

**Issue by brunonm** [FriendsOfSymfony/FOSElasticaBundle#1196]
Is there a plan to make this bundle compatible with Doctrine composite keys?

http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/composite-primary-keys.html#composite-and-foreign-keys-as-primary-key

Populate command and entity listeners doesn't work, because the identifier isn't a scalar value.

Thank you!

**Comment by XWB** [comment]
Currently there are no such plans.
