### ISSUE TITLE
Elastic search Symfony error

### ISSUE THREAD

**Issue by sergiownd** [FriendsOfSymfony/FOSElasticaBundle#1200]
Hi guys, i Just got started with ElasticaBundle, but when I run

>  php app/console fos:elastica:populate

I get the error: 
[Symfony\Component\Debug\Exception\FatalErrorException]                                                   
  Error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]])

Any idea?
Thanks

**Comment by Kablex** [comment]
Same issue, the workaround is in ruflin/elastica/lib/Elastica/Exception/ResponseException.php at __construct function. Change:

`        parent::__construct($response->getError());
`

To:

`        parent::__construct((string)$response->getError());
`

I hope it works to you!

**Comment by sergiownd** [comment]
Hei @Kablex it worked, now i can see the error, but I'm unable to find why it does.
I just followed the steps on the readme and i get this error

> [Symfony\Component\Debug\Exception\ContextErrorException]  
>   Notice: Array to string conversion   

Anyone knows why?

**Comment by oleg-andreyev** [comment]
Most likely you have "broken" ruflin/elastica version, see https://github.com/ruflin/Elastica/commit/41a7a2075837320bc9bd3bca4150e05a1ec9a115

**Comment by sergiownd** [comment]
Hei @oleg-andreyev  how is it posible?
I've reinstaled the bundle, and now i get this error instead:
Resetting app
```
 17/17 [============================] 100%
Populating app/professionalRefreshing app

Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /Users/Sergio/Proyectos/dentworking_back/vendor/ruflin/elastica/lib/Elastica/Exception/ResponseException.php on line 34

                                                                                                            
  [Symfony\Component\Debug\Exception\FatalErrorException]                                                   
  Error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]])  
                     
```

**Comment by oleg-andreyev** [comment]
What version of ruflin you are using?

**Comment by sergiownd** [comment]
I actually dont know. Following the setup instructions `https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md`. It might be installed by default.
Am i missing this install?

**Comment by RichGwilt** [comment]
Did you find a solution @sergiownd ?

**Comment by oleg-andreyev** [comment]
@sergiownd okay, and which version Elasticsearch you are using?

**Comment by RichGwilt** [comment]
Is there no combination that works with either Elasticsearch 5.1 or 2.3 ?

**Comment by oleg-andreyev** [comment]
@RichGwilt can't say for sure but afaik FOS bundle isn't fully compatible with 5.x yet, maybe @XWB can say something.

**Comment by sergiownd** [comment]
@oleg-andreyev Hey oleg sry for the delay.
Im using elastic cloud 2.4.4, dunno how to get the elastic seach of the cloud

**Comment by oleg-andreyev** [comment]
@sergiownd you can post information from `<es_host>:9200` there should a JSON with information about.
But based on information from elastic.co, they are providing latest version of Elastica

**Comment by sergiownd** [comment]
Okai I finally found a solution. I created the cluster on the cloud using 1.7.x version. Everithing seems to works. Thanks

**Comment by oleg-andreyev** [comment]
Glad that you've found solution.
I'd recommend using ES2.4 at least with ruflin ~ 3.2 and FOS dev-master (maybe with exact commit) because ES 1.7 isn't maintained anymore :)

**Comment by sergiownd** [comment]
Hey @oleg-andreyev thats why i get the error in here https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1209? Cause of the version?
