### ISSUE TITLE
The option "delete" does not exist

### ISSUE THREAD

**Issue by thanosp** [FriendsOfSymfony/FOSElasticaBundle#1205]
- The `delete` extra option was added [here]( https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Command/PopulateCommand.php#L98) and seems being validated as an option [here](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Provider/AbstractProvider.php#L65)

Recently merged here: https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1093

**Comment by XWB** [comment]
Can you try https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/19d958cadf7b87cc498c54d5bb494d11bd802da9 ?

**Comment by thanosp** [comment]
I had tried that locally and yes it worked but didn't know if it was a correct change design-wise. Thanks :)
