### ISSUE TITLE
Bundle not persisting data.

### ISSUE THREAD

**Issue by sergiownd** [FriendsOfSymfony/FOSElasticaBundle#1209]
Hey guys, Im trying to create some index into my elastic. I'm using elastic cloud 1.7.x with the fos bundle 3.2.2 and elastica 2.3.1.
I'm getting this when I try to populate the data:

```
Resetting app
 17/17 [============================] 100%
Populating app/professionalsRefreshing app
 10/10 [============================] 100%
Populating app/clinicsRefreshing app
Refreshing app
```

Everything seems correct, but when I run the `/_search?pretty ` I don't get the data.
Thanks

**Comment by oleg-andreyev** [comment]
Go to `head` plugin and check, index should exists, it's impossible that data isn't persisted, only if you are using custom provider and do not call `addDocuments`

**Comment by XWB** [comment]
Answer was given in https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1200
