### ISSUE TITLE
Issue with populate command

### ISSUE THREAD

**Issue by m2broth** [FriendsOfSymfony/FOSElasticaBundle#1221]
By running "php bin/console fos:elastica:populate" bundle produces next error:

[Symfony\Component\Debug\Exception\FatalThrowableError]                                                                     
  Wrong parameters for Elastica\Exception\ResponseException([string $message [, long $code [, Throwable $previous = NULL]]]) 

Ran on Symfony 3 + php 7.1

**Comment by kipit** [comment]
This is probably a version mismatch between your Elasticsearch version and the supported versions by ruflin/elastica. What friendsofsymfony/elastica-bundle version are you using ? What's your Elasticsearch version ?

**Comment by bxnxg** [comment]
Hy, same here, I have : 
- Symfony 3.1.10
- FOSElasticaBundle 3.2.2
- ruflin/elastica 2.3.1
- Also : jms/serializer 1.5

And in my Dedicated server, I have installed Elasticsearch version (curl connection is working) :
- Version: 5.2.2, Build: f9d9b74/2017-02-24T17:26:45.835Z, JVM: 1.8.0_121

When I'm running "php bin/console fos:elastica:populate", I get also :+1: 
`[Symfony\Component\Debug\Exception\FatalThrowableError]                                                                     
  Wrong parameters for Elastica\Exception\ResponseException([string $message [, long $code [, Throwable $previous = NULL]]]) `

My configuration seems correct :
`fos_elastica:
    clients:
        default: { host: 123.45.67.89, port: 9200 }
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    indexes:
        app:
            #client: default
            types:
                Product:
                    mappings: ~
                    persistence:
                        driver: orm
                        model:  MyBundle\Entity\MyEntity
                        provider: ~
                        listener: ~ # by default, listens to "insert", "update" and "delete"
                    serializer:
                        groups: [elastica]
                        #version: '1'
                        serialize_null: true`

**Comment by bxnxg** [comment]
Ok, after searching in previous issue, it seems that FOSElastica is not fully compatible with last version of ES (5.X). 
A contributor recommend using ES 2.4 : [](https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1200#issuecomment-283647354)

**Comment by bxnxg** [comment]
Same error with ES 2.4...

**Comment by mangelsnc** [comment]
Wow, the 1.7.x seems too old, isn't it?

**Comment by kipit** [comment]
@bxnxg [Elastica 2.3.1 require Elasticsearch 1.7.X](https://github.com/ruflin/Elastica/tree/2.3.1). You may try FOSElasticaBundle v4.0.0 to work with ES 2.4, maybe ES 5.X. To get the good library version to work with 5.X, you need to get FOSElasticaBundle 5.0.x-dev.

**Comment by The-Don-Himself** [comment]
Guys just add 
````
"friendsofsymfony/elastica-bundle": "dev-master"
````
to composer.json if you want to use latest Elasticsearch 5.x with this bundle. 

Ps. I used to think it's the bundle's fault, but really it isn't for all the major databases I use, Elasticsearch changes just too quickly for many people to keep up, especially because many changes break backwards compatibility. Note version 6 is around the corner with suggestions to deprecate 'Types' and remove them in 7.
