### ISSUE TITLE
Support for username/password HTTP authentication

### ISSUE THREAD

**Issue by Markard** [FriendsOfSymfony/FOSElasticaBundle#1224]
Hello.

Elastica can handle HTTP auth if you set username and password for a connection. [Link](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Transport/Http.php#L101)

It would be great if the bundle allows to setup these parameters.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1225
