### ISSUE TITLE
[Question] There are plans to support the latest ES versions? 5.x

### ISSUE THREAD

**Issue by mangelsnc** [FriendsOfSymfony/FOSElasticaBundle#1230]
I want to update ES to v5.x and still use this Bundle, there are plans to support this version?

**Comment by kbsali** [comment]
@mangelsnc we are currently migrating to ES 5.3 with v4.0.0 of this bundle and so far it seems to be working ok.
Do you have anything in mind making it incompatible?

**Comment by Tobion** [comment]
current master (upcoming version 5) is already compatible with ES 5. See https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/CHANGELOG-5.0.md

**Comment by Tobion** [comment]
@XWB can we release version 5 of the bundle?

**Comment by XWB** [comment]
I'll start working on it.

**Comment by dincho** [comment]
> Do you have anything in mind making it incompatible?

I just hit "Script" class incompatibility in ES 5.2 with 4.0 of this bundle, which depends on older incompatible Elastica version.

**Comment by advancingu** [comment]
@XWB Any progress on a stable release? Thanks for your work.

**Comment by makasim** [comment]
more info in https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1317
