### ISSUE TITLE
How to result only ids?

### ISSUE THREAD

**Issue by robert0770** [FriendsOfSymfony/FOSElasticaBundle#1234]
Hello, i need to get only id or other one field in result,

can i set this before allocate $result with full doctrine entities?

(i dont want entities in result i need only one column)

**Comment by XWB** [comment]
I don't think that's possible with Doctrine. In order to get partial result, you would need to return raw results. That can be done by using the search service instead of the finder service. I.e. `fos_elastica.index.search.{type_name}`.

**Comment by robert0770** [comment]
thx for replay
im do that with Elastica PHP IO
now use foselastica only for mapping and update

**Comment by XWB** [comment]
:+1:
