### ISSUE TITLE
New Feature : Populate Command Size

### ISSUE THREAD

**Issue by The-Don-Himself** [FriendsOfSymfony/FOSElasticaBundle#1237]
The populate command has some awesome features like batch size and offset but lacks a size parameter to limit the size for example
````
php bin/console fos:elastica:populate --no-reset --offset=2000 --size=8000
````
This would populate elasticsearch with entities between id 2k and 8k.

I'm wondering whether such a feature has been discussed before and if not does any one know of the complexities involved in making it before I dig deeper into the code?

**Comment by XWB** [comment]
It would be a nice addition. Feel free to open a PR :)

**Comment by The-Don-Himself** [comment]
Thanks for the encouragement, I've started looking into this, and it seems it wouldn't be too hard to implement as it just requires allowing the $nbObjects variable in the Provider Classes to be optionally configurable from options, correct?

If so, will be sending in PR soon :)

**Comment by makasim** [comment]
fixed https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1336
