### ISSUE TITLE
How to setFields (like select in sql)

### ISSUE THREAD

**Issue by robert0770** [FriendsOfSymfony/FOSElasticaBundle#1238]
How to setFields in elastica?

$query->setFilter($bool)->setFields(array('id'));

this work, but 

$query->setFilter($bool)->setFields(array('id', 'offer.mark'));

this dont work and i dont see offer.mark

how to do this?

**Comment by Tobion** [comment]
What you are looking for is https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html which can be set with https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Query.php#L411

**Comment by XWB** [comment]
See above.
