### ISSUE TITLE
Transport/Http.php on line 130 [2017-05-20 17:30:20] php.CRITICAL: Fatal Error: Out of memory

### ISSUE THREAD

**Issue by anboo** [FriendsOfSymfony/FOSElasticaBundle#1249]
# bin/console fos:elastica:populate
Resetting app
Refreshing app
  1600/12807 [===>------------------------]  12%
Populating app/item
mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 1965424640) (tried to allocate 93868952 bytes) in /var/www/mytradeoffers.ru/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php on line 130
[2017-05-20 17:30:20] php.CRITICAL: Fatal Error: Out of memory (allocated 1965424640) (tried to allocate 93868952 bytes) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Out of memory (allocated 1965424640) (tried to allocate 93868952 bytes) at /var/www/mytradeoffers.ru/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php:130)"} 

                                                                               
  [Symfony\Component\Debug\Exception\OutOfMemoryException]                     
  Error: Out of memory (allocated 1965424640) (tried to allocate 93868952 byt  
  es)                                                                          
                                                                               

fos:elastica:populate [--index [INDEX]] [--type [TYPE]] [--no-reset] [--offset OFFSET] [--sleep SLEEP] [--batch-size BATCH-SIZE] [--ignore-errors] [--no-overwrite-format] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by jorge07** [comment]
try `php -d memory_limit=3G bin/console f:e:p`

**Comment by XWB** [comment]
You may want to increase the memory limit.
