### ISSUE TITLE
help: paginated search not working?

### ISSUE THREAD

**Issue by kiwibun** [FriendsOfSymfony/FOSElasticaBundle#1256]
I'm facing a problem while using paginated search with the ElasticaBundle in the latest version .

My code in the controller:

$results = $finder->findPaginated($term);
$results->setMaxPerPage(10);
$results->setCurrentPage($page);
$results->getCurrentPageResults();

This works for page 1, but not for e.g. page 2. I get a 404 not found exception (below), even if there should be results (when I debug during the page-1-request getNbResults() returns 34; getNbPages() returns 4).

Exception: >>> OutOfRangeCurrentPageException: Page "2" does not exist. The currentPage must be inferior to "1" <<<

Are you able to reproduce this behavior?

Thanks in advance
Chris

**Comment by kiwibun** [comment]
I resolved the error. The error was just a version problem.

Issue may be closed.

Best regards
Chris

**Comment by XWB** [comment]
:+1:
