### ISSUE TITLE
Add keyword subfield when fielddata is needed during sort

### ISSUE THREAD

**Issue by emudojo** [FriendsOfSymfony/FOSElasticaBundle#1263]
We migraterd from 2.4 to 5.4 (elasticsearch not the bundle), and then from 4.x to 5.x (the bundle), and all the sudden all of our queries started to fail due to unmapped fielddata on certain text fields, what's the best way to deal with it, I had to add a listener to modify the sort field when using pagination to include .keyword at the end but seems like a hack to me.

Is there a way in which this can be done automatically by the bundle?

**Comment by k20human** [comment]
Hi,
Same problem here
