### ISSUE TITLE
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: There is no extension able to load the configuration for "   clients" (in 

### ISSUE THREAD

**Issue by rmfwebmaster** [FriendsOfSymfony/FOSElasticaBundle#1265]
$ bin/console fos:elastica:populate
**PHP Fatal error:**  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: There is no extension able to load the configuration for "   clients" (in /var/www/html/es_symfony3/app/config/foselasticabundle.yml). Looked for namespace "   clients", found "framework", "security", "twig", "monolog", "swiftmailer", "doctrine", "sensio_framework_extra", "fos_elastica", "debug", "web_profiler", "sensio_distribution" in /var/www/html/es_symfony3/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php:431
Stack trace:
#0 /var/www/html/es_symfony3/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(401): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->validate(Array, '/var/www/html/e...')
#1 /var/www/html/es_symfony3/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php(69): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile('/var/www/html/e...')
#2 /var/www/html/es_ in /var/www/html/es_symfony3/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php on line 118

**Comment by Tobion** [comment]
"   clients" suggests that there is whitespace where it should not be.
What does your config for fos_elastica look like?
