### ISSUE TITLE
_parent field deletion bug (_routing)

### ISSUE THREAD

**Issue by mpiot** [FriendsOfSymfony/FOSElasticaBundle#1268]
Hi,
I use the parent configuration like it:

     _parent:
         type: "strain"
         property: "chromosome.strain"

When I execute `bin/console fos:elastica:populate`, I've no problem, idem for indexing by listener, and when searching.

But when I want to delete an entry, I've this error:

> [Elastica\Exception\Bulk\ResponseException]                                                   
  Error in one or more bulk request actions:                                                    
  delete: /app/locus/112926 caused routing is required for [app]/[locus]/[112926] [index: app] 

In debug toolbar the curl query is:

    curl -XPOST 'http://es:9200/app/locus/_bulk' -d '"{\"delete\":{\"_id\":112926}}"'

It appear, the bug come from a ?routing=STRAIN_ID missing in the url.

In `FOS\ElasticaBundle\Persister\ObjectPersister` the method `deleteManyByIdentifiers` call the method `deleteIds` from Elastica: http://elastica.io/api/latest/classes/Elastica.Client.html

> deleteIds(array  $ids, string|\Elastica\Index  $index, string|\Elastica\Type  $type, string|boolean  $routing = false) : \Elastica\Bulk\ResponseSet

If I manually add the $routing = parentId, it's work. 

How can I access to fields (like in `FOS\ElasticaBundle\Persister\ObjectPersister` but in `FOS\ElasticaBundle\Doctrine\Listener`, to use the propertyAccessor, get the parent ID, and send it as argument in `->deleteManyByIdentifiers` ?

Then, I can have in `FOS\ElasticaBundle\Persister\ObjectPersister`:

    /**
     * {@inheritdoc}
     */
    public function deleteManyByIdentifiers(array $identifiers, $routing = false)
    {
        try {
            $this->type->getIndex()->getClient()->deleteIds($identifiers, $this->type->getIndex(), $this->type, $routing);
        } catch (BulkException $e) {
            $this->log($e);
        }
    }

And in `FOS\ElasticaBundle\Doctrine\Listener`, I set $routing if there is a _parent. But I don't know how to access mapping, or fields from the Listener (to know what is tha parent mapping)

Finally, maybe, we can just edit the bulk request ?
Actually:

    {"delete":{"_id":113088}}\n
    {"delete":{"_id":113089}}\n
    {"delete":{"_id":113090}}\n

I would want to have:

    {"delete":{"_id":113088, "_routing": 101}}\n
    {"delete":{"_id":113089, "_routing": 101}}\n
    {"delete":{"_id":113090, "_routing": 101}}\n

Someone know, if there is a way to do it ? A listener like PRE_REQUEST ? or something like it ?

**Comment by jhogendorn** [comment]
I've also run into this bug where deletion of entries with parent fields requires routing.

**Comment by mpiot** [comment]
No one I've an idea ? I've search a little but, I don't really know the FOSElastica code...

Is there a way to get the _routing information in `FOS\ElasticaBundle\Doctrine\Listener` ? Because in the `FOS\ElasticaBundle\Persister\ObjectPersister` we just have an array of ids, if we want to use objects it don't work, because id is on null (after deletion in doctrine).

I don't see an other way than get the _routing information in the listener, and use an array with the identifier and _routing information, then in `FOS\ElasticaBundle\Persister\ObjectPersister` treat by routing packet, and define the _routing to permit delete it from ES.

For the moment I'm forced to set the delete listener on false, and manually run a populate after delete an Object. But it takes a lot of time... (more than 1.000.000 documents...)

**Comment by ThomasLabstep** [comment]
The year is 2018, June 13th. We still cannot delete a document with _parent.

ruflin has support for it though. So let's fork and pass the _routing option manually.

**Comment by XWB** [comment]
I'm not sure how to fix it, I'm not working with parent documents. Perhaps somebody can open a PR?

**Comment by ThomasLabstep** [comment]
I have a PR coming.

**Comment by ThomasLabstep** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1428
