### ISSUE TITLE
multi sync accross type

### ISSUE THREAD

**Issue by Gu3** [FriendsOfSymfony/FOSElasticaBundle#1270]
Hi !
I'm struggling with an issue since 2 days : I've got several indexes with nested properties inside all of them, for example : 

            types:
                access :
                    mappings:
                        id: ~
                            person :
                               type: 'nested'
                               properties:
                                    id: ~
                                    familyName:  ~  

                 examen :
                    mappings:
                        id: ~
                            jury :
                               type: 'nested'
                               properties:
                                    id: ~
                                    members:  ~
                                       properties:
                                          person :
                                             type: 'nested'
                                             properties:
                                                id: ~
                                                   familyName:  ~  

If I change the familyName inside access type, how the update can be effective inside examen type too ? 
Actually if I've got a person: Bob with an id : 1 
I update Bob to Tom, thanks to a listener on Person entity, access is updating too. 
But inside Examen, person is still Bob... 

Do I need to check every relations where person is used in order to updated all types one by one, or do I something wrong with my conf ? 

Thanks ! 

Vincent.

**Comment by iBasit** [comment]
+1 | haha.. I'm looking to find same answer, to share model across each other.

**Comment by Gu3** [comment]
Hi, 
I found a way to solve this issue : 
- I get all association mappings for the entity with doctrine
- I get elastica mapping for my index
- for each associations, I search all the position of the mappedBy params inside the elastica mapping => so I have the right path of my elastica property
- for each path, I execute an elastica query to find all results for the Id updated
- if I've got results, I use replaceMany of elastica persister service
- and it's done!

the operation could be expensive, so I execute this inside a kernel.terminate listener (with PHP-Fpm)

Hope it's could be usefull...

Vincent.
