### ISSUE TITLE
AbstractElasticaToModelTransformer sorting issue

### ISSUE THREAD

**Issue by icedevelopment** [FriendsOfSymfony/FOSElasticaBundle#1273]
Hi,

In my model transformers (which extend [AbstractElasticaToModelTransformer](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/v4.0.0/Doctrine/AbstractElasticaToModelTransformer.php)), in the method findByIdentifiers() I'm creating a doctrine QueryBuilder and using the orderBy method to sort the results.

```php
    protected function findByIdentifiers(array $identifierValues, $hydrate)
    {
        // ...

        $qb->where($qb->expr()->in('e.' . $this->options['identifier'], ':values'))
            ->setParameter('values', $identifierValues)
            ->orderBy('label')
        ;

        return $qb->getQuery()->setHydrationMode($hydrationMode)->execute();
    }
```

The problem is that it doesn't have any effect because in [AbstractElasticaToModelTransformer#transform()](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/v4.0.0/Doctrine/AbstractElasticaToModelTransformer.php#L78) the results are automatically reordered by id :

```php
    public function transform(array $elasticaObjects)
    {
        // ...

        // sort objects in the order of ids
        $idPos = array_flip($ids);
        usort(
            $objects,
            function ($a, $b) use ($idPos, $identifier, $propertyAccessor) {
                if ($this->options['hydrate']) {
                    return $idPos[(string)$propertyAccessor->getValue(
                        $a,
                        $identifier
                    )] > $idPos[(string)$propertyAccessor->getValue($b, $identifier)];
                } else {
                    return $idPos[$a[$identifier]] > $idPos[$b[$identifier]];
                }
            }
        );
    }
```

(see commits : https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/e9cb629caaee92920cb9810178ea12b3734b00a5 and https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/de6e25e74b775884b016b488060974e56088128e)

Why is this the current behavior?
Is there any way to sort my results without having to override the transform method to remove this code?

**Comment by XWB** [comment]
I myself would simply override the transform method.

**Comment by icedevelopment** [comment]
Thanks for your reply. I think that's what I'll do for now even if this seems a little dirty.
The results should probably not be automatically reordered by default but again I'm not sure why this is the current behavior.
