### ISSUE TITLE
RepositoryManager is deprecated

### ISSUE THREAD

**Issue by iBasit** [FriendsOfSymfony/FOSElasticaBundle#1275]
RepositoryManager is deprecated on `4.0`, but when checking the doc file for implementation for custom repository, it still shows old method.

https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/4.0.x/Resources/doc/cookbook/custom-repositories.md

What function / class / service should we replace it with?

**Comment by aLkRicha** [comment]
i'm also interested in this question.

**Comment by aleixfabra** [comment]
+1

**Comment by Luciam91** [comment]
Where is this listed as deprecated? I can't see anything that marks this class as deprecated

**Comment by aleixfabra** [comment]
@Luciam91 
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Doctrine/RepositoryManager.php#L24

**Comment by Luciam91** [comment]
Ah thanks! Wasn't clear from the issue that this was to do with the Doctrine one, as reading the code samples in the docs it all relates to FOS\ElasticaBundle\Manager\RepositoryManager which isn't deprecated :)

My apologies

**Comment by XWB** [comment]
We should remove it in the master branch.

**Comment by aleixfabra** [comment]
So, it's not deprecated, right?
