### ISSUE TITLE
Documentation is complete garbage

### ISSUE THREAD

**Issue by malas** [FriendsOfSymfony/FOSElasticaBundle#1276]
I am sorry to say, but current documentation is completely unusable. It covers only minor part of possible functionality/configuration. Having in mind that Elastica documentation is even worse, this bundle tends to be unusable.

Is this bundle development still active?

How could i help to improve the documentation?

**Comment by XWB** [comment]
What kind of documentation are you missing?

**Comment by malas** [comment]
Lets see:
* configuration complete example. currently ```config:dump-reference fos_elastica``` has so many ```~``` that it is too difficult to understand what am i able to config.  How can i configure index settings? config dump gives you this:
```
    fos_elastica:
      indexes:
        name:
          settings: []
```
* Example on how to use raw array or raw json queries.
* Example on how to configure custom analyzers.
* Example on how to debug your queries against analyzers.

And there can be lots of others improvements. These are just the things i ran into in the past few weeks.

**Comment by XWB** [comment]
Index settings are available at https://www.elastic.co/guide/en/elasticsearch/reference/current/indices.html

FOSElasticaBundle does not configure any index settings, the configuration simply accepts [any value](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/DependencyInjection/Configuration.php#L198). Each Elasticsearch version can come with different settings, hence it's not really possible to configure them in this bundle.

**Comment by renanbr** [comment]
In addition it could be nice to have a "Configuration Reference", at least for bundle's specificities (example: http://symfony.com/doc/master/bundles/DoctrineBundle/configuration.html)

**Comment by malas** [comment]
@XWB ElasticSearch does not change its configuration so often, not giving any clue how to write configuration or several real world queries is just poor documentation.

You are the owner of this repo, so you must use it in many projects, why not just copy paste some queries from them?

**Comment by The-Don-Himself** [comment]
> @XWB ElasticSearch does not change its configuration so often, not giving any clue how to write configuration or several real world queries is just poor documentation.

@malas I don't think you've used Elasticsearch for that long if you'd actually say this. Are you even aware that version 1.7.x was released in 2015, 2.x in 2016, 5.x in 2016, 6.x in 2017? All of them with breaking changes to previous versions? All of which gracious developers spend their valuable time, uncompensated to create open source packages for people like you to whine about and call their work garbage. Because by calling the documentation garbage effectively that's what you're doing.

I'm no maintainer of FOSElasticaBundle but I took offence your issue and tone.

> You are the owner of this repo, so you must use it in many projects, why not just copy paste some queries from them?

This is just asking to be spoon-fed.

Anyway, all the best getting help.

**Comment by malas** [comment]
Effectively you are not contributing anything to the issue and just spill your aggression here. Not a single F was and will be given.

My tone is set in the first post:

> How could i help to improve the documentation?

Over sensitivity is a crime for humanity.

**Comment by markwalkom** [comment]
> My tone is set in the first post:

That is correct - _Documentation is complete garbage._
If you'd like to assist then being so negative out of the gates really does offset anything else you say, especially given you double down on the sentiment in later posts. Here's some great advice - https://twitter.com/mjg59/status/926095570816589825

**Comment by XWB** [comment]
> ElasticSearch does not change its configuration so often

I have seen changes even between 5.x versions. It would be painful to maintain.

But why would we duplicate the configuration in the first place when everything is already available at https://www.elastic.co/guide/en/elasticsearch/reference/current/indices.html ?

> not giving any clue how to write configuration or several real world queries is just poor documentation

Rule of thumb is that `fos_elastica.indexes.name.index` accepts any value as described at https://www.elastic.co/guide/en/elasticsearch/reference/current/indices.html

Writing queries is a different topic. For that, one has to understand [Elastica](https://github.com/ruflin/Elastica).
