### ISSUE TITLE
Using Join

### ISSUE THREAD

**Issue by silentiumtempus** [FriendsOfSymfony/FOSElasticaBundle#1288]
Hi there,

I'm trying to figure out how to use joins with the bundle.

I have two classes: **EntryEntity** and **FolderEntity**
EntryEntity class has some custom data.
FolderEntity class also has some custom data and a foreign key (**OneToOne**) which links it with EntryEntity class by its **id** (folder.archiveEntry=entry.id) field.

So, what I want is to get&display all fields of EntryEntity class with one field of FolderEntity class joined.

From what I found here [https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/usage.md](usage.md) I created a new method in my repo class 

    public function createEntriesAndErrorsQueryBuilder($entityAlias)
    {
        return $this->queryBuilder
            ->select($entityAlias, 'o')
            ->from('AppBundle:EntryEntity', 'o')
            ->innerJoin('AppBundle:FolderEntity', 'folders', Join::WITH, 'o.id = folders.archiveEntry');
    }

and set up it in config
                  elastica_to_model_transformer:
                    query_builder_method: createEntriesAndErrorsQueryBuilder

Actually I don't know what to do next, when I try to change the content of select() I receive an error.
For example, I wanted to change 'o' alias to 'entries' in above function and got an exception:
**[Semantical Error] line 0, col 7 near 'o, entries FROM': Error: 'o' is not defined.**

I don't understand where this $entryAlias is set or hot to get the joined data.
Please assist here.

**Comment by The-Don-Himself** [comment]
@silentiumtempus I don't quite get what you want to join. There are normally 2 databases involved here a doctrine orm powered one e.g MySQL where you'd get the data and Elasticsearch where you'll send the data to benefit from Elasticsearch features like text search and aggregations. This library helps you send that data over to Elasticsearch as well as query the same data from Elasticsearch. When you send that data, you might need to query 2 or 3 tables to get it, there is where the first notion of a join comes in, the bundle can help you reduce it to one using joins. Secondly, when you get that data back from Elasticsearch, this bundle would issue a query to your MySQL database to get the original data back, again this might span 2 or 3 tables hence where the second notion of a join comes in. Which one are you trying to achieve?

Note: there is a third notion of a join, one done by Elasticsearch itself in a relational database hackish way but that is well out of the scope of this bundle in that you should first research how to do it from Elasticsearch docs.

**Comment by silentiumtempus** [comment]
@The-Don-Himself The search has to be done querying only one table, so I need basically to query one table and receive a set of entries. Then I need to get additional data from the other table which is mapped with the first one through OneToOne dependency. Not sure how to implement this with the bundle.

**Comment by The-Don-Himself** [comment]
I still think you may be confusing things a little, when you talk about tables, that is a relational database like MySQL, when you talk search that is (I assume) Elasticsearch. 

It may be a bit hard for you to map tables in MySQL to indexes in Elasticsearch **while** still maintaining the relationships **without** embedding the tracks within albums and albums within bands.

**Comment by The-Don-Himself** [comment]
Check out https://www.elastic.co/guide/en/elasticsearch/guide/master/parent-child.html for reference.

**Comment by The-Don-Himself** [comment]
And also https://www.elastic.co/guide/en/elasticsearch/guide/master/parent-child-performance.html

**Comment by silentiumtempus** [comment]
OK, my explanations are not accurant because I don't fully understand how things work here.  Also I'm not sure what's the exact layer of the problem.

The thing is what I found in man page doesn't work for me:

When returning results from Elasticsearch to be transformed by the bundle, the default createQueryBuilder method on each objects Repository class will be called. In many circumstances this is not ideal and **you'd prefer to use a different method to join in any entity relations** that are required on the page that will be displaying the results.

            user:
                persistence:
                    elastica_to_model_transformer:
                        query_builder_method: createSearchQueryBuilder

An example for using a custom query builder method:

class UserRepository extends EntityRepository
{
    /**
     * Used by Elastica to transform results to model
     * 
     * @param string $entityAlias
     * @return  Doctrine\ORM\QueryBuilder
     */
    public function createSearchQueryBuilder($entityAlias)
    {
        $qb = $this->createQueryBuilder($entityAlias);
        
        $qb->select($entityAlias, 'g')
            ->innerJoin($entityAlias.'.groups', 'g');
            
        return $qb;
    }
}

I found out the description is correct, I actually want to join an entity relation **after** the data was found, not querying multiple entities (tables here), but when I try to use the above example it fails for me... Could you explain, please?

**Comment by The-Don-Himself** [comment]
Yes I can, and I think now we're getting somewhere. Note that the Github issues is not the best place for this back and forth (since it's going to send emails to all maintainers of this bundle on each comment) but perhaps it will help others.

This bundle helps you map Doctrine->FOSElastica->Elasticsearch and Elasticsearch->FOSElastica->Doctrine. It does so by using the ID field specified in each entity (hence why compound primary keys are not supported last I checked).

In your case, you'll get back the band ID, as well as any embedded documents like albums and tracks. The bundle will then use the Band ID to query the Doctrine backed database for the Band entity. But sometimes you want more than just the band e.g it's albums. Doctrine will lazy load this i.e on demand which results in another query or queries, so to avoid many queries this bundle allows you to hook into the query build using a customQueryBuilder so as to issue joins when fetching the band entity so as to do it all in one query.

So in your case, an example would be, for example
````
   $qb = $this->createQueryBuilder($entityAlias);

    $qb->select($entityAlias, 'b')
        ->leftJoin($entityAlias.'.albums', 'a');
        ->leftJoin('a.tracks', 't');

    return $qb;
}
````

**Comment by silentiumtempus** [comment]
Thanks, I will mind your advice for the future, this is just a first time I got problem of this kind.

The thing is I don't understand from the man what $entityAlias means at all and how it's received by the queryBuilder here.  When tried to mirror the manual example that didn't work for me.
To clear things here's the my repository source (createEntriesAndErrorsQueryBuilder()):

https://github.com/silentiumtempus/lencor_archive/blob/master/src/AppBundle/Repository/ArchiveEntryRepository.php

I use the common join syntax to load an entity from other table using ID field.

**Comment by silentiumtempus** [comment]
In my example I receive only 'o' as ArchiveEntryEntity, but when I try to add some filed from the other entity, like 
        return $this->queryBuilder
            ->select('o', 'folders.someField')
I got an error
