### ISSUE TITLE
[Minor] reference to framework assets which are not here

### ISSUE THREAD

**Issue by dkarlovi** [FriendsOfSymfony/FOSElasticaBundle#1289]
The collector view is [referring to `picto_less.gif`, `picto_more.gif` from framework assets](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/views/Collector/elastica.html.twig#L77-L89), but those are not there anymore.

**Comment by XWB** [comment]
Thank you. We should remove/update the assets from the template.

**Comment by dkarlovi** [comment]
Fixed in #1304
