### ISSUE TITLE
Not implementing reset() from DataCollectorInterface is deprecated in Symfony 3.4

### ISSUE THREAD

**Issue by ThomasTr** [FriendsOfSymfony/FOSElasticaBundle#1291]
I'm upgrading a Symfony app to 3.4 and I found this deprecation related to your ElasticaDataCollector:

User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since version 3.4 and will be unsupported in 4.0 for class "FOS\ElasticaBundle\DataCollector\ElasticaDataCollector".

**Comment by Tobion** [comment]
#1331
