### ISSUE TITLE
aggregation add query 

### ISSUE THREAD

**Issue by fyher** [FriendsOfSymfony/FOSElasticaBundle#1294]
when I create the aggregation like this 

 $agg = new \Elastica\Aggregation\Sum("sumimpressions");
        $agg->setName("sumimpressions");
        $agg->setField('sumimpressions');
        $query->addAggregation($agg);

How I add the search field too : 
 $fieldQuery = new \Elastica\Query\Match();
        $fieldQuery->setFieldQuery('site', $infosite->getId());

 $res=$finder->find($query,0);

You see my question ? 

thanks

**Comment by fyher** [comment]
ok I found this 

 $query->setQuery($boolQuery);

but after how I access to the return aggregation because $res is empty

**Comment by XWB** [comment]
You can fetch the aggregation from \Elastica\ResultSet

See https://github.com/ruflin/Elastica/blob/master/lib/Elastica/ResultSet.php#L140
