### ISSUE TITLE
Using Scroll API inside Type Custom Repository

### ISSUE THREAD

**Issue by vulfhelm** [FriendsOfSymfony/FOSElasticaBundle#1297]
Hello, i'm struggling with the Scroll API.
I created a Custom Repository for one of my type and I need to use the Scroll API to iterate on a large data result. My query is ready. Basic searching and pagination works but don't suite for my needs...
I'm just looking for an example, i'm quite sure there is something to do with 'finder' but i'm not able to find what...

I'm using FOSElasticaBundle 5.0

Thanks in advance :-)

**Comment by renanbr** [comment]
Are you looking for custom sorter?

If not, I recommend see:

- [ruflin/elastica](https://github.com/ruflin/Elastica) (the library behind this bundle)
- https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html (the data structure expected)

If yes, here is how (more or less) I'm using script sorting:

```php
// ...

/* @var $query Elastica\Query */
$query->addSort([
    '_script' => [
        'type' => 'string',
        'order' => 'desc',
        'script' => [
            'lang' => 'painless',
            'inline' => "... your code here, and you cand get params.foo ..."
        ],
        'params' => [
            'foo' => 'bar',
        ],
    ]
]);

// ...
```

the script inside `inline` key, when executed, returns the weight of each row, then I can get the more "relevant" to me (e.g.: 7 will be catched before 3).

https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-painless.html

**Comment by minhtranite** [comment]
@vulfhelm, Can you share you solution.
I faced this problem:
```
An exception has been thrown during the rendering of a template ("Result window is too large, from + size must be less than or equal to: [10000] but was [120000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting. [reason: all shards failed]").
```

**Comment by vulfhelm** [comment]
Hello @minhtranite .
Here is how i faced the problem... There is maybe a better way to achieve that but it works.

Create a new search object with your index : 
$fosElasticaIndexManager == fos_elastica.index_manager service. (Get it the way you want, by container in a Controller or injecting it in a service)
`$search = $fosElasticaIndexManager->getIndex('your_index')->createSearch();`

Add your type(s) to your search object.
`$search = $search->addType('video'); `

Build your query and add it to your search object. size must be less than 10000 as figured in your problem. Consider $query an Elastica Query object
`$search->setQuery($query);`

Create now the Scroll object with your Search object !
`$scroll = new \Elastica\Scroll($search);`

Scroll you results :-) !

```
foreach ($scroll as $scrollId => $resultSet) {
//Do the job
//Transform your Elastica results to your model if needed.
 }
```

Also you may want a transformer for your results because this way will give you only raw Elastica results.
For the transformer, check this subject : 
https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1298

I also faced a memory problem while transforming a large set of results.
I'm using Doctrine, so on each loop i called the clear() method of the Transformer 's Doctrine EntityManager which i added to my custom transformer.

Hope this helps !

**Comment by minhtranite** [comment]
@vulfhelm, Thank you so much! I will try it later.

**Comment by ksom** [comment]
@vulfhelm 
Hi thanks for your solution! How do you handle the pagination with this solution?
My problem is when I go to page 400 of my pagination through pagerfanta, it say that the max_result_window is 10000 and result is 30000

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1546
