### ISSUE TITLE
[Symfony2] FOSElasticaBundle: how to Paginate Aggregations?

### ISSUE THREAD

**Issue by persiasama** [FriendsOfSymfony/FOSElasticaBundle#1299]
Hello, 
this is my function (Aggregation): I want to paginate the results 10 by 10. 
I want to know if it's possible. 
if not there is an other way to have the same result?

public function travelersFiltredByCity($cityname)
    {
        $query = new \Elastica\Query(new \Elastica\Query\MatchAll());
        $tagsAggregation = new \Elastica\Aggregation\Terms('topTravelers');
        $tagsAggregation->setField('profileIndex')->setSize(10);
        $tagsAggregation->setOrder('sum', "desc");
        $sumAggregation = new \Elastica\Aggregation\Sum('sum');
        $sumAggregation->setField('tigrc');
        $tagsAggregation->addAggregation($sumAggregation);
        $filterAggregation = new \Elastica\Aggregation\Filter('city');
        $filterAggregation->setFilter(new \Elastica\Filter\Terms('slug', array($cityname)));
        $filterAggregation->addAggregation($tagsAggregation);
        $query->addAggregation($filterAggregation);
        return $query;
    }

Thanks you

**Comment by ThomasLabstep** [comment]
`
        if ($this->firstResult) {
            $query->setFrom($this->firstResult);
        }
        if ($this->maxResults) {
            $query->setSize($this->firstResult + $this->maxResults);
        }

        return $query;`

**Comment by XWB** [comment]
See comment above.
