### ISSUE TITLE
The profiler template "FOSElasticaBundle:Collector:elastica.html.twig" for data collector "elastica" does not exist.

### ISSUE THREAD

**Issue by wenmingtang** [FriendsOfSymfony/FOSElasticaBundle#1301]
<img width="649" alt="qq20171116-231437 2x" src="https://user-images.githubusercontent.com/1620172/32898828-e3211466-caae-11e7-84d1-7aca2b64b839.png">

**Comment by DavidFeller** [comment]
I can confirm this in Symfony 3.4-rc1 with flex. The template file exists in the expected folder inside the vendor directory, but the bundle doesn't find it. I also tried to copy it to /templates(/<bundles>/<bundle-name>), but couldn't solve it, yet.

**Comment by XWB** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1295
