### ISSUE TITLE
adding Makasim as maintainer

### ISSUE THREAD

**Issue by lsmith77** [FriendsOfSymfony/FOSElasticaBundle#1303]
@makasim has several open PRs and he is quite dedicated to the Bundle as shown by his open PRs:
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pulls?utf8=✓&q=author%3Amakasim%20

**Comment by makasim** [comment]
I was a maintainer of LiipImagineBundle for a year as well as created and supported few own bundles: [PayumBundle](https://github.com/Payum/PayumBundle), [EnqueueBundle](https://github.com/php-enqueue/enqueue-dev).

I have great things for this bundle: refactoring, cleanups, new features, tests and so on.

**Comment by XWB** [comment]
@makasim I have sent you an invite.

@lsmith77 Thank you for the suggestion :)

**Comment by cystbear** [comment]
Yeah 👍  about @makasim as a maintainer. 

I know him in real life, quite good dev, mostly famous as a [Payum](https://github.com/Payum/Payum) creator.

**Comment by lsmith77** [comment]
done
