### ISSUE TITLE
Why bundle is dependent of Symfony Form Component?

### ISSUE THREAD

**Issue by okorneliuk** [FriendsOfSymfony/FOSElasticaBundle#1310]
Maybe it is dumb question, but can you explain me please?

**Comment by bgaleotti** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/113

It might be dropped, as `symfony/property-access` is [required](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/57db7660bf1ded4d2c248c68fa2099eef6e9d30b/composer.json#L19).

**Comment by okorneliuk** [comment]
Thanks!
