### ISSUE TITLE
[Transformer] Add index / type info to TransformEvent

### ISSUE THREAD

**Issue by dkarlovi** [FriendsOfSymfony/FOSElasticaBundle#1312]
If you have the same entity bound to couple different indices, it makes sense for the transformation to be index-specific (for example, having `index_en` and `index_de`, loading proper locale in the transform event).

Would go a long way to allow multi-language indices integrated with Doctrine+Gedmo which is tracked in #227.

**Comment by damijank** [comment]
Hi all!
Is there any activity to be expected in this thread? `index_name` could do just fine if it were present in the `TransformEvent`'s attributes...

**Comment by userz58** [comment]
Please, add property Index to 
FOS\ElasticaBundle\Event\PreTransformEvent
FOS\ElasticaBundle\Event\PostTransformEvent

I can't catch the transformer for the desired index.
