### ISSUE TITLE
Release with Elastica 5.x support

### ISSUE THREAD

**Issue by VasekPurchart** [FriendsOfSymfony/FOSElasticaBundle#1317]
Hello, could you please tag a release with Elastica 5.x support? I see that master has already dependency on `^5.2.1`, but for obvious reasons I do not want to set dependency on that.

**Comment by makasim** [comment]
Unfortunately, we cannot do it atm. There are some changes to be done in it. 
TLDR: current providers will be replaced with a better solution. more here #1240

**Comment by VasekPurchart** [comment]
Oh, ok, thanks for the pointers and fast response, will follow the mentioned PR 👍

**Comment by dkarlovi** [comment]
@makasim I see your PR is merged, guessing that + tagging with Symfony 4 support (#1302) and Elastica v5 would be a good release (new Elasticsearch v6 is not compatible by default with this bundle currently, Elastica v5 fixed a blocker bug).

Do you have any milestone in mind or is it more like "when it's ready"?

**Comment by makasim** [comment]
I'd say in January I could release v5. Sounds good?

**Comment by makasim** [comment]
There will be other PRs. I have just started (:

**Comment by dkarlovi** [comment]
Might make sense to backport this bugfix to Elastica v3 then as people might become locked in to FOS Elastica v4 if the planned features make v4 and v5 substantially incompatible? Don't know if they would release a backport.

**Comment by makasim** [comment]
The feature I am working is merged to v4 version but disabled by default, the v4 provider API is marked as deprecated. So I expect smooth migration as long as one doesn't extend provider classes.

**Comment by dkarlovi** [comment]
Sounds good, looking forward to seeing it. :+1:

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/releases
