### ISSUE TITLE
No search type for [count]

### ISSUE THREAD

**Issue by MaximeMaillet** [FriendsOfSymfony/FOSElasticaBundle#1322]
Hi, I have problem on **ES 5.0** with that.

```php
TransformedFinder $finder = [...];
$return = $finder->createPaginatorAdapter(
    $this->getQuery() // My query whatever
);

return $return->getTotalHits();
```

Because `getTotalHits()` send GET request like this `/{index}/{node}/_search?search_type=count`

`search_type=count`deprecated in ES 2.0 and removed in 5.0
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-search-type.html

Instead of `/{index}/{node}/_count` for get total hits.

This is a trick, waiting ruflin update.

_FOS\ElasticaBundle\Paginator\RawPaginatorAdapter_
```php
public function getTotalHits($genuineTotal = false)
{
        if (! isset($this->totalHits)) {
            $this->getResults(0,1);
            //$this->totalHits = $this->searchable->count($this->query);
        }

        return $this->query->hasParam('size') && !$genuineTotal
            ? min($this->totalHits, (integer) $this->query->getParam('size'))
            : $this->totalHits;
}
```

Or, in personal code

```php
TransformedFinder $finder = [...];
$return = $finder->createPaginatorAdapter(
    $this->getQuery() // My query whatever
);
$return->getResult(0,1);
return $return->getTotalHits();
```

This is not a good solution, just a trick who can damage performence.

Edit: fix with [ruflin](https://github.com/ruflin/Elastica) 5.0.0

**Comment by braimond-carelabs** [comment]
Same problem ...

How to use Ruflin 5.0 with FOSElastica ?

**Comment by Tobion** [comment]
As you found out, you need to use the upcoming 5.0 version with elasticsearch 5. See #1356 for documenting these dependencies.
