### ISSUE TITLE
PagerProvider error

### ISSUE THREAD

**Issue by mpiot** [FriendsOfSymfony/FOSElasticaBundle#1334]
Since today (I think commit 72ea32f), I've this error when I try to populate:

> In InPlacePagerPersister.php line 42:                           
  Notice: Undefined index: indexName 

I read the PR#1240, and try to define parameters like say in:

    parameters:
        fos_elastica.use_v5_api: true

But I've the same error, then I add in my Types:

    persistence:
        driver:                         orm
        model:                        AppBundle\Entity\User
        provider:
            pager_provider:     true

And I've the following error:
> In ArrayNode.php line 319:                                                                                  
  Unrecognized option "pager_provider" under "fos_elastica.indexes.app.types.user.persistence.provider"

**Comment by makasim** [comment]
Are you on v4 or v5 (current master) version? 
Do you have any customizations at app side related to fos elastica?

**Comment by mpiot** [comment]
I use dev-master and Elasticsearch 5.6.3
No customizations, just an elasticsearch.yml file, and a SearchRepository folder to perform requests.

(For the moment, I've downgrade to Elasticsearch 2.4.6 and FOSElastica 4.0.1, to avoid errors. But I can undo it, if need more informations.)

**Comment by makasim** [comment]
> I use dev-master and Elasticsearch 5.6.3

Since you are on master you don't have to set either `pager_provider` nor `fos_elastica.use_v5_api` parameter.

**Comment by mpiot** [comment]
Yes, but  I've the error, that's why I've try with parameters:

> In InPlacePagerPersister.php line 42:
Notice: Undefined index: indexName

**Comment by makasim** [comment]
Could you post a stack trace? If you run populate command just add `-vvv`.

**Comment by makasim** [comment]
try the latest master. It should fix your problem https://github.com/FriendsOfSymfony/FOSElasticaBundle/commit/4aa07898358916056192d1a64806ec7e0282d010

**Comment by mpiot** [comment]
It works :-)
Just the console output is less nice than before, but it works.

    root@210744c4b8ed:/var/www/html# bin/console fos:elastica:populate
    Resetting app
    3/3 [============================] 100%
    5/5 [============================] 100%
    2/2 [============================] 100%
    102/102 [============================] 100%
    5247/5247 [============================] 100%
   Populating app/locusRefreshing app
   Refreshing app

With lines that normally don't exist (just 3 in my case: 3/3, 2/2, 5247/5247)

**Comment by makasim** [comment]
@mpiot cannot repo the problem

```
root@c6019541c555:/mqs/symfony# php bin/console fos:elastica:populate --batch-size=101
Resetting enqueue
 2000/2000 [============================] 100%
Populating enqueue/blogRefreshing enqueue
Refreshing enqueue
```

let me know if you find something
