### ISSUE TITLE
add _source option

### ISSUE THREAD

**Issue by felipedasilva** [FriendsOfSymfony/FOSElasticaBundle#1341]
Can i choose the fields?

MyController
$this->get('fos_elastica.index.type.doc')->search($query, [
  "_source" => "title"
]);

Elastica\Search
...
protected function _validateOption($key)
... add case '_source'

**Comment by jfcorsini** [comment]
I don't know if I understood well your question. But if you are asking if you can change the fields to source, then yes you can.

If your `$query` variable is an instance of Elastica\Query, you can actually use the method `setSource` and pass the arguments to me sourced. You can pass the parameters as an array or just pass the argument, i.e:

```
$query = new Elastica\Query();
$query->setQuery($boolQuery);
$query->setSource('name');
```

where `$boolQuery` is the query that you had before.

**Comment by felipedasilva** [comment]
thank you!!!
