### ISSUE TITLE
How create parent mapping on Elasticsearch 6?

### ISSUE THREAD

**Issue by Paulkrut** [FriendsOfSymfony/FOSElasticaBundle#1388]
Elasticsearch 6 doesn't support parent mapping anymore. Do I have to use "type:join" now? How can I map entity parent in FOS_elasticBundle with Elasticsearch 6?

**Comment by stof** [comment]
When using ES 6, you should not use the `parent` feature in the bundle anymore, as this is about configuring the mapping using the ES feature which got removed in version 6.

AFAIK, the bundle does not yet support the new `join` type.

**Comment by Paulkrut** [comment]
Thank you!

**Comment by mazahell** [comment]
Any news?
