### ISSUE TITLE
 There are no commands defined in the "fos:elastica" namespace.

### ISSUE THREAD

**Issue by methodeprog** [FriendsOfSymfony/FOSElasticaBundle#1408]
Dear Sir 
I use Symfony 4.0.6 (kernel: src, env: dev, debug: true) with "friendsofsymfony/elastica-bundle": "^5.0"
also elasticsearch-6.2.1.
It worked well when i decided to reinstalle after some update, and it commands dont appear anymore.

Ive make a reinstall of the bundle many times, clean the cache, but no way...
I need your help.

**Comment by Tobion** [comment]
please provide repository that reproduces the problem. otherwise there is no way to help here without any info.

**Comment by methodeprog** [comment]
Hi Tobion i ve clean the cache with Ccleaner and make a reinstall...it work well...
Many thanks
