### ISSUE TITLE
how to integrate the FOSElasticaBundle in my Symfony 3 project

### ISSUE THREAD

**Issue by Thunderkilll** [FriendsOfSymfony/FOSElasticaBundle#1414]
**this is my first time using this bundle and i didn't understand the documentation well **
_i want to do a dynamic search with autocomplete and my teacher advised me with this bundle . I didn't know were do i configure the definition of my **index types** & **how to use the Bundle ** _

please I really need an answer before wednesday next week so i can integrate with my templates

**Comment by XWB** [comment]
Please read the documentation.
