### ISSUE TITLE
Properties config: combining 2 attributes from the entity to make one single property

### ISSUE THREAD

**Issue by fabienchn** [FriendsOfSymfony/FOSElasticaBundle#1415]
In my project, I have an User entity having a firstname and a lastname.
I'd like to be able to search the users by typing their firstname and lastname together and therefore would need in my Elastica config to have a property that's concatenating firstname and lastname.

Imagine i have a user called Jane Doe, I could find him by typing "Jane Doe" in the search.

I didn't find anything in the doc explaining how to config that kind of property though

**Comment by secretwz** [comment]
use copy_to parameter: https://www.elastic.co/guide/en/elasticsearch/reference/current/copy-to.html

And add "fielddata: true" to the full_name field if you use serialization.

**Comment by XWB** [comment]
Thanks @secretwz
