### ISSUE TITLE
  Unrecognized options "index_analyzer, search_analyzer, mappings"

### ISSUE THREAD

**Issue by thuiban** [FriendsOfSymfony/FOSElasticaBundle#1422]
Hey guys ! 

I have problem when i would like populate, i have this error : 
` Unrecognized options "index_analyzer, search_analyzer, mappings" under "fos_elastica.indexes.sample.types.technical_assistance"`

What it's wrong ?

I'm on Symfony 3.4 and FOSElasticaBundle 5.0.3

**Comment by thuiban** [comment]
Indentation error !

**Comment by jorenvh1** [comment]
hey @thuiban, can you explain what the problem was? I have the same issue after upgrading to symfony 3.4
