### ISSUE TITLE
Fos:elastica:populate : Content-Type header [application/x-www-form-urlencoded] is not supported  

### ISSUE THREAD

**Issue by TheKassaK** [FriendsOfSymfony/FOSElasticaBundle#1423]
Hello, I have this error on a Symfony 3.4 and Elastic 6 :

```
curl -XGET 'http://localhost:9200'
{
  "name" : "Ajg6C_2",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "mPz5ROQmSIOUUzUdi4p2mw",
  "version" : {
    "number" : "6.2.4",
    "build_hash" : "ccec39f",
    "build_date" : "2018-04-12T20:37:28.497551Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

In Http.php line 172:
                                                                            
  [Elastica\Exception\ResponseException]                                    
  Content-Type header [application/x-www-form-urlencoded] is not supported  
                                                                            

Any ideas ??? Thanks !

**Comment by ibasaw** [comment]
same thing...

hint maybe: https://stackoverflow.com/questions/47544966/elasticsearch-content-type-header-application-x-www-form-urlencoded-is-not-s

**Comment by ibasaw** [comment]
just update your version of the bundle to the 5.0.3 and it works !

**Comment by XWB** [comment]
:+1:
