### ISSUE TITLE
Error EnqueueElasticaExtension

### ISSUE THREAD

**Issue by MarcelMC** [FriendsOfSymfony/FOSElasticaBundle#1424]
When command php bin/console fos:elastica:populate
In EnqueueElasticaExtension.php line 26:
Notice: Undefined index: doctrine

**Comment by jmwill86** [comment]
I agree the docs around the enqueue extension an populate comment aren't great. I can't for the life of me work out how to get it working. I have no idea what to pass in as an argument to --pager-persiter. 'The "--pager-persiter" option does not exist.' is all I get. I presume there's a service that needs to be set up of some sort.

Adding the below in your config will get rid of the error, but nowhere can I see this mentioned on the setup here or in enqueue-elastica-bundle. With the below I still can't get it to work so it may be incorrect.

```
enqueue_elastica:
    doctrine: ~
```

**Comment by XWB** [comment]
:+1:
