### ISSUE TITLE
How to catch exception 

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSElasticaBundle#1430]
Hello,

How to catch exception thrown in FOS Elastica when Elastic Search is down?

I have the error : "Couldn't connect to host, Elasticsearch down?" generate by rufflin/elastica in \ruflin\elastica\lib\Elastica\Transport\Http.php line 189.

My application throw a 500 error. I want to catch the error in logs without displaying a 500 error for the user when Elastic Search is down.

How can I do it?

**Comment by yveson33** [comment]
same issue here?

**Comment by yveson33** [comment]
I think we can simply redefine service like here: https://symfony.com/doc/current/service_container/service_decoration.html
