### ISSUE TITLE
mapping would have more than 1 type

### ISSUE THREAD

**Issue by omarsoufiane** [FriendsOfSymfony/FOSElasticaBundle#1436]
i have an error in production when running the populate command.
`Rejecting mapping update to [app] as the final mapping would have more than 1 type: [item, profile].`
the error happens on the production server but not on my computer

**Comment by RonRademaker** [comment]
This is due to a breaking change in ES 6. I'm wondering if there are options to work around this available in this bundle yet. Obviously using an index for each type would work, but I also have two types I'd like to see in one index together, are there configuration options for that solution?

**Comment by Destroy666x** [comment]
@RonRademaker the only solution would be going back to ES 5. I don't think this bundle can do anything to avoid that limitation.

**Comment by XWB** [comment]
^^
