### ISSUE TITLE
fos:elastica:reset command resets the entire index, not only the given type

### ISSUE THREAD

**Issue by mohdsamir** [FriendsOfSymfony/FOSElasticaBundle#1443]
I have an index with multiple types. When i run the following command 

`fos:el:reset --index=[MY_INDEX] --type=[MY_TYPE]`

It resets the entire index, not only the given type.

**Comment by jason-linthwaite** [comment]
Also the same situation with populating an individual type - it resets the whole index.

**Comment by sakalys** [comment]
3 years no change :o

**Comment by sakalys** [comment]
Actually, this is probably due to the fact that it is no longer possible to delete a type (or at least a type mapping).

Ref: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/indices-delete-mapping.html
