### ISSUE TITLE
New index every time I run fos:elastica:populate

### ISSUE THREAD

**Issue by jorenvh1** [FriendsOfSymfony/FOSElasticaBundle#1448]
Is it expected bahaviour that every time I run the populate command a new index gets created?

This causes my elasticsearch cluster to be bloated with unneeded indexes and old data...

I'm not using the --no-delete option btw

**Comment by jandom** [comment]
That is indeed the behavior right now. I know – i was a bit puzzled myself. 

There are two way around this 
- use the `--no-reset` flag, see `fos:elastica:populate -h` for explanation and other cool flags
- use an aliased index, which keeps two indicies called app_xxxx and app_yyy and uses an alias app to point to one of them, while the other is repopulated https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/cookbook/aliased-indexes.md
