### ISSUE TITLE
How to do the mapping for a ManyToMany Relation

### ISSUE THREAD

**Issue by jvalll3** [FriendsOfSymfony/FOSElasticaBundle#1450]
I'm trying to use FOSElasticaBundle on my symfony 4 project and I have some problems.

I have an entity, "Users", with the next annotation in the property "segments":

```
* @var Collection $segments
 * @ORM\ManyToMany(targetEntity="App\Entity\Segment", mappedBy="users", cascade={"persist", "remove"})
```

Which is the correct form to do the mapping in the fos_elastica.yaml file?

**Comment by juanpiterson** [comment]
Same problem for me, any one?

**Comment by DavidGarciaCat** [comment]
Just in case its useful, the error I get is

```
Warning: Undefined property: Doctrine\Common\Collections\ArrayCollection::$id
```

**Comment by DavidGarciaCat** [comment]
Closed 5 hours ago but no comments to explain how to solve this problem? :-)
