### ISSUE TITLE
Exception when property of entity relation contain null

### ISSUE THREAD

**Issue by priyankoctal** [FriendsOfSymfony/FOSElasticaBundle#1461]
I have a item entity, stock entity and color entity

Item has oneToMany stocks and stock have ManytoOne association with color

now I am mapping item entity and stocks with elastic search. I am mapping stocks as nested of item

but it gives an error when color_id is null in stock table, how I can solve this exception

 item:
                    mappings:
                        id: { type: integer }
                        title: { index: analyzed, analyzer: autocomplete, search_analyzer: autocomplete }
                        description: { index: analyzed, analyzer: simple }
                        stock:
                            type: nested
                            include_in_root: true
                            properties:
                                id: { type: integer }
                                color: { type: object}
                                
Type error: Return value of AppBundle\Entity\Stock::getColor() must be an instance of AppBundle\Entity\Color, null returned

I am stuck from couple of days, if anyone have idea please share

**Comment by Sharsie** [comment]
@priyankoctal Maybe a bit late to the party, but I reckon this was due to incorrect typings of the return type of `getColor` method
as in `... getColor(): Color` instead of `... getColor(): ?Color`
