### ISSUE TITLE
Symfony4.2: Try using dependency injection instead

### ISSUE THREAD

**Issue by wenmingtang** [FriendsOfSymfony/FOSElasticaBundle#1467]
I using Symfony4.2-beta1 version:

The following error occurred:

<img width="1029" alt="screen shot 2018-11-07 at 2 58 32 pm" src="https://user-images.githubusercontent.com/1620172/48115339-8beb5a00-e29d-11e8-865a-94c4030ac601.png">

```
An exception has been thrown during the rendering of a template ("Service "fos_elastica.finder.article.article" not found: even though it exists in the app's container, the container inside "App\Controller\ArticleController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "session" and "twig" services.Try using dependency injection instead.").
```

**Comment by methodeprog** [comment]
There is a issue with this as when try to use the base controller, with Symfony 4.2.x..
// Class controller is deprecated //

**Comment by wenmingtang** [comment]
> extending
In Sf4.2, The `Symfony\Bundle\FrameworkBundle\Controller\Controller` is deprecated.

**Comment by methodeprog** [comment]
Yes really !
that is deprecated since Symfony 4.2, use {@see AbstractController}

**Comment by XWB** [comment]
@wenmingtang @XWB Thanks :)

In that case you will have to inject `fos_elastica.manager` intro your controller.

**Comment by methodeprog** [comment]
@XWB a little code could help me ! Thank for all !
Here is inside my controller 

    /**
     * @Route("/search", name="search_contact")
     */
    public function searchContactAction(Request $request): Response
    {
        // create Contact model
          $ContactSearch = new ContactSearch();
          // create form
          $ContactSearchForm = $this->createForm(ContactSearchType::class, $ContactSearch );
            // bind data
          $ContactSearchForm->handleRequest($request);
          $ContactSearch = $ContactSearchForm->getData();
          $elasticaManager = $this->get('fos_elastica.manager');
          $results = $elasticaManager->getRepository(Contact::class)->searchFull( $ContactSearch);

**Comment by methodeprog** [comment]
@XWB  Greaaaaat thank ! i can't find word ! A great help !

**Comment by god1dog** [comment]
https://github.com/symfony/framework-bundle/blob/v4.2.1/Controller/ControllerResolver.php#L64
time to move on [autowiring](https://symfony.com/doc/current/service_container/autowiring.html)

**Comment by methodeprog** [comment]
Hi @XWB  i got something weird i don't know what miss in the last step:

 Could not fint the ->searchFull method in Repository(Contact::class) and Repository(Contact::class) is not related to the repository define in the fos_elastica.yaml but to \FOS\ElasticaBundle\Repository...
So phpstorm mention that ->searchFull method is not found in \FOS\ElasticaBundle\Repository
And i need the searchFull method query ...define in the Repository(Contact::class)
:)

Thanks

**Comment by primus852** [comment]
> 
> 
> Hi @XWB i got something weird i don't know what miss in the last step:
> 
> Could not fint the ->searchFull method in Repository(Contact::class) and Repository(Contact::class) is not related to the repository define in the fos_elastica.yaml but to \FOS\ElasticaBundle\Repository...
> So phpstorm mention that ->searchFull method is not found in \FOS\ElasticaBundle\Repository
> And i need the searchFull method query ...define in the Repository(Contact::class)
> :)
> 
> Thanks

There are `find`, `findHybrid`, findPaginated` methods to call, e.g. `$manager->getRepository(Contact::class)->findHybrid($ContactSearch);`
