### ISSUE TITLE
Missing documents in populate command

### ISSUE THREAD

**Issue by adrianet86** [FriendsOfSymfony/FOSElasticaBundle#1478]
Hi

I am facing problems since I update to ElasticSearch 6.3 (AWS) with foselastica 5.3.

When I run populate command it is supposed to be inserted 1371 documents, but when I get all total hits of this index I have only 1047.

However, if I update the entity related (Doctrine and PostgreSQL), it is inserted in ElasticSearch.

Any idea? 

Thanks

**Comment by jvasseur** [comment]
This looks like the same issue as https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1393

**Comment by XWB** [comment]
Duplicate ^^
