### ISSUE TITLE
Populate index without persistence

### ISSUE THREAD

**Issue by versh23** [FriendsOfSymfony/FOSElasticaBundle#1507]
i want to populate index without any persistence driver. 

for example, i have data in json. i parse it and populate index type.
after that i want to do search 

how can i do it ?

i don't want to use Elastica lib directly, because this bundle have a beautiful configuration, mapping and transformer

i think it will be useful to add in docs. if its possible - i do PR later

**Comment by versh23** [comment]
another question 
there we must define a driver options in persistence https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/src/DependencyInjection/Configuration.php#L293

but here 
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/src/DependencyInjection/FOSElasticaExtension.php#L434
checks is driver options defined


what does it mean ? a cant create fully custom persistence without driver options ? is it bug or feature ?

**Comment by Renrhaf** [comment]
@versh23 could you please elaborate on how to deal with such a requirement ? Thanks !
