### ISSUE TITLE
Elasticsearch 7.x support

### ISSUE THREAD

**Issue by oachoor** [FriendsOfSymfony/FOSElasticaBundle#1514]
With the removal of mapping types, indices created in Elasticsearch 7.0 or later no longer accept a _default_ mapping. is there a work in progress regarding the Configuration?

**Comment by Nek-** [comment]
@oachoor isn't this an issue related to your version of elastica?

see https://github.com/ruflin/Elastica

**Comment by oachoor** [comment]
@Nek- thanks! I don't think that would be enough to resolve the issue, I could require version 7.x although **FOSElastica** requires version 6.x [here](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/composer.json#L22).
Also _types_ key is still defined in the [Configuration](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/src/DependencyInjection/Configuration.php#L111)

**Comment by Nek-** [comment]
@oachoor Elastica is not released as 7.x version ATM. See https://github.com/ruflin/Elastica/releases

You should consider open an issue on the other project. ;-)

**Comment by oachoor** [comment]
You're right! there's an open issue already https://github.com/ruflin/Elastica/issues/1626

**Comment by XWB** [comment]
@Nek- Still, at some point the [index types](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/src/DependencyInjection/Configuration.php#L111) will have to be removed in FOSElasticaBundle.

**Comment by oachoor** [comment]
@XWB correct, thanks. I wanted just to know if there's a work in progress regarding the Configuration, apparently not.
