### ISSUE TITLE
Decrease number of shards

### ISSUE THREAD

**Issue by graferowy** [FriendsOfSymfony/FOSElasticaBundle#1536]
Hi!
When populating my index, 5 shards are being created. Even if my index was already created and initialized with only 1 shard. That's quite an overkill for me, since I don't have that much data currently. Is there a way to decrease the number of shards being created when populating? 1 shard with 1 replica is all I need at the moment.

**Comment by graferowy** [comment]
I've changed settings of my default template and it helped.

`PUT _template/all
{
  "template": "*",
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1
  }
}`

Wondering if there is any other way?

**Comment by XWB** [comment]
This is rather related to your ES setup.
