### ISSUE TITLE
Support for ElasticSearch 7.2

### ISSUE THREAD

**Issue by tacman** [FriendsOfSymfony/FOSElasticaBundle#1541]
When I configure the bundle to use a 7.2 server, it appears to index the documents (no failures), but doesn't search them (but again, no errors).

Does this bundle support 7.2 at all?  I'm guessing it doesn't, since the documentation only mentions version 6, but it'd be helpful to document if version 7 is supported (or maybe fail when it detects it?)

Thank you.

**Comment by sharipovmarat** [comment]
Same issue

**Comment by horlyk** [comment]
I was getting errors while using 7.3. After I'd switched to 6.8 all worked fine. Waiting for 7+ support :)

**Comment by jourdan-qe** [comment]
Hi,

Are there any plans to support 7+?
I won't downgrade my cluster and of course, I'd like to use this bundle

Thx

**Comment by racastellanosm** [comment]
This is a must! 

ES7 works better with other components like Api-Platform! Meamwhile ES6 is more dificult to integrate beacuse the ES7 new struture and recomendations to drop support for index types and will only allow single type per index

Is there any proposal to add support for ES7?

Thx!

**Comment by aequasi** [comment]
Getting a bunch of these trying to use 7.x

`Root mapping definition has unsupported parameters`
