### ISSUE TITLE
Automatic mapping creation based on Serializer groups doesn't seem to work

### ISSUE THREAD

**Issue by timfennis** [FriendsOfSymfony/FOSElasticaBundle#1560]
I'm trying to automatically create mappings based on serializer annotations as documented here:

https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/serializer.md

When I run `bin/console fos:elastica:create` the index is created as expected but when i run

```
curl -XGET http://localhost:9201/foobar/_mapping\?pretty\=true
```

I get the following response

```
{
  "foobar" : {
    "mappings" : {
      "newsitem" : {
        "_meta" : {
          "model" : "AppBundle\\Entity\\NewsItem"
        },
        "dynamic_date_formats" : [ ]
      }
    }
  }
}
```

while I expect mappings for the properties `title` and `created`.

I created a small project that demonstrates this behaviour here: https://github.com/timfennis/reproduce-fos-elastica-mapping

Is this a misunderstanding on our part? Is my project not configured correctly? Is there some kind of version incompatibility that's causing this issue?

**Comment by kuzinmv** [comment]
I'v got exactly  the same issue

**Comment by kezek** [comment]
Same issue here.

**Comment by benstinton** [comment]
Same issue here, would be great to hear if anyone found a solution
