### ISSUE TITLE
Bundle is not compatible with ruflin/elastica 7.0.0-beta1

### ISSUE THREAD

**Issue by deguif** [FriendsOfSymfony/FOSElasticaBundle#1568]
As there were some breaking introduced in ruflin/elastica 7.x branch with the `Elastica\Type` removal, I think support for version `7.x` of ruflin/elastica in composer.json should be removed.

By the way, I would be very happy to help making this bundle compatible with `ruflin/elastica` 7.x version. But it would probably require to create a new branch, as there are quite a lot of changes to do.

**Comment by deguif** [comment]
See https://github.com/ruflin/Elastica/pull/1666 for reference

**Comment by thomaspicquet** [comment]
I'm not sure if there are any plans on supporting the new version `ruflin/elastica`. This bundle doesn't seem updated anymore

**Comment by XWB** [comment]
@deguif You are right. I created a 5.1.x branch and removed `ruflin/elastica` 7 from the composer file. In addition, master has been bumped, allowing us to introduce BC breaks. Feel free to open a PR with proper `ruflin/elastica` 7 support :)

@thomaspicquet Pull requests are still welcome. If you want new functionality, feel free to open a PR :)

**Comment by OskarStark** [comment]
So we can handle #1566 with a BC break, too?

**Comment by deguif** [comment]
@OskarStark that would mean dropping support for Symfony 3.4 in master and support only Symfony 4.3+, if I understand correctly?

**Comment by deguif** [comment]
@XWB Shouldn't we bump the new version of the bundle to `7.0` instead of `6.0`, to better reflect we support `ruflin/elastica` 7.x in this major version?

**Comment by OskarStark** [comment]
> @OskarStark that would mean dropping support for Symfony 3.4 in master and support only Symfony 4.3+, if I understand correctly?

Yes 👍

**Comment by deguif** [comment]
I would love to get rid of Symfony 3.4, but as Symfony 3.4 is a LTS and its end of support is only for end of next year, it maybe not judicious?

**Comment by deguif** [comment]
I started to work on this topic, but will probably take a long time

**Comment by XWB** [comment]
ElasticSearch 7 support has been added to the master branch.
