### ISSUE TITLE
populate takes a lot of time and cpu usage on a single core

### ISSUE THREAD

**Issue by locojuhi** [FriendsOfSymfony/FOSElasticaBundle#1582]
Thanks in advanced for have taken time to read the issue.

# Stack
| Tool | Version |
|------|:-------------:|
|Symfony|4.0| 
|ElasticSearch|6.3.1|
|Elastica bundle|^5.0|

We have just released our application to production environment and when I ran populate to the new instance of elastic search on AWS it takes a lot of time and cpu usage to index the data.

Not only the populate takes a lot of time. The refresh method also takes it's time

This is production environment, I'm not able to change the env and do some profiling for that reason.

![Cpu usage - populate](https://user-images.githubusercontent.com/7256501/70006422-0e932700-153b-11ea-953a-346181ee2caf.png)

**Comment by anmolnagpal** [comment]
👍

**Comment by mxkh** [comment]
@locojuhi Try to run with --no-debug flag

**Comment by locojuhi** [comment]
As this is a really old question/issue that were not that did not have any follow up Going to close this issue.

Thanks for your kindly replies.
