### ISSUE TITLE
Support queued messages via Symfony Messenger?

### ISSUE THREAD

**Issue by tacman** [FriendsOfSymfony/FOSElasticaBundle#1586]
Now that Symfony Messenger is a first-class component, what do folks think of building in the functionality of EnqueueBundle in this bundle?

It _might_ be something like replacing the ->dispatch calls that are currently events on a configurable message bus.  That would allow us to replace the idea of deferring the indexing altogether, since the user would simply configure how they wanted the dispatched messages handled.

**Comment by XWB** [comment]
That sounds like a good idea, as long as the usage of Symfony Messenger remains optional.

I have no experience with Symfony Messenger though, is this something you could accomplish?

**Comment by tacman** [comment]
Check out this chapter and the next one:

https://symfonycasts.com/screencast/messenger/events#play

Would you consider making the Messenger component a requirement (and thus dropping support for Symfony 3.4 in this branch)?  Basically all the dispatch events would be sent on a configurable message bus. 

If so, then I think I could take a swing at replace the event handles with message handlers, and dispatching messages instead of events.  I admit, though, that I am no expert at this.

**Comment by mwansinck** [comment]
@tacman @XWB 

Any update on this, we like the idea, and Symfony Messenger seems to be a logic choice because it's Symfony's native message queue implementation. Also if needed I could assist.

However to be backwards compatible I would suggest to keep the Enqueue logic and add the Messenger logic through some configuration parameters so it's up to the user which queue system is being used.

**Comment by tacman** [comment]
I think the requirement to be backwards compatible to Symfony 3.4 is pretty onerous.  Messenger was designed for exactly this situation, because in addition to being asynchronous, it handle failures and retries.  

I _think_ the approach to integrate Messenger would be to wrap all the current event dispatcher calls in a message, and dispatch the message on a bus.  

Perhaps we could implement a bus for 3.4 that simply makes the calls directly to the event dispatcher, implementing the interface, then using that proxy class if the Symfony Messenger isn't installed.  So maybe it's not too onerous.

I'm a huge fan of the Messenger component.  Here's an excellent tutorial:

https://symfonycasts.com/screencast/messenger

But you don't need to go through the whole tutorial, it only takes a few minutes to set it up and start using it.  Plus, you don't even need to set up RabbitMQ, since you can also put messages in Doctrine (and Symfony 5.1 reduces latency even more with PostgreSQL: https://github.com/symfony/symfony/pull/35485)

If compatibility with ElasticSearch 7 is going to require a version bump for FOSElasticaBundle, can we drop support for anything less than 4.4, and require Symfony Messenger?

**Comment by Growiel** [comment]
The last commit on this is now a month old, any plans on merging it ?

I'm on a new SF 5 project and already using Messenger in other parts of my app and would hate to have maintain a second queuing bundle (enqueue) or to have to write my own logic to handle it with Messenger when that's the sole reason I'm using FOSElastica.
