### ISSUE TITLE
how to improve the populate command?

### ISSUE THREAD

**Issue by leobeal** [FriendsOfSymfony/FOSElasticaBundle#1595]
Hi!
I am aware this is a known issue and we even have a doc on how to speed it up.

I created a custom command that uses the `Elastica Bulk API` and I am able to insert 70k objects in ~2min. ~50M memory. 
Using the `populate` command with the exact same code takes ~30min and ~1.5G memory

Some facts: 

- Having the logger enabled increases memory consumption on my custom command, but it does not increase time. (Also a known issue)
- The `populate` command also uses the same `Bulk API` I use on my custom command.

My question is: Is there any way we can improve this? Do we know where the memory leak is, or why the performance is so much worse in comparison with a custom command?

Thanks a lot for the package and the hard work on the 7.x release 👍

**Comment by mmenozzi** [comment]
Why this has been closed?

**Comment by leobeal** [comment]
@mmenozzi it turns out the performance issues we were having did not happen on production (only on dev). 
If the issues you are having are also only on dev you can try to add `--no-debug` to the populate command.
