### ISSUE TITLE
Usage without persisted entities

### ISSUE THREAD

**Issue by marlip** [FriendsOfSymfony/FOSElasticaBundle#1601]
Hello,
i'm new to FOSElasticaBundle but know elasticsearch for a while now.

I wanted to integrate elasticsearch in one of our projects but **without any database**.

We have a symfony 4 app, only a command with a data pipeline to process and enhance data, at the last stage we want to push the processed objects to an elasticsearch cluster to index them and make them searchable.

They are not persisted in any database at any time.

Is this with FOSElasticaBundle possible? Because I tried hard without any progress and can't find any examples / tutorials that cover this situation.

**Comment by COil** [comment]
In my tutorial, I have done a custom provider to populate es data : check out : https://www.strangebuzz.com/en/blog/implementing-a-search-engine-with-elasticsearch-and-symfony-part-2  section  : "Creating a custom provider"

**Comment by XWB** [comment]
^^
