### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by KDederichs** [FriendsOfSymfony/FOSElasticaBundle#1602]
Now that SF5 support is merged can we expect a 5.2 release some time in the near future?

**Comment by julkwel** [comment]
@KDederichs  I'm able to use this with SF5 by override a part of this bundle , here is the project

[Me and symfony 5](https://github.com/julkwel/me-and-symfony5)

**Comment by ThomasTr** [comment]
@XWB could you tag a new release please? FOSElasticaBundle is blocking Symfony 5 Upgrade.

**Comment by mpiot** [comment]
Oh yes a new release may be fine.

 If needed, for the moment you can require: `"friendsofsymfony/elastica-bundle": "5.x-dev",`. It works well, but not a good thing in production.

**Comment by XWB** [comment]
Unfortunately the next 5.x release is not yet ready.

**Comment by KDederichs** [comment]
Is there a list of things that still need to be done somewhere?

**Comment by COil** [comment]
@XWB I have forked https://github.com/COil/FOSElasticaBundle and merged the master to the 5.x branch, (there were two little conflicts), everything works correctly. I have updated my blog to Symfony5. 

If someone else want to try and check it it's ok for you too : 

Add in composer.json : 

    "repositories": {
        "coil_foselasticabundle": {
            "type": "vcs",
            "url": "git@github.com:COil/FOSElasticaBundle.git"
        }
    },

Then use : 

    "friendsofsymfony/elastica-bundle": "v5.1.2",

**Comment by amigainc** [comment]
I'm waiting for the new release, to finish migrating a project from SF3 to SF5!

**Comment by COil** [comment]
Hello amigainc, you can give a try with the repo I put just below (just to test). See you or see the answer of mpiot.

**Comment by amigainc** [comment]
> "friendsofsymfony/elastica-bundle": "5.x-dev"
Unfortunately, I already have installed latest ElasticSearch 7.5, and it's only compatible 5.3.5-6.1.1...

**Comment by amigainc** [comment]
> "friendsofsymfony/elastica-bundle": "5.x-dev"

First, you need to remove bundle **elasticsearch/elasticsearch** if installed, and install bundle **ruflin/elastica**. After that, install is OK! 

Now, let's try!!!

**Comment by COil** [comment]
@amigainc ? This bunlde is not compatible with Elasticseach 7.x yet. I don't understand your comment.

**Comment by amigainc** [comment]
> @amigainc ? This bunlde is not compatible with Elasticseach 7.x yet. I don't understand your comment.

It's a comment I've deleted, I found my error since.

**Comment by localheinz** [comment]
Is there anything holding up a new release that includes support for `symfony/symfony:^5`?

/cc @OskarStark

**Comment by COil** [comment]
Hello, any news for this?  /cc @XWB

**Comment by spointecker** [comment]
Any update here?

**Comment by fjugaldev** [comment]
any update about the release for symfony 5?

**Comment by oachoor** [comment]
Any news about SF5 support?

**Comment by mfeltscher** [comment]
Any news about this?

**Comment by hugosoltys-dkt** [comment]
Day 2321424, still waiting for news.

**Comment by COil** [comment]
I know this is not a solution but you can temporarily use my fork which works with Symfony 5.1, I use since several months in production. See my answer above.

**Comment by insekticid** [comment]
@COil I agree, I am using your fork since February

**Comment by tacman** [comment]
Sorry for such a simple question, but I'm not sure how to use your fork.

composer config repositories.fos_elastica '{"type": "vcs", "url": "
https://github.com/COil/FOSElasticaBundle.git"}'
composer req friendsofsymfony/elastica-bundle:dev-master

This still tries to get the original repo, not your fork.  I'm guessing
that it shouldn't be dev-master, but not sure what it should be.

Thanks,

Tac

**Comment by ThomasTr** [comment]
```
    "repositories": {
        "coil_foselasticabundle": {
            "type": "vcs",
            "url": "git@github.com:COil/FOSElasticaBundle.git"
        }
    }
```
require:
```
        "friendsofsymfony/elastica-bundle": "5.1.*",
```

**Comment by COil** [comment]
I have this, it should be the same  : `"friendsofsymfony/elastica-bundle": "^5.1",`

Try removing all your vendor, perhaps.

**Comment by tacman** [comment]
Does your fork support ES7?  I think that's where I'm having a problem.

**Comment by COil** [comment]
No, it's another problem. It's not compatible yet with Elasticsearch 7, check out this issue: https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1568 .

**Comment by leobeal** [comment]
@tacman check this PR. https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1569

The fork from @giovannialbero1992 seems to have fixed all remaining issues. I've been using it for few weeks now and all seem to work very well.

**Comment by XWB** [comment]
ES7 support has been added to the master branch.
