### ISSUE TITLE
how to search from ORM and Elastic together?

### ISSUE THREAD

**Issue by robert0770** [FriendsOfSymfony/FOSElasticaBundle#1605]
For example
my entity has fields:
id (int)
title (text) (stored also in elastic)
content (text) (stored also in elastic)
categoryId (int)
status (int)

and i want to search text from title,content i use 
`
//RepositoryManagerInterface $finder;
$results = $finder->getRepository(Offer::class)->find('AUDI A6 C6 2.0');
`
when i want search in database example by categoryId
`
$offers = $this->getDoctrine()->getRepository(Offer::class)->customOfferQueryBuilderWithResult(['categoryId'=>5]);
`
how to search it together? do I have to store categoryId also in elastic?

**Comment by hipachka** [comment]
mb,you can try first find array id then filter elastic

**Comment by robert0770** [comment]
ok thanks so better solution is index more fields
