### ISSUE TITLE
Index alias not working in combination with enqueue

### ISSUE THREAD

**Issue by nikolicaleksa** [FriendsOfSymfony/FOSElasticaBundle#1617]
Hello everyone, I am using Sylius 1.6.6 and have installed BitBagCommerce/SyliusElasticsearchPlugin plugin (not that much relevant).

Because of large amount of data I decided on speeding-up populate command in the suggested way from docs (https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/cookbook/speed-up-populate-command.md). I am using php-enqueue and RabbitMQ as transporter for this and it works as expected.

Later on I decided on using index alias because the website search needs to be available even when populate command is ran and it takes some time to finish because of large amount of data. This also works as expected when running command `php bin/console fos:elastica:populate`.

However the problem occurs when both queue and alias are being used.
- Run consumer: `php bin/console enqueue:consume --setup-broker -vvv`
- Run populate: `php bin/console fos:elastica:populate --pager-persister=queue`

The process finishes but the data for the aliased index is not there. I tried to debug it and came to the following result. When running `php bin/console fos:elastica:populate` the index is loaded as

> ^ FOS\ElasticaBundle\Persister\ObjectPersister^ {#4220
>   #type: Elastica\Type^ {#4214
>     #_index: FOS\ElasticaBundle\Elastica\Index^ {#4023
>       -originalName: "bitbag_shop_products_dev"
>       -typeCache: array:1 [
>         "default" => Elastica\Type^ {#4214}
>       ]
>       #_name: "bitbag_shop_products_dev_2020-04-04-160700"
>       #_client: FOS\ElasticaBundle\Elastica\Client^ {#4022
>         -indexCache: array:3 [
>           "bitbag_shop_products_dev" => FOS\ElasticaBundle\Elastica\Index^ {#4023}
>           "bitbag_option_taxons_dev" => FOS\ElasticaBundle\Elastica\Index^ {#4057
>             -originalName: null
>             -typeCache: []
>             #_name: "bitbag_option_taxons_dev"
>             #_client: FOS\ElasticaBundle\Elastica\Client^ {#4022}
>           }
>           "bitbag_attribute_taxons_dev" => FOS\ElasticaBundle\Elastica\Index^ {#4058
>             -originalName: null
>             -typeCache: []
>             #_name: "bitbag_attribute_taxons_dev"
>             #_client: FOS\ElasticaBundle\Elastica\Client^ {#4022}
>           }
>         ]

When doing the same thing but through queue the index is loaded as this when the message is being consumed:

> ^ FOS\ElasticaBundle\Persister\ObjectPersister^ {#6171
>   #type: Elastica\Type^ {#6189
>     #_index: FOS\ElasticaBundle\Elastica\Index^ {#4122
>       -originalName: null
>       -typeCache: array:1 [
>         "default" => Elastica\Type^ {#6189}
>       ]
>       #_name: "bitbag_shop_products_dev"
>       #_client: FOS\ElasticaBundle\Elastica\Client^ {#6210
>         -indexCache: array:1 [
>           "bitbag_shop_products_dev" => FOS\ElasticaBundle\Elastica\Index^ {#4122}
>         ]
>         -indexTemplateCache: []

As you can see when the index is loaded through queue it doesn't have originalName set and name is the name of the index and not index_YYYY-MM-DD-SS...

**Comment by nikolicaleksa** [comment]
Okay so I found a workaround for this. Instead of using aliases I just added option `--no-reset` so the full command is `php bin/console fos:elastica:populate --pager-persister=queue --no-reset`

**Comment by Ispolin08** [comment]
I faced same problem but its a bit deeper. 

If I use the alias and queue processing it creates new index (with time and etc) but putting documents to the current one, after all it change alias to new (but empty) and remove old one (which had newest data). 

no-reset is not the same as using alias.

**Comment by nikolicaleksa** [comment]
@Ispolin08 Yes I faced the same issue as you but came to conclusion that I cannot use both the alias and queue. In my use case it was sufficient to have it without an alias but run it with `--no-reset` option so that I don't lose any data.

**Comment by maciejmrozinski** [comment]
should fix the issue with aliased index when resetting: https://github.com/php-enqueue/enqueue-elastica-bundle/pull/38
