### ISSUE TITLE
FOSElasticaBundle and ElasticSearch 7 compatibility

### ISSUE THREAD

**Issue by sofictif** [FriendsOfSymfony/FOSElasticaBundle#1619]
Hello, 
Is there a date scheduled to have FOSElasticaBundle and ElasticSearch 7 compatibility?

**Comment by oscarpedrero** [comment]
Elasticsearch 7 and corresponding ruflin/elastica library will only be available in next major version.

https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1599

**Comment by florianfish** [comment]
In ten years ? :D

**Comment by stchr** [comment]
See #1569

**Comment by XWB** [comment]
ElasticSearch 7 support has been added to the master branch.
