### ISSUE TITLE
Manual provider usage returning error

### ISSUE THREAD

**Issue by leobeal** [FriendsOfSymfony/FOSElasticaBundle#1628]
Hi, 
By following the documentation on how to create a manual pager provider (https://github.com/leobeal/FOSElasticaBundle/blob/bump-package-versions/doc/cookbook/manual-provider.md), I get an error `No persister was registered for index "index_name"`.

On the provider, I am fetching data from an API and would expect no "persistence" settings would be needed. 

Thanks,

**Comment by Renrhaf** [comment]
Hi ! Did you find any solutions ?
