### ISSUE TITLE
Question about the project state

### ISSUE THREAD

**Issue by mpiot** [FriendsOfSymfony/FOSElasticaBundle#1633]
Hi everyone,
I know that the question is a bit unpleasant...
But, the last release date from 1 year ago and the last commit from more than 7 months. Moreover this bundle still not support Symfony 5 (November 2019).

It's a general question before start to use it on a new project.

Thanks a lot :)

**Comment by deguif** [comment]
Hi @mpiot 

Symfony 5 support should soon be added (with a lot more) in the same time than support for 
 Elasticsearch 7.x 
See https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1569 for more details

**Comment by mpiot** [comment]
Hi @deguif thank you for your answer. I'll go check it out then.

**Comment by XWB** [comment]
The author of https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1569 has finished his PR, and it has been merged into the master branch.
