### ISSUE TITLE
missing options in findHybridPaginated

### ISSUE THREAD

**Issue by geoffroyp** [FriendsOfSymfony/FOSElasticaBundle#1681]
Hi guys,

the $options are missing from the findHybridPaginated function in TransformedFinder.php, as well as in createHybridPaginatorAdapter from the same file, and finally in the __construct of HybridPaginatorAdapter.php

This prevent to be able to get more than 10 resultats per page when using findHybridPaginated, for example.

Could you please fix this?

Thanks :)

**Comment by deguif** [comment]
There is a PR about this already : https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1634
But the contributor is not responding anymore, maybe we should address this in another PR

If you want to contribute, feel free ;)

**Comment by geoffroyp** [comment]
I did. But since this is my first PR on an opensource project, I'm not quite sure why my PR doesn't work. It says it's the coding style that fails but there is no other details. So...I'm quite confused at the moment

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1683
