### ISSUE TITLE
$finder->find() method will only return 10 results

### ISSUE THREAD

**Issue by singingstars** [FriendsOfSymfony/FOSElasticaBundle#169]
I wish to get my Doctrine entity object searched. 
I configured along the way and managed to get elastica search results using `finder` for my entity. 
In my controller, `$finder->findPaginated('searchTerm')` worked fine. I got paginated 10+2 results.

But when I use `$finder->find('searchTerm')`, it will only return 10 results (where I assume 12); and it really confuses me, because I didn't add any limit to the find. I tried `$finder->find('searchTerm', '20')`, it will return all 12 objects in an array.

Was I doing something wrong?

**Comment by COil** [comment]
:+1: for having this in the doc I lost also time finding this issue.

**Comment by shadypierre** [comment]
:+1:

**Comment by dunnleaddress** [comment]
i set it like this in the find method to achieve limit of 3000.

$return = $this->find($query, 3000);

**Comment by dutchiexl** [comment]
I am having the same problem, is there another solution then just setting the limit to 3000 ?

**Comment by jmaquet** [comment]
@dutchiexl  :+1:

**Comment by julien-jourde** [comment]
After some research : https://discuss.elastic.co/t/get-query-is-showing-only-10-results-while-searching-for-a-particular-data/88187
If no limit is specified, ES return 10 results and the max is 10k.
