### ISSUE TITLE
The service "fos_elastica.async_pager_persister" has a dependency on a non-     existent service "messenger.default_bus"

### ISSUE THREAD

**Issue by deguif** [FriendsOfSymfony/FOSElasticaBundle#1701]
Since upgrade to BETA 2, I got this error.
That's related to new integration with symfony/messenger, but not using symfony/messenger shouldn't break.

I think something is wrong with current implementation. ping @giovannialbero1992

**Comment by deguif** [comment]
@XWB do you think we can revert the feature in the mean time?

**Comment by XWB** [comment]
I think we need to move to `symfony/messenger` related services to a separate xml file, and only load it if the component is installed. Something like https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/src/DependencyInjection/FOSElasticaExtension.php#L83

**Comment by deguif** [comment]
You're right, but the component is installed in my case, but not used nor configured.
So the ideal setup should be IMHO to add configuration options for defining messenger bus and anything related to this integration inside this bundle.

**Comment by deguif** [comment]
And also avoid a hard requirement on `symfony/messenger` in composer.json as discussed in the PR that added this support.

**Comment by XWB** [comment]
The requirement should at least be moved to `require-dev` otherwise the unit test will fail.
