### ISSUE TITLE
Any chance to use version 6.* with Symfony 3.4 ?

### ISSUE THREAD

**Issue by 2ur1st** [FriendsOfSymfony/FOSElasticaBundle#1715]
Our version of Symfony 3.4 and It not possible to update the very big project to Symfony 4.*. But our DevOps update ElasticSearch to version 7.* and I have no idea what to do? 
Maybe anyone has the same problem?
How to use the new version of FriendsOfSymfony/FOSElasticaBundle with Symfony 3.4

**Comment by deguif** [comment]
@2ur1st that won't be possible to support Symfony 3.4 on 6.x branch as so much was introduced which are not compatible with Symfony 3.4 and would require a lot of code to make it compatible with this unmaintained.

**Comment by 2ur1st** [comment]
@deguif thanks for the answer
