### ISSUE TITLE
Override MappingBuilder / hook into MappingBuilder proces

### ISSUE THREAD

**Issue by darthf1** [FriendsOfSymfony/FOSElasticaBundle#1725]
At this moment it is not possible to override the [`MappingBuilder`](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/src/Index/MappingBuilder.php) or hook into the mapping builder proces (Please tell me otherwise).

Things I would like to do:
- Have a basic mapping generated based on my serializer group. 
- Set a default [`null_value`](https://www.elastic.co/guide/en/elasticsearch/reference/current/null-value.html) (based on the property's value type) on each property, without having to define that property in the yaml config in the first place.

I'm willing to work on a PR for this, but I would like to check first if you think this is a valid thing to do, if you would accept such a PR and how you would like to have this resolved:

1. Create a `MappingBuilderInterface` and allow setting a `mapping_builder` service per index.
2. Add a `PostMappingBuilderEvent` just before [this](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/src/Index/MappingBuilder.php#L38) line.

I guess my preference would be the second as that would be a lot less work, but I'm open for suggestions :)

**Comment by XWB** [comment]
I would introduce an event, I don't think many people need a custom MappingBuilder.
