### ISSUE TITLE
6 version

### ISSUE THREAD

**Issue by kricha** [FriendsOfSymfony/FOSElasticaBundle#1733]
are there any news about releasing 6 version? 

sorry, if duplicate.

**Comment by jeroendesloovere** [comment]
Also interested in the reaction :-D

**Comment by deguif** [comment]
There was discussion here about the stable release: https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1657

**Comment by kricha** [comment]
@deguif i see, but in this mr no information about release time frames from september...

**Comment by XWB** [comment]
Things we need for a final beta:

- [ ] Get https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1729 fixed
- [ ] Add a test for https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1734
- [ ] Allow PHP 8 https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1642

**Comment by kricha** [comment]
@XWB thanks! 

As i see, only `PR on elasticsearch/elasticsearch to add support for PHP 8.0` remained

**Comment by deguif** [comment]
There is also an issue with testing that we should fix before releasing I think.
Tests should probably be moved to Gihub action, I did this for https://github.com/ruflin/Elastica project as we were having issue too since Travis updated their policy for open-source projects.

**Comment by XWB** [comment]
I suppose we will have to implement something like https://github.com/FriendsOfSymfony/FOSRestBundle/commit/1483a697362fbe1919741543a5673b3304873097

**Comment by stchr** [comment]
Is there an eta for the final release?

Would be glad to help out to speed this up, either by coding or sponsoring.  Just reach out to me 🤝

**Comment by deguif** [comment]
We should now be able to publish a new release as elasticsearch official library now supports PHP 8.0 and ruflin/elastica too.
The only blocker remaining here is the CI not working anymore. I'm taking care of it by migrating to Github action.

**Comment by kricha** [comment]
Hey 👋

yet no news about new version?

**Comment by deguif** [comment]
For the remaining issue about CI, this should be fixed soon: see https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1762

**Comment by deguif** [comment]
@XWB should we publish a latest RC version before releasing the 6.0 ?

**Comment by XWB** [comment]
Yes I agree :)

**Comment by stefanvandekaa** [comment]
Is there an ETA for the next 6.0-RC or 6.0 version?

**Comment by kricha** [comment]
Hello, is there any chance to see released 6 version in a month or repo and this project is dead?

**Comment by ostrolucky** [comment]
Can we at least get a new beta version tagged? There is no release with PHP 8 support, that's a big bummer.

**Comment by deguif** [comment]
@XWB Would you be open to add new maintainers on this project?
I would be very happy to help you on merging PRs and releasing versions.

**Comment by kg4b0r** [comment]
Any news about the release of stable version 6?

**Comment by b1rdex** [comment]
> @XWB Would you be open to add new maintainers on this project?
> I would be very happy to help you on merging PRs and releasing versions.


@XWB friendly ping

**Comment by kricha** [comment]
@XWB hello, is that dead repo?

**Comment by kricha** [comment]
HELLO, ANY NEWS?

**Comment by XWB** [comment]
v6 is out today: https://github.com/FriendsOfSymfony/FOSElasticaBundle/releases/tag/v6.0.0
