### ISSUE TITLE
Error 500 - Notice: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by maniekx1984** [FriendsOfSymfony/FOSElasticaBundle#1754]
Hi, I have a problem with ElasticaBundle (5.2) on PHP 7.4. On PHP 7.3 is ok.

On every persist/update I have this error:

Notice: Trying to access array offset on value of type null
![image](https://user-images.githubusercontent.com/5805886/107211880-70d09d00-6a06-11eb-8bb4-2e31c16cfc79.png)

I hope you can help me with this.
Thanks.

**Comment by T-Nagui** [comment]
hello, I have the same pb did you fixe it ?

**Comment by maniekx1984** [comment]
> hello, I have the same pb did you fixe it ?

Hi, yes. It was my mistake. I've extended event listener without parent::__construct();
