### ISSUE TITLE
Not compatible with PagerfantaBundle v3

### ISSUE THREAD

**Issue by annuh** [FriendsOfSymfony/FOSElasticaBundle#1760]
PagerfantaBundle released a new version: https://github.com/BabDev/PagerfantaBundle/releases/tag/v3.0.0

This bundle is not compatible with the latest PagerfantaBundle:

```
PHP Fatal error:  Declaration of FOS\ElasticaBundle\Paginator\FantaPaginatorAdapter::getNbResults() must be compatible with Pagerfanta\Adapter\AdapterInterface::getNbResults(): int in vendor/friendsofsymfony/elastica-bundle/src/Paginator/FantaPaginatorAdapter.php on line 30
```

We are using:
```
    "friendsofsymfony/elastica-bundle": "6.0.0-beta3",
```

**Comment by XWB** [comment]
The interface has changed: https://github.com/BabDev/Pagerfanta/blob/3.x/lib/Core/Adapter/AdapterInterface.php

Can you check if https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1764 resolves the issue?

**Comment by annuh** [comment]
Yes that works, thanks! 👍

**Comment by XWB** [comment]
Fixed in master.
