### ISSUE TITLE
Current support status of OpenSearch

### ISSUE THREAD

**Issue by StudioMaX** [FriendsOfSymfony/FOSElasticaBundle#1804]
Maybe you heard about a fork of ElasticSearch 7.10.2 called OpenSearch. It is still the same Amazon ElasticSearch Service, but under a different brand. They claim the API remains backward compatible.
Although it is still in beta, it is already gaining some popularity. But in FOSElasticaBundle there is no mention of OpenSearch's brand support status. I think this information would be useful for those who plan to use OpenSearch in the future, given that the version numbers of the original ElasticSearch and the OpenSearch fork will not match.

Links:
https://www.opensearch.org/
https://aws.amazon.com/blogs/opensource/introducing-opensearch/
https://github.com/opensearch-project/OpenSearch

**Comment by deguif** [comment]
The answer here is the same than @ruflin on https://github.com/ruflin/Elastica/issues/1962 as this bundle is based on the elastica library.

**Comment by XWB** [comment]
^^
