### ISSUE TITLE
Issue using SoftDeletion doctrine extension

### ISSUE THREAD

**Issue by athieriot** [FriendsOfSymfony/FOSElasticaBundle#183]
Hi,

   We currently use the [SoftDeletion](http://www.gediminasm.org/article/softdeleteable-behavior-extension-for-doctrine-2) extension from Gedmo in a Symfony2 app and start building a Search feature around elasticsearch.

   We encounter an issue when using the two Bundle together. 
   With SoftDeletion, object are not really deleted but stay in the database with a deletion date field updated.

   But, that way, the object is never removed from the index. And we got an exception when Elastica try to map the index object with the related entity.

What is the better way to handle this?

Thank you.

Aurélien

**Comment by smilesrg** [comment]
@richardmiller +1 for adding this to cookbook

**Comment by smilesrg** [comment]
@nurikabe there is no such service. Even if I put index name instead of .type. BTW you have a type (foq_ instead of fos_)

**Comment by dbu** [comment]
@smilesrg foq was the old version. you are looking at the rewritten current version of bundle.

**Comment by smilesrg** [comment]
@dbu thanks! I've used ```$this->container->get("fos_elastica.object_persister.search.$type")->deleteOne($entity);
``` as a temporary solution.

```php
    public function postSoftDelete(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();

        if ($entity instanceof InstagramShopPicture) {
            $type = 'picture';
        } else if ($entity instanceof InstagramShop) {
            $type = 'shop';
        } else {
            return;
        }

        $this->container->get("fos_elastica.object_persister.search.$type")->deleteOne($entity);
    }
```

**Comment by rvdbogerd** [comment]
For all those people still ending up here: it's very easy to fix, just add a Method to your entity like 'isActive' and add that to your config as a persistence listener:

    indexes:
        mynamespace:
                mymodel:
                    mappings:
                        ...
                    persistence:
                        provider: ~
                        model: My\Model
                        repository: My\Repository
                        listener:
                            is_indexable_callback: "isActive"

Then add a little something like this to your model and your done:

    public function isActive(): bool
    {
        return !$this->deletedAt;
    }
