### ISSUE TITLE
Can't access Aggregation data via Finder; Pagerfanta deprecated `->getAdapter()`;  Doc needs Update

### ISSUE THREAD

**Issue by floriankapaun** [FriendsOfSymfony/FOSElasticaBundle#1854]
The [Usage Documentation](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/usage.md), shows the following [example](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/usage.md#aggregations) to get Aggregation data:

```
...
$aggs = $companies->getAdapter()->getAggregations();
```

This is outdated, since Pagerfanta deprecated `->getAdapter()` and there is no `->getAggregations()` function within the `AdapterInterface` anymore.

I found no way to access aggregation data via the Finder as of now. Please correct me if I'm wrong.

We could easily provide this by making the `TransformedFinder`s `$searchable` property accessible with a getter.

Then we could do something like

```
...
$companies = $this->finder->getSearchable()->search($query);
```

Some more Context: https://github.com/BabDev/Pagerfanta/issues/35

**Comment by mbabker** [comment]
This can be closed out, https://github.com/BabDev/Pagerfanta/commit/a2fddfd10e6113a86c52b04c8c94a5ef0d71c9ab (not yet released) removes the deprecation on the `getAdapter()` method.

My general thinking was that most folks who'd need access to the adapter are also already creating it before they instantiate a `Pagerfanta` instance, so they'd already have it in scope to use.  But, projects like this one and Sylius have some APIs that make it impossible to access the adapter as they build the `Pagerfanta` object and send it back to the caller, and there isn't a clean solution to decorating/extending the `Pagerfanta` class to make it available for those who do need it.  So, I'll leave it in the API as the breakage here just isn't worth the headache in the long run.

**Comment by floriankapaun** [comment]
Closing this because @mbabker truly stated, the `getAdapter` deprecation notice got removed again.
