### ISSUE TITLE
Branch 5.x compatible with PHP8

### ISSUE THREAD

**Issue by ypereirareis** [FriendsOfSymfony/FOSElasticaBundle#1856]
HI !

thanks for this incredible bundle !

- Is version 5.x compatible with PHP8 ?
- if not, is it planned to do what is needed to add compatibility ?

Thanks !!

**Comment by ypereirareis** [comment]
Hi once again !

Any information about PHP8 compat on branch 5.x would be really appreciated.

Thanks.

**Comment by XWB** [comment]
Well, the 5.x branch is not maintained anymore. It would be difficult to support old versions, even elasticsearch 5.x has been EOL for quite some time.

**Comment by jorrit** [comment]
I've been running the 5.1 branch on PHP 8 for a while and there seem to be no incompatibilities in every day use.

**Comment by manuelkiessling** [comment]
If you absolutely must keep using the 5.x branch (which of course I recommend against), while at the same time running on PHP 8, see this fork work the neccessary changes: https://bitbucket.org/go-gastro/foselasticabundle/src/5.x-php8.2/

This fork however comes with NO WARRANTIES WHATSOEVER.
