### ISSUE TITLE
Get results which contains query

### ISSUE THREAD

**Issue by bastien70** [FriendsOfSymfony/FOSElasticaBundle#1880]
Hello, I am discovering ElasticSearch and this bundle, and for several hours I have been trying to perform a partial query on all the fields.

To get the results which have among their fields the exact term 'Ipsum' I will for example do :

```php
$search = Util::escapeTerm('Ipsum');
$result = $this->postsFinder->findHybrid($search, 15);
```

But if I want the results where the fields contain a string (equivalent of LIKE in DQL), how should I go about it?

I don't see anything in the bundle documentation about this.
Thank you

**Comment by keganv** [comment]
I'm looking for the same thing, how to implement a fuzzy search. The "options" argument seems to be ambiguous, as every key that I've passed so far says it's not a valid option.

`$data = $finder->findHybrid($request->query->get('term'), null,
            [
                'match' => [
                    'fuzziness' => 'AUTO:0,2'
                ]
            ]
        );`

**Comment by keganv** [comment]
This page, helps somewhat. 
[https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html](url)

**Comment by XWB** [comment]
You will need to construct a query with the `ruflin/elastica` library and pass it to the finder or search service. FOSElasticaBundle does not construct queries for you.

Here's an example of a simple 'like' search:

```php
use Elastica\Query;

$query = new Query();
$boolQuery = new Query\BoolQuery();

$titleQuery = new Query\Match();
$titleQuery->setField('title', [
    'operator' => 'and',
    'query' => Util::escapeTerm('Ipsum'),
]);

$boolQuery->addMust($titleQuery);

$query->setQuery($boolQuery);

$result = $this->finder->findHybrid($query, 15);
```

The example assumes you have a working elastic index, with properties, analyzers and tokenizers configured.

I never used fuzzy search but I assume it would be similar. You can find some query examples in https://github.com/ruflin/Elastica/blob/master/tests/Query/FuzzyTest.php
