### ISSUE TITLE
Class QueryAdapter not found after updating to v6.3.0

### ISSUE THREAD

**Issue by fzberlin23** [FriendsOfSymfony/FOSElasticaBundle#1911]
Hi,

today i updated friendsofsymfony/elastica-bundle (v6.2.0 => v6.3.0).

```
php composer.phar update --no-progress --with-all-dependencies

Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 2 updates, 1 removal
  - Removing pagerfanta/pagerfanta (v3.6.2)
  - Upgrading friendsofphp/proxy-manager-lts (v1.0.15 => v1.0.16)
  - Upgrading friendsofsymfony/elastica-bundle (v6.2.0 => v6.3.0)
  - Locking pagerfanta/core (v3.8.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 2 updates, 1 removal
  - Removing pagerfanta/pagerfanta (v3.6.2)
  - Upgrading friendsofphp/proxy-manager-lts (v1.0.15 => v1.0.16): Extracting archive
  - Installing pagerfanta/core (v3.8.0): Extracting archive
  - Upgrading friendsofsymfony/elastica-bundle (v6.2.0 => v6.3.0): Extracting archive
```

When i run `php app/console fos:elastica:populate` in my symfony application i get:

```
In ORMPagerProvider.php line 79:
                                                                               
  Attempted to load class "QueryAdapter" from namespace "Pagerfanta\Doctrine\  
  ORM".                                                                        
  Did you forget a "use" statement for another namespace?                      
                                                                               

fos:elastica:populate [--index [INDEX]] [--no-reset] [--no-delete] [--sleep SLEEP] [--ignore-errors] [--no-overwrite-format] [--first-page FIRST-PAGE] [--last-page LAST-PAGE] [--max-per-page MAX-PER-PAGE] [--pager-persister PAGER-PERSISTER] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

It seems that in ORMPagerProvider.php line 79 the class `QueryAdapter` is used. But this class does not exist anymore (it existed in pagerfanta/pagerfanta, which was removed).

Does anyone have the same problem? Thank you very much.

**Comment by mitrae** [comment]
confirm, same error. updated PagerfantaBundle to the latest 3.x - did not help
symfony 4.4, php 7.4, elasticsearch 7

**Comment by cristobaldiaz-aircury** [comment]
Confirmed it happens also upgrading from 5.1 to 6.3. It seems that the issue appeared when switching this requirement in 6.3:
[pagerfanta/pagerfanta](https://packagist.org/packages/pagerfanta/pagerfanta): ^2.4 || ^3.0
for this one
[pagerfanta/core](https://packagist.org/packages/pagerfanta/core): ^2.4 || ^3.0

I discovered this workaround:
`composer require pagerfanta/pagerfanta:^2.4 -W`

**Comment by mbabker** [comment]
You can install whichever adapters your application will need using the list at https://www.babdev.com/open-source/packages/pagerfanta/docs/3.x/installation

The PagerfantaBundle stopped installing the `pagerfanta/pagerfanta` mono-package with 3.0 and I'm generally encouraging folks to rely on the subsplit packages over the full mono-package (as installing the mono-package brings in a lot of unused code and has a much more complex dependency graph for Composer to deal with compared to the individual packages).

**Comment by XWB** [comment]
@mbabker You are certainly right, but perhaps we should restore the `pagerfanta/pagerfanta` dependency for BC reason, and make the split in the next major release?
