### ISSUE TITLE
Incompatibility with doctrine/orm ^3

### ISSUE THREAD

**Issue by emhovis** [FriendsOfSymfony/FOSElasticaBundle#1944]
It would be neat if we could get doctrine/orm ^3 support.

At the moment, the only thing I believe that's holding back is the calls to the removed functions: getSqlLogger() and setSqlLogger() within the RegisterListenersService which will seemingly change how logging (or not logging rather) is handled.

**Comment by scolandrea** [comment]
Isn't this issue related to the database abstraction layer? You can use Doctrine ORM 2.x and you can still have this warning if you run doctrine/dba up to ^3.

Anyway, you are right, the compatibility should be addressed shortly.
