### ISSUE TITLE
Lose ModelToElasticaAutoTransformer->transform() $fields parameter

### ISSUE THREAD

**Issue by brainartdev** [FriendsOfSymfony/FOSElasticaBundle#220]
Transformer (model-to-elastica, but apparently elastica-to-model too) should be initalized once per Type with $fields definitions, so there would be no necessity to do _exactly_ the same stuff for each document - constructing PropertyPath objects. This is significant time loss when you are dealing with millions of documents.

It is quite difficult to build such transformer yourself because $fields have gone thru some processing, which is not available publicly AFAIK.

**Comment by jandom** [comment]
We're very interested in this, seeing majority of the time spent on Entity -> Associative array conversion, when we repopulate ES from scratch. Does anybody have any ideas how this step could be improved/speed up? 

We've spent a lot of time understanding refresh_interval and other ES settings but upon careful inspection it's this Entity -> Array step that's the most costly, especially when multiple fields are defined.
