### ISSUE TITLE
fos:elastica:populate doesn't use is_indexable_callback

### ISSUE THREAD

**Issue by arnestockmans** [FriendsOfSymfony/FOSElasticaBundle#287]
In my configuration I use `is_indexable_callback` several times. This seems to be working (except for issue #284), although when I run the fos:elastica:populate command, this setting gets ignored completely.

**Comment by merk** [comment]
The documentation is up to date. `indexable_callback` is the new parameter name. `is_indexable_callback` is the old name.

https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/DependencyInjection/Configuration.php#L230
