### ISSUE TITLE
Exception when relation property contains null

### ISSUE THREAD

**Issue by maks-rafalko** [FriendsOfSymfony/FOSElasticaBundle#349]
Hi,

Is it possible to not index those nested objects, which are `null`.
For example:

I have multi-step forms, so on the first step I don't have all related objects to persist.
`ElasticaBundle` throws and exception because of these lines of code:

``` php
// ModelToElasticaAutoTransformer.php
public function transform($object, array $fields)
{
    $identifier = $this->propertyAccessor->getValue($object, $this->options['identifier']);
    $document = new Document($identifier);

    foreach ($fields as $key => $mapping) {
        // exception is thrown here
        $value = $this->propertyAccessor->getValue($object, $key);

        // .....
    }

    return $document;
}
```

So exception is thrown with message: "Expected argument of type "object or array", "NULL" given"

I don't see any settings to avoid this behavior.
I only have one idea - do not index such entities by setting `is_indexable_callback` until the last form step.

Please give me some information how to handle this case.
Thank you.

**Comment by diegotham** [comment]
Please could you tell me how can I allow null in object types with ModelToElastica? Should I only set a parameter in config, create a service...? Thank you

**Comment by priyankoctal** [comment]
@borNfreee I am facing same issue, did you managed to fix it by config rather than class overriede,

I am newbie so I am still now sure how to override transformer

**Comment by borNfreee** [comment]
@priyankoctal no, it was 5 years ago ;) Unfortunately, I don't remember how I solved it

**Comment by priyankoctal** [comment]
@jtwebb 

did you

> 
> 
> @priyankoctal no, it was 5 years ago ;) Unfortunately, I don't remember how I solved it

Can you review this matter and let me know how to fix this as I am very newbie and I am stuck

**Comment by priyankoctal** [comment]
> 
> 
> @priyankoctal no, it was 5 years ago ;) Unfortunately, I don't remember how I solved it

Ok can you review this issue and suggest me something

**Comment by priyankoctal** [comment]
> 
> 
> ModelToElastica transformer now properly handles null values for object or nested types

@merk still is is not fixed
