### ISSUE TITLE
Custom identifier on nested object

### ISSUE THREAD

**Issue by thujeevan** [FriendsOfSymfony/FOSElasticaBundle#357]
As of now i can be able to specify custom identifier of the main document, but when it comes to nested objects where the nested object has its own custom identifier, populating index breaks. It looks for the specified identifier in the nested object too. This happens here, while it's recursively getting called

```php
    public function transform($object, array $fields)
    {
        $identifier = $this->propertyAccessor->getValue($object, $this->options['identifier']);
        $document = new Document($identifier);

```

How can this be solved?
Any help will be much appreciated

**Comment by jvandesande** [comment]
This problem still exists in the master branch, it's a very annoying bug when you run into it. I think the best way to solve it right now, is by extracting the foreach loop ```foreach ($fields as $key => $mapping)``` into a private method that can be called from the ```transform``` and ```transformNested``` methods.

**Comment by jvandesande** [comment]
I've created a PR for this, see #918
