### ISSUE TITLE
How to findPaginated() return highlighted resultSet?

### ISSUE THREAD

**Issue by wenmingtang** [FriendsOfSymfony/FOSElasticaBundle#384]
```
    $finder = $this->get('fos_elastica.finder.website.position');

    $queryString = new QueryString($request->get('query');
    $queryString->setDefaultOperator('AND');

    $query = new Query($queryString);
    $query->setHighlight(array(
        'fields' => array(
            'description' => array(
                'fragment_size' => 900,
                'number_of_fragments' => 1,
            ),
            'position' => array(
                'fragment_size' => 100,
                'number_of_fragments' => 1,
            ),
        ),
        'pre_tags'    => array('<em class="highlight">'),
        'post_tags'   => array('</em>'),
    ));

   $paginator = $finder->findPaginated($query);
   $paginator->setCurrentPage($request->get('page', 1));
```

$paginator not include highlighted results，how to return highlighted results?

thx

**Comment by yoh** [comment]
:+1:

**Comment by yoh** [comment]
Why just return _source with array_map in Paginator/RawPartialResults ? https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/cacb40286c6dd1da6d53d141f453ade237344fa5/Paginator/RawPartialResults.php#L28 ?
Why not just return ```$this->resultSet->getResults()``` in toArray() method ?
This allows to return highlights or others stuff.

**Comment by yoh** [comment]
To bypass it, i write my own ElasticaToRawTransformer and use the TransformedPaginatorAdapter.

```php
$pagination = $this->get('knp_paginator')->paginate(
    new \FOS\ElasticaBundle\Paginator\TransformedPaginatorAdapter(
        $this->get('fos_elastica.index.project.doc'),
        $elasticQuery, // \Elastica\Query
        [], // options
        new \MyBundle\Transformer\ElasticaToRawTransformer()
    ),
    $request->query->get('page', 1),
    10
);
```

The ElasticaToRawTransformer class which implement FOS\ElasticaBundle\Transformer\ElasticaToModelTransformerInterface : https://gist.github.com/yoh/3d1553f1ff1164121b9b
This just return raw data with highlights !

**Comment by Apostropher** [comment]
@yoh Your final comment has been very helpful! 

Instead of `\FOS\ElasticaBundle\Paginator\TransformedPaginatorAdapter`, I've used `FOS\ElasticaBundle\Paginator\RawPaginatorAdapter`

**Comment by ahmed-bhs** [comment]
Can you share your code plz ?
