### ISSUE TITLE
Issue with colon ":" char in QueryString

### ISSUE THREAD

**Issue by jpetitcolas** [FriendsOfSymfony/FOSElasticaBundle#416]
We are currently facing an issue with colon character, a _SearchPhaseExecutionException_, probably due to interpretation of this special char. Here is the guilty code:

``` php
$fieldQuery = new QueryString();
$fieldQuery->setDefaultOperator('AND');
$fieldQuery->setFields(array('body', 'title'));
$fieldQuery->setQuery(trim($query));
```

Is there any way to escape properly all special characters in `$query` variable? We are hot fixing it by a `strtr` call, but not fan of it.

**Comment by gherkins** [comment]
:+1:

**Comment by silentiumtempus** [comment]
👍
