### ISSUE TITLE
Unexpected character when running populate command

### ISSUE THREAD

**Issue by hardchor** [FriendsOfSymfony/FOSElasticaBundle#431]
I just got the latest dev version because I needed functionality introduced in #413. However, upon running `app/console fos:elastica:populate`, i get the following error:

```
  [Elastica\Exception\ResponseException]                                                                                   
  Unexpected character (':' (code 58)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')  
   at [Source: [B@1706f0fd; line: 1, column: 80]     
```

On closer inspection, this happens when the batch inserter runs. This is what is being posted to ES:

```
{"index":{"_index":"patient","_type":"user","_id":1234}}
{
    "date_of_birth": "1970-07-08T22:00:00+0000",
    "firstname": "Test",
    "lastname": "User",
    "id": 1234
}
```

Line 1, character 80 is the colon after `date_of_birth`.

Any idea what might be going wrong?

**Comment by glennthehuman** [comment]
Was this ever resolved?
