### ISSUE TITLE
Autocompletion? Elastic Completion Suggester? Typeahead? 

### ISSUE THREAD

**Issue by hubchau** [FriendsOfSymfony/FOSElasticaBundle#445]
Hi, 

I want to add an autocompletion feature to my Elastic Search. Does anyone have it?

Should I use Typeahead.js?

I came across this tuto (http://devblog.lexik.fr/symfony2/autocompletion-avec-elasticsearch-2525) but it's already outdated (it's using Bootstrap 2 and its ".typeahead" class attribute which is now depreciated).

What about Elastic's completion suggester? (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-suggesters-completion.html)
Did you guys try it?

Thank you very much for your help :)

**Comment by XWB** [comment]
Don't think this is really related to this bundle.

**Comment by pittersnider** [comment]
It's horrible that this Bundle doesn't let us execute raw queries.
