### ISSUE TITLE
Random Sorting

### ISSUE THREAD

**Issue by trsteel88** [FriendsOfSymfony/FOSElasticaBundle#474]
I am trying to implement random sorting on my query (http://www.elasticsearch.org/blog/0-90-4-released/). Can anyone tell me how I could do this on the \Elastica\Query Object?

Thanks.

**Comment by mcanepa** [comment]
I would like to complete @trsteel88 's code for v5 (2019)

Include this in you php:
`use Elastica\Query\FunctionScore;`

Then do your nomal query building with `$bool->addMust()`, `$bool->addShould()`, etc

and finally set the randomness like:

```
$seed = time() . rand(10000, 20000);
$randomScore = new FunctionScore();
$randomScore->setRandomScore($seed);
$randomScore->setQuery($bool);

$query->setQuery($randomScore); //normally you would do $query->setQuery($bool);
```
