### ISSUE TITLE
'time' format for date field failed with error

### ISSUE THREAD

**Issue by liuwenchao** [FriendsOfSymfony/FOSElasticaBundle#498]
I'm trying to index a time field w/o date part via orm driver, but it failed with this error:

Config:
    start_time: { type: date, format: time }
format is from: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-date-format.html

Error:
    caused MapperParsingException[failed to parse [start_time]]; nested: Map  perParsingException[failed to parse date field [2014-03-09T09:00:00-0500], tried both date format [time
], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "2014-03-09T09:00:00-0500" is malformed at "14-03-09T09:00:00-0500"];  

Does anyone know what's wrong here?

**Comment by bartclarkson** [comment]
Code illustrating answer by @merk .  Save somebody else a little time.  I'm still on v3.0.9 to support Doctrine version associated with Symfony 2.3.  Maybe this isn't an issue anymore in dev-master.

```xml
#config.yml
fos_elastica:
    indexes:
        site:
            types:
                document:
                    mappings:
                        date_created: { type: date, format: 'yyyy-MM-dd HH:mm:ss' }
```

```php
<?php
// src/Acme/DemoBundle/Entity/Document.php
/**
 * @ORM\Entity
 */
class Document
{
    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @Assert\DateTime()
     */
    protected $created_at;

    /**
     * 
     * Supports FOSElasticaBundle (see config_{env}.yml
     *
     */

    public function getDateCreated()
    {
	    return $this->created_at->format('Y-m-d H:i:s');
    }
}
```
