### ISSUE TITLE
How to get count results?

### ISSUE THREAD

**Issue by weburnit** [FriendsOfSymfony/FOSElasticaBundle#564]
``` php
            $finder = $this->finder;
            $query = new NormalQuery;
            $boolQuery = new Bool();
            foreach ($data as $key => $value) {
                if (is_string($value)) {
                    $fieldQuery = new TextQuery;
                    $fieldQuery->setFieldQuery($key, $value);
                    $fieldQuery->setFieldOperator($key, 'and');
                    $boolQuery->addShould($fieldQuery);
                } else if (is_array($value)) {
                    $termsQuery = new Terms();
                    $termsQuery->setTerms($key, $value);
                    $boolQuery->addShould($termsQuery);
                    $boolQuery->addMust($termsQuery);
                }
            }
            $query->setQuery($boolQuery);
            $results = $finder->find($query);
```

How to get total results for that query?

I have dig into this bundle but dont see any snippet support this.

Regards.

**Comment by LewisW** [comment]
> Hi,
> 
> I'm trying to apply both solutions, and i red the whole (short) manual. Without success so far.
> 
> What i need is to know the total count of matching results from a filtered query. In JSON directly on Elastic Search server you would call
> 
> ```
> localhost:9200/_search?search_type=count
> ```
> 
> with the query params, like:
> 
> ```
> {
>   "query": {
>     "filtered": {
>       "query": {
>         "match_all": []
>       },
>       "filter": {
>         "bool": {
>           "must": [
>             {
>               "terms": {
>                 "media.category.id": [
>                   681
>                 ]
>               }
>             }
>           ]
>         }
>       }
>     }
>   },
>   "sort": {
>     "published_at": {
>       "order": "desc"
>     }
>   },
>   "size": 1
> }
> ```
> 
> Note the "search_type=count" URL param.
> 
> It actually doesn't need any pagination, nor it return any document. But how to use that from FOSElasticaBundle please?
> 
> I tried this:
> 
> ```
> $query = (...) // building the Elastica query here
> $count = $this->finder->findPaginated(
>             $query,
>             array(ES::OPTION_SEARCH_TYPE => ES::OPTION_SEARCH_TYPE_COUNT)
>         )->getNbResults();
> ```
> 
> But i get an Attempted to load class "Pagerfanta". I don't want Pagerfanta.
> 
> Then this:
> 
> ```
>         $count = $this->finder->createPaginatorAdapter(
>             $query,
>             array(ES::OPTION_SEARCH_TYPE => ES::OPTION_SEARCH_TYPE_COUNT)
>         )->getTotalHits();
> ```
> 
> But it would always give me 0.
> 
> Thank you.

You can call count on the underlying Elastica index class, see this post (but call `count` instead of `search`):
https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/1282#issuecomment-343902827
