### ISSUE TITLE
Pagerfanta / Double Query

### ISSUE THREAD

**Issue by StefanGlaesser** [FriendsOfSymfony/FOSElasticaBundle#587]
Hello,
I'm using the Pagerfanta component for navigation through my results page by page:

$userPaginator = $finder->findPaginated($request->get('q'));
$userPaginator->setCurrentPage($page);

That leads to 2 (nearly identical) elasticsearch queries:
1. query: {"query":{"query_string":{"query":"ak"}}}
2. query: {"query":{"query_string":{"query":"ak"}},"from":10,"size":10}

So my question is, why are 2 queries fired instead of one?

**Comment by Koc** [comment]
relates to https://github.com/whiteoctober/Pagerfanta/pull/183
