### ISSUE TITLE
[RFC] New pagination

### ISSUE THREAD

**Issue by merk** [FriendsOfSymfony/FOSElasticaBundle#689]
We've got a few outstanding PRs to add aggregations or other features available to Elastica into our Pagination interfaces, but to me this exposes that the interfaces of this bundle are not flexible and need to be improved.

I propose the following way I believe that pagination should work:

``` php

$search = new \Elastica\Search($this->container->get('fos_elastica.client'));
$search->addIndex($this->container->get('fos_elastica.index.index_name'));
$search->addType($this->container->get('fos_elastica.index.type_name1'));
$search->addType($this->container->get('fos_elastica.index.type_name2'));

$query = /** Build an instance of an \Elastica_Query object that you want to search against the Searchable */

// Using Pagerfanta:
$adapter = new ElasticaAdapter($search, $query);
$pagerfanta = new Pagerfanta($adapter);

// Using Knp Paginator
$paginator  = $this->get('knp_paginator');
$pagination = $paginator->paginate(
    new ElasticaAdapter($search, $query),
    $this->get('request')->query->get('page', 1)/*page number*/,
    10/*limit per page*/
);
```

It may be possible to adjust the api slightly to avoid the need to create a Search object and accept a SearchableInterface object that we would convert internally into a Search object.

I also face problems with this implementation - the return values that we can return. For 3.2 or 4.0 I plan on removing our Hybrid results completely, and instead only return the Elastica ResultSet containing only Elastica Result objects. I hope to have a method, getTransformed() on the Result to return the transformed object. This cant be done for 3.1.

The only option I can think of that lets me keep some level of forward compatibility without forcing you all to make changes is:

``` php
// In php
foreach ($pagerfanta as $result) {
  $transformed = $resultTransformer->transform($pagerfanta, $result);

 // Do stuff with $transformed
}

// In twig
{% for result in pagerfanta %}
  {% set transformed = result | fos_elastica_transform(pagerfanta) %}

  {# Do stuff with transformed #}
{% endfor %}
```

I would appreciate feedback from those that actually use pagination, since in my applications I dont paginate search results.

**Comment by nurikabe** [comment]
+1

**Comment by hugohenrique** [comment]
I tested its proposal with a structure:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html#_example

And it did not work, you suggest something?
