### ISSUE TITLE
Cannot find corresponding Doctrine objects for all Elastica results. 

### ISSUE THREAD

**Issue by piux** [FriendsOfSymfony/FOSElasticaBundle#703]
after deleting a entry with doctrine ´´´$em->flush();´´´  this happened, after using fos:elastica:populate the results show and isnt a issue, how can i avoid having this error everytime i modify the database?

i was planning to use elastic search for searching for the moment.

**Comment by ginadub86** [comment]
Does anyone has the answer on this problem? I'm running into the same problem at the moment :-(

Everytime after a search on the website there is the error 500... We tried to solve this with a cronjob for the populate, but didn't solve the problem.
