### ISSUE TITLE
Couldnt connect to host, ElasticSearch down?

### ISSUE THREAD

**Issue by Chrysweel** [FriendsOfSymfony/FOSElasticaBundle#71]
When I write " php app/console foq:elastica:populate " I get the following error:

[Elastica_Exception_Client]
Couldnt connect to host, ElasticSearch down?

My config.yml is:

foq_elastica:
   clients:
      default: { host: localhost, port: 9200 }
   indexes:
      website:
         client: default
         types:
            user:
               mappings:
                  username: { boost: 5 }
               persistence:
                  driver: orm
                  model: myAplicattion\MyBundle\Entity\User
                  provider:
                     query_builder_method: createIsActiveQueryBuilder
                  finder:

And I have the method " createIsAtiveQueryBuilder "  in my userRepository.php.

I do not know that I have to do now.
I do not speak much English, would appreciate long answers.   ; )

**Comment by qiaofei32** [comment]
stop iptables
disable Selinux
then try again
