### ISSUE TITLE
\Pagerfanta\Pagerfanta setCurrentPage() sends aditional query to Elasticsearch

### ISSUE THREAD

**Issue by dmarko484** [FriendsOfSymfony/FOSElasticaBundle#710]
I'm using FOSElasticaBundle with Pagerfanta and I found out that setting the current page on finder object sends its additonal query to Elasticsearch which increases page processing time sligtly. I found the problem with in \Pagerfanta\Pagerfanta setCurrentPage() method and line " $this->filterCurrentPage($currentPage);", when I disable this check and assign currentPage value directly as in example below, the additional search query is not issued to Elastisearch ...

 ```
public function setCurrentPage($currentPage)
    {
        $this->useDeprecatedCurrentPageBooleanArguments(func_get_args());

        //$this->currentPage = $this->filterCurrentPage($currentPage);
        $this->currentPage = $currentPage;

        $this->resetForCurrentPageChange();

        return $this;
    }
```

**Comment by merk** [comment]
This is a known flaw with the current paginator setup and will go away some point after 3.1 stable (maybe 3.2)
