### ISSUE TITLE
Change ES data on nested object changes automatically

### ISSUE THREAD

**Issue by developeryashraj** [FriendsOfSymfony/FOSElasticaBundle#715]
```
types:
                product:
                    mappings:
                        title:    { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string }
                        status:
                        brand.name:    { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string }
                        brand:
                          type: "nested"
                          properties:
                              status: ~
                    persistence:
                        driver: orm
                        model: MyBundle\Entity\Product\Product
                        provider: 
                          query_builder_method: customProductQueryBuilderElastica
                        listener: ~ 
                        finder: ~
```

This is my mappings for type product. **customProductQueryBuilderElastica** contains code which populates only products which have active status and have related brand status active. It is working perfectly if i change products from my admin. 

**what i want to do is when i change my brand status to inactive, all related products should be removed from ES.**

For that i have used brand as nested of product and created listener for it as [explained here] (http://stackoverflow.com/questions/21909763/symfony2-foselasticabundle-update-index-for-all-entities-related-to-the-entity-u) and now i am able to change brand status for every products in my ES automatically but i want to remove such products when brand status sets to inactive. **How can this be achieved in better way?**.

**Comment by merk** [comment]
Closing because it is to be handled in #681

**Comment by kasparsklavins** [comment]
Still an issue.
