### ISSUE TITLE
Serializer causes ModelToElasticaTransfomer to transform an empty document

### ISSUE THREAD

**Issue by pjdrevet** [FriendsOfSymfony/FOSElasticaBundle#716]
Hi,

When i populate my index, I indexed the full model (the entity) not the document returned by the transformer. Why ? I checked that one going well into the transfomer.
There are my config and my transformer class after.

My config is:

```
fos_elastica:
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    indexes:
        search:
            finder: ~
            types:
                project:
                   mappings:
                        name: { boost: 5 }
                        slug: { boots: 5 }
                        shortDescription: { boots: 3 }
                        tags:
                          type: "nested"
                          properties:
                            name: { boots: 5 }
                            slug: { boots: 5 }
                   persistence:
                        model_to_elastica_transformer:
                            service: plateforme_project.project_transformer_elastica
                        driver: orm # orm, mongodb, propel are available
                        model:  Plateforme\ProjectBundle\Entity\Project
                        provider: ~
                        finder: ~
                        listener: ~ # by default, listens to "insert", "update" and "delete"
```

And my transformer is:

class ProjectToElasticaTransformer implements ModelToElasticaTransformerInterface {

```
/* (non-PHPdoc)
 * @see \FOS\ElasticaBundle\Transformer\ModelToElasticaTransformerInterface::transform()
 */
public function transform($project, array $fields) {

    $identifier = $project->getId();

    $tags = array();


    foreach($project->getTags() as $tag){

        $nestedTag = array('name' => $tag->getName(), 'slug' => $tag->getSlug(), 'id' => $tag->getId());
        $tags[] = $nestedTag;
    }


    $values = array(
        'id' => $project->getId(),
        'name' => $project->getName(),
        'slug' => $project->getSlug(),
        'shortDescription' => $project->getShortDescription(),
        'user' => $project->getUser()->getUsername(),
        'tags' => $tags
    );

    // Crée le document à indexer
    $document = new Document($identifier);
    $document->setData($values);

    return $document;

}
```

}

**Comment by gxolin** [comment]
Same issue for me. Here's my config : 
““
fos_elastica:
	clients:
		default: { host: localhost, port: 9200 }
	serializer:
		callback_class: FOS\ElasticaBundle\Serializer\Callback
		serializer: serializer
	indexes:
		article:
			client: default
				types:
					ElasticaDocument:
						persistence:
							driver: orm
							model: MyBundle\Entity\Article
							elastica_to_model_transformer:
								service: mybundle.elasticatoarticle.transformer
							finder: ~
							listener: ~
							provider: ~
							model_to_elastica_transformer:
								service: mybundle.articletoelastica.transformer
						mappings:
							articleId
							articleTitle
							categoryId
							categoryTitle
							contenus:
								type: “nested”
““
Each elasticasearch row gives my correct 5 Transformed attributes, and all entity attributes.
Any thoughts ?

**Comment by merk** [comment]
Im sorry, I'm not following what the problem is here for you @gxolin - Can you please provide more information about what you're expecting and what actually happens? Is your problem with the elastica_to_model transformer or the model_to_elastica transformer?

@pjdrevet are you still having the same problem?

Could you please both paste the output of `composer show -i`.

**Comment by pjdrevet** [comment]
Hi, i don't solved my problem.
Currently all properties of my entity are indexed but when i am searching in my index, i am building my query with required fields.

Sorry for my english. 

Thereafter my composer description.

Best regards.


afarkas/html5shiv                               3.7.2
amazonwebservices/aws-sdk-for-php               1.6.3
avocode/form-extensions-bundle                  dev-master 1d2d41c
behat/transliterator                            v1.0.1
braincrafted/bootstrap-bundle                   v2.1.0
cedriclombardot/admingenerator-generator-bundle v1.1.3
cedriclombardot/twig-generator                  v1.0.0
components/bootstrap                            3.3.2
components/font-awesome                         4.3.0
components/jquery                               1.11.2
components/jqueryui                             1.11.2
craue/formflow-bundle                           2.1.5
cybernox/amazon-webservices-bundle              1.5.6
doctrine/annotations                            v1.2.3
doctrine/cache                                  v1.4.0
doctrine/collections                            v1.2
doctrine/common                                 v2.4.2
doctrine/data-fixtures                          v1.0.0
doctrine/dbal                                   v2.5.1
doctrine/doctrine-bundle                        v1.3.0
doctrine/doctrine-cache-bundle                  v1.0.1
doctrine/doctrine-fixtures-bundle               dev-master c5ff054
doctrine/inflector                              v1.0.1
doctrine/lexer                                  v1.0.1
doctrine/orm                                    v2.4.7
ee/dataexporter-bundle                          v0.4.2
egeloen/ckeditor-bundle                         2.5.2
egeloen/json-builder                            1.0.3
eko/feedbundle                                  dev-master 13b3c35
facebook/php-sdk                                v3.2.3
fpn/doctrine-extensions-taggable                v0.9.0
fpn/tag-bundle                                  dev-master 2cc70ca
friendsofsymfony/comment-bundle                 dev-master 2363b47
friendsofsymfony/elastica-bundle                v3.0.7
friendsofsymfony/facebook-bundle                1.3.0
friendsofsymfony/rest-bundle                    1.3.1
friendsofsymfony/user-bundle                    v1.3.5
gedmo/doctrine-extensions                       v2.3.11
genemu/form-bundle                              v2.2.2
gthm/rdf-bundle                                 dev-master 8cd7cd1
guzzle/guzzle                                   v3.8.1
h4cc/wkhtmltoimage-i386                         0.12.2.1
h4cc/wkhtmltopdf-i386                           0.12.2.1
hwi/oauth-bundle                                dev-master a9f88f3
idm-io/mangopay                                 dev-master 0cd3231
imagine/imagine                                 0.6.2
incenteev/composer-parameter-handler            v2.1.0
jdorn/sql-formatter                             v1.2.17
jms/metadata                                    1.5.1
jms/parser-lib                                  1.0.0
jms/serializer                                  0.16.0
jms/serializer-bundle                           0.12.0
jquery/jquery                                   1.11.0
kayue/kayue-wordpress-bundle                    v1.1.1
knplabs/gaufrette                               v0.1.8
knplabs/knp-components                          1.3.1
knplabs/knp-gaufrette-bundle                    v0.1.7
knplabs/knp-menu                                v1.1.2
knplabs/knp-menu-bundle                         v1.1.2
knplabs/knp-paginator-bundle                    2.4.1
knplabs/knp-snappy                              0.1.2
kriswallsmith/assetic                           v1.2.1
kriswallsmith/buzz                              v0.13
leafo/lessphp                                   v0.4.0
leaseweb/guzzle-bundle                          v1.0.2
liip/imagine-bundle                             dev-master 33440c2
liip/monitor-bundle                             2.0.3
liuggio/ExcelBundle                             v2.0.1
lunetics/locale-bundle                          v2.2.5
michelf/php-markdown                            1.4.1
mlpz/mailchimp-bundle                           dev-master f778d86
monolog/monolog                                 1.12.0
mopa/bootstrap-bundle                           v3.0.0-beta3
mopa/composer-bridge                            v1.3.1
mremi/bootstrap-bundle                          v3.0.2
mremi/contact-bundle                            dev-master c613aa2
nelmio/api-doc-bundle                           2.7.0
pagerfanta/pagerfanta                           v1.0.3
phpcollection/phpcollection                     0.4.0
phpoffice/phpexcel                              1.8.0
phpoption/phpoption                             1.4.0
predictionio/predictionio                       v0.6.3
predictionio/predictionio-bundle                dev-master 726112b
psr/log                                         1.0.0
robloach/component-installer                    0.0.12
ruflin/elastica                                 v1.3.4.0
sensio/distribution-bundle                      v2.3.8
sensio/framework-extra-bundle                   v3.0.4
sensio/generator-bundle                         v2.3.5
siphoc/pdf-bundle                               1.2.3
sonata-project/intl-bundle                      dev-master 292fad9
stephpy/timeline                                v1.0.3
stephpy/timeline-bundle                         dev-master 35250da
stfalcon/tinymce-bundle                         dev-master 758c199
stof/doctrine-extensions-bundle                 dev-master 2ff8473
swiftmailer/swiftmailer                         v5.3.1
symfony/assetic-bundle                          v2.6.1
symfony/css-selector                            v2.3.24
symfony/dom-crawler                             v2.3.24
symfony/finder                                  v2.3.24
symfony/monolog-bundle                          v2.7.1
symfony/swiftmailer-bundle                      v2.3.8
symfony/symfony                                 v2.6.3
twbs/bootstrap                                  v3.0.0
twig/extensions                                 v1.0.1
twig/twig                                       v1.18.0
vich/uploader-bundle                            v0.10.0
videlalvaro/php-amqplib                         v2.4.1
white-october/pagerfanta-bundle                 v1.0.2
willdurand/jsonp-callback-validator             v1.1.0
willdurand/negotiation                          1.3.4
zendframework/zend-escaper                      2.3.4
zendframework/zend-feed                         2.3.4
zendframework/zend-http                         2.3.4
zendframework/zend-loader                       2.3.4
zendframework/zend-servicemanager               2.3.4
zendframework/zend-stdlib                       2.3.4
zendframework/zend-uri                          2.3.4
zendframework/zend-validator                    2.3.4
zendframework/zenddiagnostics                   v1.0.3

**Comment by merk** [comment]
Does your custom transformer get called? Can you put a var_dump or xdebug_break call inside and see that the $document is actually made?

**Comment by pjdrevet** [comment]
My transformer is called.

D:\data\workspace\workspace-crowdfunding\cafi-success>php app/console fos:elastica:populate
Resetting search
object(Elastica\Document)#1528 (6) {
  ["_data":protected]=>
  array(7) {
    ["id"]=>
    int(1)
    ["project_tags"]=>
    string(17) "Bandes dessin├⌐es"
    ["name"]=>
    string(18) "Mon livre de poche"
    ["slug"]=>
    string(18) "mon-livre-de-poche"
    ["shortDescription"]=>
    string(257) "Le Lorem Ipsum est simplement du faux texte employ├⌐ dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les ann├
⌐es 1500, quand un peintre anonyme assembla ensemble des morceaux de texte"
    ["user"]=>
    string(3) "pej"
    ["tags"]=>
    array(0) {
    }
  }
  ["_docAsUpsert":protected]=>
  bool(false)
  ["_autoPopulate":protected]=>
  bool(false)
  ["_upsert":protected]=>
  NULL
  ["_params":protected]=>
  array(3) {
    ["_id"]=>
    int(1)
    ["_type"]=>
    string(0) ""
    ["_index"]=>
    string(0) ""
  }
  ["_rawParams":protected]=>
  array(0) {
  }
}
Populating search/project, 100.0% (1/1), 1 objects/s (RAM : current=18Mo peak=18Mo)
Refreshing search

**Comment by gxolin** [comment]
composer for elastica : (full composer a bit heavy on my project)
````
friendsofsymfony/elastica-bundle     v3.0.8             Elasticsearch PHP integration for your Symfony2 project using Elastica
````

my ModelToTransformer : 
````
    public function transform($doc, array $fields)
    {
        $identifier = $doc->getId();
        $values = array(
            'id' => $identifier,
            'name' => 'foo',
            'contents' => ['foo', 'bar'],
        );
        $document = new Document($identifier,$values);
var_dump($document);
        return $document;
    }
````

my post-transformer dump : 
````
object(Elastica\Document)#1131 (6) {
  ["_data":protected]=>
  array(3) {
    ["id"]=>
    int(2409)
    ["name"]=>
    string(3) "foo"
    ["contents"]=>
    array(2) {
      [0]=>
      string(3) "foo"
      [1]=>
      string(3) "bar"
    }
  }
  ["_docAsUpsert":protected]=>
  bool(false)
  ["_autoPopulate":protected]=>
  bool(false)
  ["_upsert":protected]=>
  NULL
  ["_params":protected]=>
  array(3) {
    ["_id"]=>
    int(2409)
    ["_type"]=>
    string(0) ""
    ["_index"]=>
    string(0) ""
  }
  ["_rawParams":protected]=>
  array(0) {
  }
}
````
populating the elastica searchDB :
````
php app/console fos:elastica:populate
Resetting searchDB
string(17) "Elastica\Document"
string(17) "Elastica\Document"
Populating searchDB/ElasticaDocument, 66.7% (2/3), 2 objects/s (RAM : current=26Mo peak=28Mo)
Refreshing searchDB
````
it's still all good here ! (i replaced the dump($document) by dump(get_class($document)) on my transformer,  and he get called during the elastica:populate).


The last part only is strange. This happen when i curl elastica : 
````
curl -GET 'http://localhost:9200/searchDB/_search?pretty=true&q=*:*'
{
    "took" : 5,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
        "_index" : "article",
      "_type" : "ElasticaDocument",
      "_id" : "2409",
      "_score" : 1.0,
      "_source":{"blocks":[ /* ALL MY CONTENT HIERARCHY */ ],"categories":[/* MY SOURCE CATEGORIES */],"id":2409,"name":/* SOURCE NAME */}
    }, {
        "_index" : "kartable",
      "_type" : "ElasticaDocument",
      "_id" : "2562",
      "_score" : 1.0,
      "_source":{"blocks":[ /* ALL MY CONTENT HIERARCHY */ ],"categories":[/* MY SOURCE CATEGORIES */],"id":2562,"name":/* SOURCE NAME */}
    } ]
  }
}
````

TL-DR: instead of populating the elasticsearch database with my transformed 'foo' entities, the search db contains my full pre-transform entity with all dependencies !

**Comment by gxolin** [comment]
@pjdrevet, @merk, 
I finaly found it ! just comment those lines in your config : 
````
#    serializer:
#        callback_class: FOS\ElasticaBundle\Serializer\Callback
#        serializer: serializer
````

**Comment by merk** [comment]
Sorry I'm not sure. I dont use the serializer. If not I'm happy to accept a PR enabling this if it isnt already possible.

**Comment by gxolin** [comment]
Referring to the doc it's possible : 
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/serializer.md
This line describe the serializer :
````
fos_elastica:
    serializer: ~
```` 
and this one enable it for a type : 
````
fos_elastica:
    indexes:
        search:
            types:
                user:
                    serializer:
```` 
But it seems to use by default the serializer if you describe it, without the ````types: {user:  { serializer: {}}}```` line. A bit confusing :) 
Anyway, thanks for your help !

**Comment by pjdrevet** [comment]
Thanks for your help !

I test tonight.

Best regards.

**Comment by pjdrevet** [comment]
@gxolin 

It's good.

Thanks a lot.
