### ISSUE TITLE
Auto-refresh option

### ISSUE THREAD

**Issue by pkruithof** [FriendsOfSymfony/FOSElasticaBundle#723]
Refreshing the index is done periodically according to the Elasticsearch documentation. When you run functional tests though, you want fixtures to be available immediately. It would be handy if the bundle provides an `auto-refresh`option of some sort to do this for you.

**Comment by merk** [comment]
I believe this is out of scope of this bundle. Either the code handling your scenario should call this refresh method or your elasticsearch installation should be configured to have a different refresh interval.

It should be possible to override the listener for your types to add this in production for whatever reason it is required.

**Comment by pkruithof** [comment]
I understand and I agree that it's not really the bundle's responsibility (though it would be more convenient to use). However I do feel it's a good idea to document that in this sentence:

> When using the providers and listeners that come with the bundle, any new or modified object will be indexed automatically

automatically does not imply immediately, or something like that. What do you think?

**Comment by merk** [comment]
I think its a good idea, but it might be worth expanding on automatically and if there is documentation on indexing delays in ElasticSearch's own documentation that we could link to that?

**Comment by pkruithof** [comment]
Here's the link to the ES section about it: http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/near-real-time.html#refresh-api
