### ISSUE TITLE
Catchable fatal error: Argument 1 passed to FOS\ElasticaBundle\Repository::__construct() must be an instance of FOS\ElasticaBundle\Finder\PaginatedFinderInterface, instance of Doctrine\ORM\EntityManager given, called in C:\xampp\htdocs\symfony-bootstrap\vendor\doctrine\orm\lib\Doctrine\ORM\EntityMan     ager.php on line 689 and defined in C:\xampp\htdocs\symfony-bootstrap\vendor\friendsofsymfony\elastica-bundle\Repository.php on line 17

### ISSUE THREAD

**Issue by piux** [FriendsOfSymfony/FOSElasticaBundle#735]
greetings, im trying to make a custom repository.

the documentation is pretty straight forward but i still dont understand how it works, im getting this error  ´The service definition "fos_elastica.manager" does not exist.´.

this is my configuration so far:
    //app/config.yml
>     fos_elastica:
>         clients:
>             default: { host: localhost, port: 9200 }
>         indexes:
>              sava:
>                 client: default
>                 types:
>                     blog:
>                         mappings:
>                             id:
>                                 type: integer
>                             body : ~
>                             title : ~
>                             tags: ~
>                         persistence:
>                             identifier: id
>                             driver: orm
>                             model: sava\BlogBundle\Entity\TblPost
>                             finder: ~
>                             provider: ~
>                             listener: ~
>                             repository: sava\BlogBundle\Entity\TblPostRepository

this is my controller action:

    namespace sava\BlogBundle\Controller;
    
    //custom querys
    use FOS\ElasticaBundle\Manager\RepositoryManager;
    use FOS\ElasticaBundle\Repository;
    //
    use Symfony\Component\DependencyInjection\ContainerBuilder;
    
    class TblPostController extends Controller
    {
            public function getPostAction(Request $request)
        {   
             $container = new ContainerBuilder();
             $repositoryManager = $container->get('fos_elastica.manager');
    
             $repository = $repositoryManager->getRepository('BlogBundle:TblPost');
   
            $items2 = $repository->matchExact($categoria,$searchQuery );
    
    
             return $this->render('savaBlogBundle:TblPost:index.html.twig', array(
                        'results' => $items2, 'entities' => $items2
            ));
        }

this is my post repository:

    <?php
    
    namespace sava\BlogBundle\Entity; //Changed this typo.
    
    use Doctrine\ORM\Mapping as ORM;
    
    use FOS\ElasticaBundle\Repository;
    
    class TblPostRepository extends FOS\ElasticaBundle\Repository
    {
        public function matchExact($campo, $searchQuery) {
            
            
             //$finder = $this->get('fos_elastica.finder.sava.blog');
             
            $query = new Query();
            if($searchQuery=='')
            {
                $innerQuery = new Query\MatchAll();
            }
            else{
               $innerQuery = new Query\Match();
            $innerQuery->setField( $campo  , array('query' => $searchQuery));
            }
            $query->setQuery($innerQuery);
            $query->setSize(1000000);
            $query->setExplain(true);
            
            return $this->find($query);
        }  
    }

and since im using yml this is my tblpost.orm, i did generate my entities.

whenever i do the get postaction it throws me that it cant find the container, and i dont see an example in how to properly intiaze it, also is this is how you make a custom query?

**Edited typos** in config and searchrepository.

**Comment by BonnieDoug** [comment]
Did you ever find a real fix for this? I'm getting the same error..

**Comment by ekyna** [comment]
@BonnieDoug see answers to the op question [on stackoverflow](http://stackoverflow.com/questions/26807310/creating-custom-repository-fos-elastic-search#answers).
