### ISSUE TITLE
Is _routing working ?

### ISSUE THREAD

**Issue by fancyweb** [FriendsOfSymfony/FOSElasticaBundle#745]
Is the `_routing` option supported / working ?

I've been tryng to use it for several hours, but if I add the `_routing` option with a `path` parameter for a child / parent / grandparent relation (cf http://www.elasticsearch.org/blog/customizing-your-document-routing/) I'm getting the following error : 

`  [Elastica\Exception\ResponseException]                                                                                
  MapperParsingException[The provided routing value [72] doesn't match the routing key stored in the document: [null]]`

Note that 72 is not the good supposed value. Whatever I put for the `path` parameter, the same number 72 always appears which is the id of the `_parent` parameter. From what I understood it should be the id of the grandparent which is specified in the `path` value.

If I inject directly the `_routing` parameter in the Transformer->transform() method manually for one test document `$document->setParam('_routing', 13);`, then it works fine and my queries on the index with hasChild() filter work well.

Anyone can help me to figure this out please ?

**Comment by merk** [comment]
The transformer now dispatches a POST_TRANSFORM event that will let you modify the document as it is being transformed which should allow you to set this parameter as you desire it.
