### ISSUE TITLE
Aggregation and GeoBounding filter

### ISSUE THREAD

**Issue by Merk87** [FriendsOfSymfony/FOSElasticaBundle#751]
Hi guys.

I was playing around with ElasticaBundle for now a few days and now I'm trying to build a query with Aggregations using Geohash and GeoBoundings, but I don't see how to add of is it possible using ElasticaBundle.

Any recommendation/help?

**Comment by Merk87** [comment]
Hi.

Sorry for the late reply, but basically here is what I did to accomplish the task: 

First of all I add to my entities a function to generate the coordenates in a simple string, with the format:
"51.9244201, 51.9244201".

Then in the configuration I pass as geo_point:
```yml
users:
      mappings:
            country: ~
                    location:
                    type: geo_point
```

Well and to put this on practise basically I'd created a dynamic query using both FOSElastica and Elastica.io:

```php
 protected function searchProfiles($searchTerm, $maxResults, $offset, $clubId = null)
    {
        $searchCoords1 = $this->getRequest()->query->get('point1');
        $searchCoords2 = $this->getRequest()->query->get('point2');

        $finderUsers = $this->container->get('fos_elastica.finder.search.users');
        $setFilter = false;

        $boolFilter = new \Elastica\Filter\Bool();
        $boolFilter->addMust(new \Elastica\Filter\GeoBoundingBox('location', array($searchCoords1, $searchCoords2)));

        $queryUsers->setFilter($boolFilter);
        $userResults = $finderUsers->findPaginated($queryUsers);
        $userResults->setMaxPerPage($maxResults);
        $userResults->setCurrentPage(1);

        return $this->pagerFantaToArray($userResults);

    }
```

This return me a very accurated range of values and when I pass to the front end I can group it and make the updates on the zooming, etc.

Hope this is helpful for someone.

**Comment by XWB** [comment]
Thanks.
