### ISSUE TITLE
Support for msearch

### ISSUE THREAD

**Issue by yellow1912** [FriendsOfSymfony/FOSElasticaBundle#752]
I'm not sure if this issue is brought up already, but recently I have come to need the ability to run multiple search queries in 1 request. 

Elastic supports _msearch and Elastic does have the Elastica\Multi. Would be nice to somehow allows using it via FOSElastica. Right now I have to create a custom service to handle this.

**Comment by varloc2000** [comment]
@yellow1912 Could you please share the way you've implemented a custom service to handle _msearch with foselastica?
