### ISSUE TITLE
Add support for defining types

### ISSUE THREAD

**Issue by yellow1912** [FriendsOfSymfony/FOSElasticaBundle#756]
I would like to be able to define the list of document types to be searched. Right now elastica does allow us to add types to index but FosBundle does not expose those methods. Would be nice if this bundle expose elastica object at some point, perhaps via event dispatcher to be modified.

**Comment by merk** [comment]
What exactly do you want to do? The configuration at the moment is static and built during container compilation and you wont be able to hook into that process at runtime.

There have been some changes in the last few months to expose the configuration through a dedicated Configuration class but it isnt enough at the moment to define types at runtime. If you'd like to continue work on allowing runtime configuration I'd be happy to review a PR.
