### ISSUE TITLE
Nested type when using JMS serializer

### ISSUE THREAD

**Issue by runcom** [FriendsOfSymfony/FOSElasticaBundle#759]
Does the bundle support defining a nested type on a class field when using jms serializer? I know I can just define `mappings` but I was wondering if it was supported

**Comment by merk** [comment]
I dont believe so. The nested type requires additional information.

**Comment by Yaug** [comment]
Hi.
Sorry for commenting on an old and closed ticket, but Is this now possible to use nested objects and jmsserializer ? 
If not, is there an alternative solution ?

Thank you
