### ISSUE TITLE
Where stores FosElasticaBundle the indexes? 

### ISSUE THREAD

**Issue by Slowwie** [FriendsOfSymfony/FOSElasticaBundle#763]
Hey guys, 

I populated a simple index. And there was something about ram size written. Is it not like lucene that stores it in the file system? Is this not very ram-exhausting ? Is FosElasticaBundle the right way to build a simple ajax searche or is it to heavy for it ?

greetings Michael

**Comment by merk** [comment]
The RAM notification is about usage while populating the indexes. When your number of documents or entities grows this ram usage grows. It is for debugging purposes.
