### ISSUE TITLE
Advanced Query error using Elastica_Query_Text() - No query registered for [text]]; }]

### ISSUE THREAD

**Issue by tomasliachovskis** [FriendsOfSymfony/FOSElasticaBundle#767]
I use example from : 

https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/2.1.x/README.md#example-of-advanced-query

Code: 

        $finder = $this->container->get('fos_elastica.finder.site.company');
        $boolQuery = new \Elastica_Query_Bool();

        $fieldQuery = new \Elastica_Query_Text();
        $fieldQuery->setFieldQuery('artText', 'text');
        $fieldQuery->setFieldParam('artText', 'analyzer', 'my_analyzer');
        $boolQuery->addShould($fieldQuery);
        $data = $finder->find($boolQuery);

Configuration: 

fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        site:
            settings:
                index:
                     analysis:
                        analyzer:
                            my_analyzer:
                                type: snowball
                                tokenizer: my_tokinizer
                                filter   : [lowercase, my_ngram]
                        filter:
                            my_ngram:
                                type: "nGram"
                                min_gram: 1
                                max_gram: 50
                        tokenizer:
                            my_tokinizer:
                                type: "nGram"
                                min_gram: 1
                                max_gram: 50
            types:
                company:
                    mappings:
                        artText: { boost: 10, analyzer: my_analyzer}
                        artSeoKey:
                        artSeoDesc:
                        artUrl:
                    persistence:
                        identifier: artId
                        driver: orm
                        model: Catalog\WebBundle\Entity\ComArticles
                        provider:
                        finder:

What I get: 

SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[qtEeqhjbTyWPoPlp9mhwGQ][site][0]: SearchParseException[[site][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"should":[{"text":{"artText":{"query":"I","analyzer":"my_analyzer"}}}]}}}]]]; nested: QueryParsingException[[site] No query registered for [text]]; }{[qtEeqhjbTyWPoPlp9mhwGQ][site][1]: SearchParseException[[site][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"should":[{"text":{"artText":{"query":"I","analyzer":"my_analyzer"}}}]}}}]]]; nested: QueryParsingException[[site] No query registered for [text]]; }{[qtEeqhjbTyWPoPlp9mhwGQ][site][2]: SearchParseException[[site][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"should":[{"text":{"artText":{"query":"I","analyzer":"my_analyzer"}}}]}}}]]]; nested: QueryParsingException[[site] No query registered for [text]]; }{[qtEeqhjbTyWPoPlp9mhwGQ][site][3]: SearchParseException[[site][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"should":[{"text":{"artText":{"query":"I","analyzer":"my_analyzer"}}}]}}}]]]; nested: QueryParsingException[[site] No query registered for [text]]; }{[qtEeqhjbTyWPoPlp9mhwGQ][site][4]: SearchParseException[[site][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"bool":{"should":[{"text":{"artText":{"query":"I","analyzer":"my_analyzer"}}}]}}}]]]; nested: QueryParsingException[[site] No query registered for [text]]; }]

**Comment by merk** [comment]
This is a support request better suited to the Elastica repository as nothing FOSElasticaBundle is doing relates specifically to the error.

MY suggestion would be to build this query from the command line first, then try to mimic the same structure by json_encoding the $boolQuery object.
