### ISSUE TITLE
[Regression] The configuration refactoring broke the parent child mapping

### ISSUE THREAD

**Issue by stof** [FriendsOfSymfony/FOSElasticaBundle#774]
After https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/629, the transformer does not receive the ``_parent`` configuration anymore, and so does not set the parent when transforming the entity to a document, thus breaking the indexation

**Comment by merk** [comment]
It looks like the parent/child mapping creation is tested but the indexing of such a relationship isnt. https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Tests/Functional/app/Basic/config.yml#L92

**Comment by stof** [comment]
The issue is that the Transformer only receives properties, currently: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/1bf59d5b66c4e2b4e20b88e83899208dc8591e8a/DependencyInjection/FOSElasticaExtension.php#L399

The transformer is able to handle the special ``_parent`` key in the data it receives, but it does not receive it currently.

**Comment by stof** [comment]
Note that the handling of ``_parent`` in the transformer itself is also tested. The issue is only in the configuration layer

**Comment by stof** [comment]
here you go
