### ISSUE TITLE
The routing feature is broken

### ISSUE THREAD

**Issue by stof** [FriendsOfSymfony/FOSElasticaBundle#775]
The configuration allows to configure a path for ``_routing`` and sends it to ES when configuring the mapping. But the transformer never gets this info, and so does not call ``setRouting`` on the document.

**Comment by merk** [comment]
I dont use this feature - could you please provide example mappings and expected results stored in ElasticSearch so I can increase test coverage?

**Comment by stof** [comment]
I'm wrong here actually: we support the routing feature when you use the path to ask ES to use an existing field as routing key: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-routing-field.html#_path
We don't support providing it separately from the document fields (by setting ``_routing`` directly in the document). But this is not a bug. So I'm closing this issue

**Comment by merk** [comment]
It should be possible to use the new POST_POPULATE event to provide a _routing key directly now.

**Comment by merk** [comment]
(available in 3.1-dev)
