### ISSUE TITLE
Documentation is lacking - Find method not working compared to Command file

### ISSUE THREAD

**Issue by chrisciampoli** [FriendsOfSymfony/FOSElasticaBundle#781]
I've been working with this bundle for about a week now, and find the examples and documentation lacking.  Case in point is the "Usage" page.....

While your example seems simple enough, there would appear to be more going on behind the scenes then meets the eye.  Let me present you with the issue I'm seeing on my end.

``` php
$finder = $this->container->get('fos_elastica.finder.videos.video');
$results = $finder->find('wiggles');
```

This code above returns 0 results.  I get nothing back in the way of a results object, nor array results.

HOWEVER, when I used the console command to search for this same criteria I was able to pull back results.  That got me to digging, and after ripping apart the Command file, I decided to try this bit in my controller for giggles.

``` php
$index = $this->container->get('fos_elastica.index_manager')->getIndex("videos");
$type  = $index->getType("video");
$query = Query::create('wiggles');
$results = $type->search($query);
```

And what do you know, I got back my results!

The point of this is, that while I was able to eventually get some kind of jerry-rigged way of returning my results, it would be nice if the documentation laid out in better detail, what else the FIND method requires in the way of setup.  Obviously the simple -> find example you have is just not cutting it.

**Comment by aequasi** [comment]
+1

**Comment by merk** [comment]
The usage section of the documentation could use some love, I'd even prefer us to move towards linking to Elastica's own documentation and not providing usage instructions beyond how to retrieve an index or a type from the container.

I'd appreciate a PR.
