### ISSUE TITLE
Implementation TopHits Aggregation

### ISSUE THREAD

**Issue by Mkrc** [FriendsOfSymfony/FOSElasticaBundle#784]
Hi,

I couldn’t find an implementation TopHits Aggregation for ElasticaBundle
is there any plan to add this feature?

**Comment by ewgRa** [comment]
https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Aggregation/TopHits.php

**Comment by merk** [comment]
Aggregations should be available now in 3.1-dev in pagination situations which should make this available. If something specific is unavailable please open a new issue or a PR
