### ISSUE TITLE
Decode $data variable --- Not a bug

### ISSUE THREAD

**Issue by dbhattacharjee** [FriendsOfSymfony/FOSElasticaBundle#785]
Hi Guys,

In public function request($path, $method = Request::GET, $data = array(), array $query = array()) {} function of Client.php file you are passing $data variable.
Is there any way to json_decode this variable & print the underlying object/array structure.

**Comment by merk** [comment]
Why?

Our Elastica\Client implementation includes a logger that will log requests sent. Alternatively for debugging you could use xdebug_break() with an IDE that supports remote debugging.
