### ISSUE TITLE
setExistence() and setNullValue() methods on Missing Filter

### ISSUE THREAD

**Issue by Arrogance** [FriendsOfSymfony/FOSElasticaBundle#786]
Hi,

I'm using the bundle on a project with elements that can have a deletedAt value, and I don't want to show these results on elastic queries.

I took a look at elastica documentation, and I saw the Missing filter class, that would help me with my requirement, but these methods are not available in the latest version of the bundle (at least on dev-master branch).

Elastica\Filter\Missing doc: http://elastica.io/api/classes/Elastica.Filter.Missing.html

It 's possible to add these new methods to the bundle? Can I do the search with actual bools and restrictions?

Thanks in advance.

**Comment by ewgRa** [comment]
This is what are you looking for?
https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Filter/Missing.php

You need look to Elastica, not to FOSElasticaBundle. Bundle it is just "connector" between Elastica lib and Symfony.
