### ISSUE TITLE
Install with elasticsearch-1.4.2

### ISSUE THREAD

**Issue by ewgRa** [FriendsOfSymfony/FOSElasticaBundle#787]
I want use bundle with elasticsearch 1.4.2. For this I need install "ruflin/elastica": "v1.4.2.0" in composer.

But when I try install "friendsofsymfony/elastica-bundle": "~3.0" I have "friendsofsymfony/elastica-bundle v3.0.7 requires ruflin/elastica >=0.90.10.0, <1.4-dev -> no matching package found."

Have same error when I try install "ruflin/elastica": "1.4.x-dev".

Is elastica-bundle can work with elastica v1.4.2.0?

**Comment by merk** [comment]
3.0.8 now allows Elastica 1.4
