### ISSUE TITLE
QueryBuilder service

### ISSUE THREAD

**Issue by XWB** [FriendsOfSymfony/FOSElasticaBundle#790]
Elastica 1.4.2 comes with a QueryBuilder:

http://elastica.io/2015/01/25/release-v1-dot-4-2-dot-0/
http://elastica.io/getting-started/search-documents.html

What would be the best way to implement a QueryBuilder service while still supporting older Elastica versions?

**Comment by merk** [comment]
Current roadmap (i should probably update the roadmap issues)

3.1 - find a solution to make the current paginators work "well enough"
3.2 - Introduce a new bundle API that matches significantly closer to using Elastica by itself and deprecate the current paginator methods (as the new method will use built in support for Elastica in the paginator libraries)

For now, the QueryBuilder looks compatible with the Query class ($query->setQuery($qb->...)) so no work needs to be done to support the QB
