### ISSUE TITLE
Memory leak in populate

### ISSUE THREAD

**Issue by djlemmings** [FriendsOfSymfony/FOSElasticaBundle#791]
Hello,

I've been using foselasticabundle for more than a year, the memory leak that used to be in the populate was fixed a long time ago (around last summer) and I use the release 3.0.5 with no problems until now.

But I wanted to try to upgrade today, so I updated to the last release (3.0.8) and it seems that the memory leak is back...

Here is the command I use:

`php app/console fos:elastica:populate --index=cph_full --no-reset --type=photo`

And it rapidly raise the memory usage over 100 MB, on a large database it can even raise to more than 1 GB...

On the 3.0.5 I have no memory issue.

Also, when I add the "--no-debug" option on the 3.0.8, the memory keeps around 40 MB, and never raise to 100 MB.

Maybe there is something wrong in the debug not flushed somewhere?

Best regards.

**Comment by merk** [comment]
Population should be done in prod env with --no-debug. When debug mode is enabled, the logger is enabled by default (which is where the memory usage is coming from).

If you're seeing memory usage balloon in prod/no-debug we'll investigate that.

**Comment by djlemmings** [comment]
Didn't knew that but totally makes sense.

Thanks.
