### ISSUE TITLE
AutoUpdate not working if listener insert set to false 

### ISSUE THREAD

**Issue by samuelvi** [FriendsOfSymfony/FOSElasticaBundle#796]
I had a lot of problems with this configuration:

listener:
    immediate: true
    insert: false
    update: true
    delete: true

If only worked if I deleted the immediate and insert values, or set insert: true.
It worked before setting filters and tokenizers for my index/type.
Anyone knows what could happen?

This issue is a bit like #741.

Thanks a lot!

**Comment by merk** [comment]
immediate:true is not recommended anymore.

As for the rest, I'm going to need more information. Does the listener fire on update? What is going on inside the listener when you persist/flush an object?

**Comment by samuelvi** [comment]
Hi,
I tried to write a Listener for postUpdate and never fired I'm afraid :(


I

**Comment by merk** [comment]
I cant see what the issue is without more information / a reproducible test case. Please remove immediate:true and try again.

**Comment by samuelvi** [comment]
Thanks Tim,
I'll have a look.
Thanks a lot for your help, the bundle is really great, honestly!
Regards,

  Samuel

2015-03-11 11:39 GMT+01:00 Tim Nagel <notifications@github.com>:

**Comment by raphox** [comment]
@samuelvi Do you solved the problem?

**Comment by samuelvi** [comment]
Hi,
I managed mappings ignoring the parameter and everything went find.
Thanks a lot.

Samuel
