### ISSUE TITLE
LogicException, Progress Bar in the command line

### ISSUE THREAD

**Issue by ychadwick** [FriendsOfSymfony/FOSElasticaBundle#800]
When using the command fos:elastica:populate 
![screen shot 2015-02-24 at 16 15 19](https://cloud.githubusercontent.com/assets/664349/6352146/bf8d1c04-bc40-11e4-92a7-09d9fca37e98.png)
The problem seems to be on line 171 vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php

```php
$progress->advance($increment);
```
instead of something like this which would calculate the number of results based on the percentage

```php
$progress->advance($totalObjects*($increment/100));
```
This error stops the population of further objects

**Comment by merk** [comment]
Closing as it is already being discussed here: https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/793
