### ISSUE TITLE
Seeking Propel maintainer

### ISSUE THREAD

**Issue by Lionel09** [FriendsOfSymfony/FOSElasticaBundle#801]
I'm using Propel1 with this bundle and have troubles trying to use the finder searching the full index.

This piece of code in the `transform` method is incompatible with the PropelCollection:

```
            $transformed[$type] = array_combine(
                array_map(
                    function($o) use ($identifierGetter) {
                        return $o->$identifierGetter();
                    },
                    $transformedObjects
                ),
                $transformedObjects
            );
```

If I replace with this code, it's ok:

```
            foreach($transformedObjects as $object) {
                $transformed[$type][$object->$identifierGetter()] = $object;    
            }
```

No time for PR, but just want to tell it if someone is interested!

**Comment by merk** [comment]
Propel support is no longer maintained. Unless someone using it provides PRs for updates it will remain as is.

**Comment by StudioEcho** [comment]
OK, so if I have some time, I'll try to make some PRs to keep Propel support compatible with this bundle.

**Comment by Tobion** [comment]
Closing due to #1354
