### ISSUE TITLE
LogicException You can't advance the progress bar past the max value.

### ISSUE THREAD

**Issue by milos-ilic** [FriendsOfSymfony/FOSElasticaBundle#802]
Hello,

I'm getting logic exception when I want to repopulate indexes.

app/console fos:elastica:populate

 0/3 [>---------------------------]   0%
%message%
                                                          
  [LogicException]                                        
  You can't advance the progress bar past the max value.  
                                                          
fos:elastica:populate [--index[="..."]] [--type[="..."]] [--no-reset] [--offset="..."] [--sleep="..."] [--batch-size="..."] [--ignore-errors]

Firstly I have error message You must start the progress bar before calling setCurrent()., but then I have updated bundle and now I'm getting "You can't advance the progress bar past the max value."

composer show -i
shows: 
friendsofsymfony/elastica-bundle         dev-master 3c87cc1 Elasticsearch PHP integration for your Symfony2 project using Elastica

and in composer.json i have the following line:

        "friendsofsymfony/elastica-bundle": "dev-master",

I try to update elastica-bundle bundle using command line:
composer update friendsofsymfony/elastica-bundle

Any help would be appreciated. Thanks.

**Comment by merk** [comment]
There is a compatibility problem with symfony 2.5 and this bundle's unstable 3.1-dev branch. Either upgrade to symfony >= 2.6 or downgrade this bundle to ~3.0@stable until I have a chance to work out what i want to do.

See #792

**Comment by milos-ilic** [comment]
Many thanks!
