### ISSUE TITLE
Logger Closure used improperly on index errors - obfuscates true error

### ISSUE THREAD

**Issue by jmcclell** [FriendsOfSymfony/FOSElasticaBundle#803]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Doctrine/AbstractProvider.php#L70

When one of these exceptions is caught, it attempts to use the logger closure to log the exception. Unfortunately, the logger closure, defined [here](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Command/PopulateCommand.php#L164) is not meant for this type of usage. Instead of seeing the actual exception or its message, one is greeted with a closure error due to the second parameter missing.

I am not certain what behavior should actually be expected here so I'm not providing a fix just yet. Using the progress bar, I don't see a good way of logging exception messages like this without refactoring the logger or by creating a separate error logger.

**Comment by merk** [comment]
Handled in #815
