### ISSUE TITLE
RetryOnConflict

### ISSUE THREAD

**Issue by royraider** [FriendsOfSymfony/FOSElasticaBundle#807]
Hello,
I have problems with my index, after a populate everything is right, but in times some elements start missing, even worst: my website start to throw errors like this one:
```
[2015-03-03 23:46:36] request.CRITICAL: 
Uncaught PHP Exception Elastica\Exception\Bulk\ResponseException:
"Error in one or more bulk request actions: update: /app/type/2 caused
VersionConflictEngineException[[index][3] [type][2]: version conflict, current [752], provided [751]] "
at /var/www/App/vendor/ruflin/elastica/lib/Elastica/Bulk.php line 395
```

I found out the error was caused by a double update. But I found I could fix it by a force update thanks to "retryOnConflict". (https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Client.php#L24)

Do I have a way to set it in my config, does someone already used/set this ? Do you have another solution to my problem ?

Thanks a lot for your help !

**Comment by merk** [comment]
This looks like a concurrency problem where one visitor updates a record while another beat them to the punch.

What is the full stack trace of the exception? Which process specifically causes it to occur?

There is no way to set this property right now but a PR would be appreciated

**Comment by royraider** [comment]
Sorry I totally forgot this issue !
We just stopped to use the default "onUpdate" .
I think there was situations where our objects were "updated" multiple times in a short time and that was the problem.

Now we have no problem anymore, we update an object only when it's really matter. :)

**Comment by vadim2404** [comment]
I catched the same issue

RetryOnConflict has been added to ruflin/elastic since 2013 (https://github.com/ruflin/Elastica/pull/629/files). It will be good to configure the option at bundle.
