### ISSUE TITLE
Value in lowercase

### ISSUE THREAD

**Issue by pmithrandir** [FriendsOfSymfony/FOSElasticaBundle#810]
Hello,

I added a property of my doctrine object named theme.

In my database, they have all Capital letter in them.
In Head, I see capital letter also on them.

But when I'm looking for all my objects with a filter on this value, I must give the value in lowercase, like if elastic search was actually containing the value in lowercase instead of the original one.

Is it something normal ?

Took me 8 hours to figure out by mistaes that actually the value expected had to be in lowercase to match.

Best regards,
Pierre

**Comment by merk** [comment]
Is the value indexed in ElasticSearch as uppercase or lowercase? What does your search query look like?

Use something like ElasticSearch Head plugin to browse the data and see what is actually indexed.

**Comment by pmithrandir** [comment]
Hello,

my query is like that
```
{"query":{"filtered":{"query":{"match_all":{}},"filter":{"term":{"theme":"economie"}}}},"size":50}
```

In my database table, the value of theme is : Economie
In Head, it's displayed : Economie
But if I do the query with this value, it doesn't work. i have to use the lowercase value.

Here is my config file : 
```
fos_elastica:
    clients:
        default: { host: %es_host%, port: %es_port% }
#    serializer:
#        callback_class: FOS\ElasticaBundle\Serializer\Callback
#        serializer: serializer
    indexes:
        jaiuneidee:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_french_analyzer:
                                type: custom
                                tokenizer: letter
                                filter: ["asciifolding", "lowercase", "french_stem", "stop_fr"]
                        filter:
                            stop_fr:
                                type: "stop"
                                stopwords: ["l", "m", "t", "qu", "n", "s", "j", "d"]
            types:
                Idee:
                    mappings:
                        id:
                            type: integer
                        updatedAt :
                            type : date
                        lastAction :
                            type : date
                        theme : ~
                        localisations: ~
                        localisationsNiveau0: ~
                        localisationsNiveau1: ~
                        localisationsNiveau2: ~
                        localisationsNiveau3: ~
                        isVisible :
                            type : boolean
                        countCommentaires:
                            type: integer
                        title : { analyzer: custom_french_analyzer }
                        description : { analyzer: custom_french_analyzer }
                        content : { analyzer: custom_french_analyzer }
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model:  JaiUneIdee\SiteBundle\Entity\Idee
                        provider: ~
                        listener: ~ # by default, listens to "insert", "update" and "delete"
                        finder: ~
                        repository: JaiUneIdee\SiteBundle\SearchRepository\IdeeRepository
```

and the query : 
```
    public function search(IdeeSearch $ideeSearch)
    {
        $query_part = new \Elastica\Query\MatchAll();
        $filters = new \Elastica\Filter\Bool();
 
        if($ideeSearch->getTheme() !== null){
            $filters->addMust(
                new \Elastica\Filter\Term(array('theme'=>lowercase($ideeSearch->getTheme()->getNom())))
            );
        }
 
        $filtered = new \Elastica\Query\Filtered($query_part, $filters);
        return $this->find($filtered,50);
    }
```

**Comment by merk** [comment]
And what happens when you directly query ElasticSearch with curl? It seems to me like your custom analyzer is causing it, specifically the lowercase filter..

**Comment by pmithrandir** [comment]
Hello,

I can check at home what would be the result without this analyser(but it was not supposed to be applied on this field I think)
Except the fact that head display the value with capital letter, I think the probleme is mainly in th "input" part.
I got lowercase stored when I would expect the normal value to be there.

Another strange thing, I don't think I got the same need of lowercase whan I was doing the theme selection in the query part(and not filter).

There is something tricky here I think.
Pierre

**Comment by Tobion** [comment]
Closing as this is not related to FOSElasticaBundle. But as a tip: When you use a `term` query it must match exactly. Maybe that's not what you are looking for. Usually you would also have a field mapping for such a field to be not analyzed (keyword). This makes it easier to make sure anyalyzers are not messing up the matching for terms.
