### ISSUE TITLE
Example of research by word

### ISSUE THREAD

**Issue by pmithrandir** [FriendsOfSymfony/FOSElasticaBundle#811]
Hello,

The most common research people would like to perform is the one when you search a given text in a whole document, title, ...

Any way to provide such an example using repositories ?

It's a bit tricky and I'm sure it would help people to start.

Best regards,
Pierre

**Comment by merk** [comment]
I am open to merge PRs that clarify and increase the quality of the documentation.

**Comment by pmithrandir** [comment]
Hello,

As I'm still looking for a way to do that part of the job, I'm not able to help here...
If I find my answer, I will try to help by updating the doc. In the meantime, if someone else has an example, I could also use it and then share the info.

Pierre

**Comment by merk** [comment]
Have you looked at the ElasticSearch documentation? You might be looking for the special field _all.

FOSElasticaBundle is primarily about integration of the library Elastica with Symfony. The Elastica library mimics the HTTP API provided by ElasticSearch - the best place to start is there.
