### ISSUE TITLE
Sorting the models from the repositories

### ISSUE THREAD

**Issue by BitOne** [FriendsOfSymfony/FOSElasticaBundle#813]
Hello guys,

I have a small question as I'm evaluating the use of FOSElasticaBundle.

From what I can see, the main principle is that Elasticsearch is used to retrieve models ids and then the ids are loaded from the model repository, like here:
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Doctrine/MongoDB/ElasticaToModelTransformer.php

Which is very fine to me.

But how do you respect the sort order for model loaded from the model repository ?

Elastic search provides the right order, but once you do a IN('ids') on your DB, there's nothing that forces the DB to provides you the result in the original order as provided by Elasticsearch. I don't see any way to provide order to the ElasticaToModelTransformerInterface::transform() methods.

Is there a way to do that ? Or is it done somewhere else ? From the Finder code, it seems to return directly the results of the transformer:
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Finder/TransformedFinder.php#L35

If my question is not clear here is an example:

I have the following user entities:

id | name
---|-------
1 | Alice
2 | Robert
3 | Denis
4 | Bob

If I do a search sorted on name, ES will send me back the following results:

ids:1, 4, 3, 2

Then if I do my DB query with IN(1,4,3,2), there's a chance that I get the following results:

id | name
---|-------
1 | Alice
2 | Robert
3 | Denis
4 | Bob

because I don't have any order on my query (so there's a high chance that the order will be the one of the primary key, but that would depend on the index).

Is there a problem in my logic here ?

If there's really a problem on FOSElasticaBundle, we could use the order of the ids provided to reorder my result to rebuild a collection of models in the right order.

**Comment by merk** [comment]
The issue is handled here: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Doctrine/AbstractElasticaToModelTransformer.php#L82-119

FOSElasticaBundle keeps the order returned by ElasticSearch.

**Comment by BitOne** [comment]
Thanks a lot for your answer ! I didn't check see this part of the code. Sorry for the inconvenience !
