### ISSUE TITLE
Memory crash for batch

### ISSUE THREAD

**Issue by pierre-b** [FriendsOfSymfony/FOSElasticaBundle#82]
Hi guys,

I've this crash when trying to populate 60 000 objects:

**Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 392213 bytes) in /home/sites/myproject/prod/vendor/elastica/lib/Elastica/Transport/Http.php on line 78**

Any idea please ?

**Comment by ilithium** [comment]
pierre-b: could you share with us how you used PDO?

**Comment by pierre-b** [comment]
Hi @ilithium , I'm sorry I don't even retrieve the source code of it, my project has been fully rewritten since ! But what I learned from this time is: never use ORM/ODM, just micro-frameworks, and do your requests yourself it's faster, easier to debug etc....
