### ISSUE TITLE
Exception after update today

### ISSUE THREAD

**Issue by GuiminZHOU** [FriendsOfSymfony/FOSElasticaBundle#821]
I got this after a composer update just now, 
 Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 4 passed to FOS\ElasticaBundle\Doctrine\Listener::__construct() must implement interface Psr\Log\LoggerInterface, string given, called in /app/cache/dev/appDevDebugProjectContainer.php on line 2032 and defined' in vendor/friendsofsymfony/elastica-bundle/Doctrine/Listener.php:79

**Comment by vkartaviy** [comment]
A just sent PR which fixes that issue https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/822
