### ISSUE TITLE
Allow mapping from DQL queries / doctrine repository.

### ISSUE THREAD

**Issue by pmithrandir** [FriendsOfSymfony/FOSElasticaBundle#825]
Hello,

I will give you an example in my code.
I want to retrieve the last date for a Post or the comment added. My goal is to define the last action performed on the post to display the last modification.

In the current system I have : 
config.yml
```
                post:
                    mappings:
                        id:
                            type: integer
                        lastAction :
                            type : date
```

And in my Post entity : 
```
public function getLastAction()
    {
        $comments = $this->getComments();
        $date = $this->getCreatedAt();
        foreach($comments as $comment){
            if($comment->getCreatedAt()>$date){
                $date = $comment->getCreatedAt();
            }
        }
        return $date;
    }
```
Pretty inefficient isn't it ?

Having access to the doctrine repository would allow me to perform the folowing SQL query : 
```
SELECT 'CASE WHEN COUNT(c.id)>0 THEN MAX(c.created_at) ELSE p.created_at END AS last_action'
FROM Post p
LEFT JOIN Comment c On p.id = c.post_id
```
Much more efficient.
I have multiple example like that where this functionality would be a huge performance improvement for the ES data generation.

Best regards,
Pierre

**Comment by merk** [comment]
You can use an event listener on `POST_TRANSFORM` and inject the repositories you need to set custom fields.

Add mapping for your lastAction date but set a property_path of false. There is more information in the 'dynamic properties` cookbook entry in the docs.

**Comment by pmithrandir** [comment]
Hello,

You mean this one ?
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/cookbook/custom-properties.md

It's hardly understanable from my point of view. 

```
class CustomPropertyListener implements EventSubscriberInterface
{
    private $anotherService;
    // ...
    public function addCustomProperty(TransformEvent $event)
    {
        $document = $event->getDocument();
        $custom = $this->anotherService->calculateCustom($event->getObject());

        $document->set('custom', $custom);
    }

    public static function getSubscribedEvents()
    {
        return array(
            TransformEvent::POST_TRANSFORM => 'addCustomProperty',
        );
    }
}
```

I suppose that $document represent the Elastic search element ?
You are suggesting me to inject the repo as you do with the service, and then to use the set function ?

If yes, I can try to do it and actually reshape a bit the doc to answer the interrogation I had reading it.

Pierre
