### ISSUE TITLE
Configuration : is there any way to name elasticsearch clusters ?

### ISSUE THREAD

**Issue by gxolin** [FriendsOfSymfony/FOSElasticaBundle#826]
I would like to know if there is any way to name the elasticsearch clusters from the FOSElasticaBundle configuration ? 
````http://localhost:9200/```` gives : 
````
{
  "status" : 200,
  "name" : "Kro",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.4",
    "build_hash" : "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
    "build_timestamp" : "2015-02-19T13:05:36Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.3"
  },
  "tagline" : "You Know, for Search"
}
````
and i would like to set ````"cluster_name" : "custom_name"```` from elasticaBundle config (or from somewhere else in my project)

Thanks for your amazing job on this bundle !

**Comment by merk** [comment]
The cluster name is set in elasticsearch.yml in elasticsearch's own configuration. AFAIK it is not possible to set that name from the http API

**Comment by gxolin** [comment]
I already changed my elasticsearch.yml but i was wondering if it could be done through the bundle. 
Thanks !
