### ISSUE TITLE
setFieldBoost in Match Query doesn't work.

### ISSUE THREAD

**Issue by Defgenx** [FriendsOfSymfony/FOSElasticaBundle#827]
I use the Match Query of the FOSElasticaBundle and try to use the method: setFieldBoost(), but it returns the following error:

 ErrorHandler ->handleError ('2', 'Illegal string offset 'boost'', '/my/path/to/vendors/vendor/ruflin/elastica/lib/Elastica/Query/Match.php', '45', array('field' => 'EVENEMENT_NOM', 'key' => 'boost', 'value' => '100', 'this' => object(Match))) 

I think that the problem is that the boost value became a string but it should be a float or a int. But I don't know if it's the real reason of this error (knowing that the error came from the rufflin component). Boost in this query type is still supported in ES ; it's written in the documentation.

It works well with the Regexp Query or QueryString.

**Comment by merk** [comment]
Please seek assistance with Elastica errors in the Elastica repository.
