### ISSUE TITLE
batch_size is not propagated from config into populate command

### ISSUE THREAD

**Issue by digitalkaoz** [FriendsOfSymfony/FOSElasticaBundle#829]
currently the `batch_size` option  is not propagated into the `PopulateCommand`
its always `null, and therefore the slicer runs into an endless loop

a workaround is to give it the command-line option `batch_size`

**Comment by vadim2404** [comment]
:+1: I catch the same issue.

**Comment by Kevlys** [comment]
Same issue here

**Comment by merk** [comment]
Should be fixed in 3.1.1
