### ISSUE TITLE
Error console elastica populate

### ISSUE THREAD

**Issue by roberwushu** [FriendsOfSymfony/FOSElasticaBundle#831]
I have the next error when execute in console: php app/console fos:elastica:populate

PHP Fatal error:  Class 'Symfony\Component\Console\Helper\ProgressBar' not found in /var/www/html/sfproyect/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php on line 78

Use
symfony/symfony                      v2.3.26            The Symfony PHP framework
friendsofsymfony/elastica-bundle     3.1.0              Elasticsearch PHP integration for your Symfony2 project using Elastica

**Comment by webda2l** [comment]
Same for me, I search a bit without find valid fix.

People can use ````php app/console fos:elastica:populate --no-overwrite-format```` to avoid this currently.

**Comment by macintoshplus** [comment]
Same for me

**Comment by merk** [comment]
Fixed in 3.1-dev, will be part of 3.1.1

**Comment by webda2l** [comment]
Ok ProgressBar naming is Symfony >= 2.5 in fact

**Comment by roberwushu** [comment]
It is true that with that option found php app/console fos:elastica:populate --no-overwrite-format but only populate one entity if I have several fails to jump to the next entity

**Comment by merk** [comment]
Please create a new issue with more details about your set up and exactly what is going wrong.
