### ISSUE TITLE
v3.1.0 - CLI - PHP Fatal error:  Class 'Symfony\Component\Console\Helper\ProgressBar' not found in PopulateCommand.php on line 78

### ISSUE THREAD

**Issue by Giuffre** [FriendsOfSymfony/FOSElasticaBundle#833]
From CLI, when i run app/console fos:elastica:populate on Mac OS X, i give this error:

```
PHP Fatal error:  Class 'Symfony\Component\Console\Helper\ProgressBar' not found in /private/var/www/my-project/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php on line 78
```
But from my IDE the Class ProgressBar is correctly loaded.

**Comment by Sweep810** [comment]
In my case the ProgessBar is found, but the output is broken, i just see something like this:

     $ app/console f:e:p
     0/3 [>---------------------------]   0%
    %message%

the index will be populated anyway.

maybe its related to your Problem?

**Comment by nurikabe** [comment]
I'm seeing the same as @Sweep810

**Comment by webda2l** [comment]
ProgressBar not found has been fixed in dev-master
And invalid progress is due to https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/829 I think. Try to add ````--batch-size=100```` in your command

**Comment by Giuffre** [comment]
@webda2l When the fix will be available in a stable version?

**Comment by merk** [comment]
Fixed in 3.1.1

**Comment by Giuffre** [comment]
I'm on Symfony 2.3.* and this is a new error in cli when i'm runngin fos:elastica:populate :
```
PHP Catchable fatal error:  Argument 1 passed to Symfony\Component\OptionsResolver\OptionsResolver::setAllowedTypes() must be of the type array, string given, 
called in /private/var/www/api.schoolproject.org/vendor/friendsofsymfony/elastica-bundle/Provider/AbstractProvider.php on line 107 and defined in
 /private/var/www/my-project/vendor/symfony/symfony/src/Symfony/Component/OptionsResolver/OptionsResolver.php on line 168
```
There are known incompatibilities with version 2.3.x of Symfony?

**Comment by merk** [comment]
Yeah - i broke compatibility with 2.3 sorry, setAllowedTypes needs to be
called with an array. Havent had a chance to fix it yet.

**Comment by Giuffre** [comment]
Ok, i will waiting for 2.7 stable realease. With Symfony 2.3,
foselasticabundle working with up to 3.0.9 version.

*Angelo Giuffredi*

2015-03-27 10:06 GMT+01:00 Tim Nagel <notifications@github.com>:
