### ISSUE TITLE
Paginated Facets throws an error...Attempted to load class "Pagerfanta"

### ISSUE THREAD

**Issue by eddiejaoude** [FriendsOfSymfony/FOSElasticaBundle#851]
Error:
```
Attempted to load class "Pagerfanta" from namespace "Pagerfanta".
Did you forget a "use" statement for another namespace?
```

Example code from documentation:
```php
$query = new \Elastica\Query();
$facet = new \Elastica\Facet\Terms('tags');
$facet->setField('companyGroup');
$query->addFacet($facet);

$companies = $finder->findPaginated($query);
$companies->setMaxPerPage($params['limit']);
$companies->setCurrentPage($params['page']);

$facets = $companies->getAdapter()->getFacets();
```

Composer:
```
"friendsofsymfony/elastica-bundle": "~3.1",
```

**Comment by westberliner** [comment]
Pagerfanta is part of composer require-dev and will not installed by default. 
Just execute "composer require pagerfanta/pagerfanta" for your composer.json.

**Comment by anhnt0212** [comment]
@westberliner  :+1:

**Comment by hmuschett** [comment]
if not just execute "composer require pagerfanta/pagerfanta"  buy composer not work in my country

**Comment by anhnt0212** [comment]
Your country not using composer ???? @hmuschett

**Comment by hmuschett** [comment]
I try but I always throws error "The "https://getcomposer.org/packages.json" Could not be downloaded file: failed to open stream: Can not connect to HTTPS through proxy server" and I've tried a thousand ways but nothing sel using set command http_proxy = http: // username: PASSS @ server: port  and i not use composer for this @anhnt0212

**Comment by XWB** [comment]
You need to install Pagerfanta.
