### ISSUE TITLE
moreLikeThis broken

### ISSUE THREAD

**Issue by nurikabe** [FriendsOfSymfony/FOSElasticaBundle#854]
I was surprised to notice `moreLikeThis` implemented in `TransformedFinder`.  Not so surprised to see that it's not really working.  I think Elastica's `mlt` implementation has been refactored.

**Comment by merk** [comment]
Yes, this is possible. We have no test coverage of these areas.

**Comment by gido** [comment]
PR #950 is a try to fix it. We should definitively add test coverage on it or think to remove the implementation.
