### ISSUE TITLE
Use this bundle without Doctrine or Propel

### ISSUE THREAD

**Issue by rbarilani** [FriendsOfSymfony/FOSElasticaBundle#858]
Hi guys is possible to use this bundle without Doctrine or Propel. I have a custom model layer, elastica documents are indexed by another application (a python application) so i must only read and query those documents and then transform those documents to my custom "entities". is that possible? Any suggestion? I think that i have to start implementing an ElasticaToModelTranformer and register it.. i'm wrong? Thank you in advance. Ruben

**Comment by eric-hansen** [comment]
I use this at work without having it do anything w/ an ORM.  If you don't want to use an ORM just don't set the config options for it.  There's no changes I have to specifically make and it plays nicely.  If you have any questions feel free to ping me on here.

**Comment by khalildakhli** [comment]
Hello, I removed the doctrine configuration, but I receive this message :
The service "fos_elastica.manager.orm" has a dependency on a non-existent service "doctrine".
is that this bundle will not work without doctrine? can you help me?

**Comment by eric-hansen** [comment]
@khalildakhli it depends on how you set up Elastica in your configs.  We don't use a mapper so we don't have an inherent dependency on any DB set up.  However, if you use any of the mappers (forgot the technical term) then it would make sense for this error.

You can also try clearing your cache to make sure it's all fresh.

**Comment by khalildakhli** [comment]
Thank you for your help.
I tested this example (https://github.com/obtao/blog-sandbox) on a windows server Xampp.
I modified : fos_elastica.yml
fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        obtao_blog:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_analyzer :
                                type     :    custom
                                tokenizer:    nGram
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                            custom_search_analyzer :
                                type     :    custom
                                tokenizer:    standard
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 2
                                max_gram: 20
                        filter:
                            snowball:
                                type:     snowball
                                language: French
                            elision:
                                type:     elision
                                articles: [l, m, t, qu, n, s, j, d]
                            stopwords:
                                type:      stop
                                stopwords: [_french_]
                                ignore_case : true
                            worddelimiter :
                                type:      word_delimiter
            types:
                category:
                    mappings:
                        id:
                            type: integer
                        label : ~
                    persistence:
                        model: Obtao\BlogBundle\Entity\Category
                        finder: ~
                        provider: ~
                        listener: ~

And I removed the doctrine configuration in app/config.yml

I cleared the cache.

**Comment by skafandri** [comment]
use a [code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/) please

**Comment by Tobion** [comment]
The bundle does not depends on doctrine o propel. For example you can just use the mapping configuration and the command fos:.elastica:reset and for the rest use elastica directly.

**Comment by florianajir** [comment]
There's no documentation for crud operations without using listeners
