### ISSUE TITLE
Manual Provider

### ISSUE THREAD

**Issue by ilithium** [FriendsOfSymfony/FOSElasticaBundle#864]
Hey guys

I have a scenario where I want to populate ES via a SQL query and DBAL, instead of the ORM as I've heard this is more efficient and also allows me to change which table is used to pull the data from.

I _think_ this is done by using a manual provider; however, the documentation here is very limited.

Can you provide some more details on a) what these are for and b) how they actually work?

Thanks!

**Comment by davidfuhr** [comment]
I am working on the documentation of the customer provider in #872. Maybe it already covers your use case.
