### ISSUE TITLE
Wrong or outdated way to extend FOS\ElasticaBundle\Doctrine\Listener

### ISSUE THREAD

**Issue by davidvartanian** [FriendsOfSymfony/FOSElasticaBundle#865]
Hi guys, I've just needed to extend a listener for a deeper configuration of an entity on my application. I've found only old posts like this http://stackoverflow.com/questions/21909763/symfony2-foselasticabundle-update-index-for-all-entities-related-to-the-entity-u, which is and outdated way to create a custom entity listener. I also noticed that these type of implementations are not part of the bundle's documentation. I'm using the 3.1.3 version of this bundle.

So, trying to make it work regarding the stackoverflow link I got this error:

```
PHP Catchable fatal error:  Argument 1 passed to Doctrine\Common\EventManager::addEventSubscriber() must implement interface Doctrine\Common\EventSubscriber
```

But looking at the base FOS\ElasticaBundle\Doctrine\Listener class I changed my service declaration dependencies to this: `[@fos_elastica.object_persister.search.clothing, @fos_elastica.indexable]` and it worked because the tag doctrine.event_subscriber adds this to the appDevDebugProjectContainer class: `$d->addEventSubscriber($this->get('my_bundle.listener.elastica.entity'));` and that method requires a `Doctrine\Common\EventSubscriber` object.
Therefore it's also required to implement the `Doctrine\Common\EventSubscriber` on the customised listener class.

I could write a document to help you add this to the main documentation if you want.
Thanks for the bundle, it's awesome!

**Comment by NoScopie** [comment]
:+1:

**Comment by dbhattacharjee** [comment]
Can you please share service definition(in config.yml) and custom class ? I am bit confused here as I am following the same post you have mentioned.

**Comment by patie** [comment]
can anyone explain how to do it please? :)

**Comment by dbhattacharjee** [comment]
@patie 

I have done it bit differently. I have two related entities A & B. My task was to update A after related B is updated.

So I have created a function in B's entity class file which is called via @ORM\PostUpdate. So each time B is updated this function is called. And inside this function, I have added code to update A. like this : 

function updateAonB() {
 $kernel = $GLOBALS['kernel'];
 $container = $kernel->getContainer();
$a = $container ->getDoctrine()->getManager()->getRepository('A')->findBy(array('b'=>$this->getId()));
            $persister = $container->get('fos_elastica.object_persister.organizations.A');
            $persister->insertMany($a);
        }
}

**Comment by davidvartanian** [comment]
How to break a model, a paradigm and all hopes of good practices in only 3 lines of code :smile_cat:

**Comment by dbhattacharjee** [comment]
yes, when people who has knowledge keep silence when asked for guidance/help.

**Comment by XWB** [comment]
Closing this. Feel free to create a PR containing the documentation :)
