### ISSUE TITLE
Index Only Specific field

### ISSUE THREAD

**Issue by Solirio** [FriendsOfSymfony/FOSElasticaBundle#874]
Hi, 

Im french, so first, sorry my english if it's hard to read :).

I searched during 2-3 hours everywhere i can, but i dont find the way i can resolv my problem.

I have 1 entity wich have relation with 4 other entity, and i dont want them to be index. I just want to index specific attribute. Like Title, content, but not the relationship.

So i did something like that:

mappings:
                        titre: { analyzer: custom_french_analyzer }
                        presentation: { analyzer: custom_french_analyzer } 
                        etablissement: { index: false, store: false, type: nested } //Entity
                        etat: { index: false, store: false, type: nested } //Entity
                        status: { index: false, store: false, type: nested } //Entity
                        categorie: { index: false, store: false, type: nested } //Entity

Everything i do dont take effect or make error like , i think this is just a syntax problem or do things like that: 
caused MapperParsingException[failed to parse [etat]]; 

When i go to http://127.0.0.1:9200/_plugin/head/ to see my index, there is all of the attribute of all those entity. I dont want it.

Thanks for all answer :). And Thanks for this bundle.

**Comment by merk** [comment]
Remove this:

```
etablissement: { index: false, store: false, type: nested } //Entity
etat: { index: false, store: false, type: nested } //Entity
status: { index: false, store: false, type: nested } //Entity
categorie: { index: false, store: false, type: nested } //Entity
```

Also, if you are using the "serializer" you have to configure the serializer to exclude your relationships.

**Comment by Solirio** [comment]
At the begin they were not present in my code, and relationships and all their attribute were mapped too. I will look for what u say about serializer
