### ISSUE TITLE
fos:elastica:populate doesn't work with Doctrine 2.5

### ISSUE THREAD

**Issue by korotovsky** [FriendsOfSymfony/FOSElasticaBundle#876]
If entity's `@id` field is an object.

There is ugly workaround which I use:

``` patch
         // https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/3.1.x/Doctrine/ORM/Provider.php#L51
         $qb = clone $queryBuilder;
         $rootAliases = $queryBuilder->getRootAliases();

+        /** @var \Doctrine\ORM\Query\Expr\From $fromDQLPart */
+        $fromDQLPart = $queryBuilder->getDQLPart('from')[0];
+        $manager = $this->managerRegistry->getManagerForClass($fromDQLPart->getFrom());
+        $metadata = $manager->getClassMetadata($fromDQLPart->getFrom());
+        $count = sprintf('%s.%s', $rootAliases[0], $metadata->getIdentifier()[0]);
+
         return $qb
-            ->select($qb->expr()->count($rootAliases[0]))
+            ->select($qb->expr()->count($count))
             // Remove ordering for efficiency; it doesn't affect the count
             ->resetDQLPart('orderBy')
             ->getQuery()
             ->getSingleScalarResult();
     }
```

In Doctrine 2.5 aliases must have full name, and associations isn't allowed anymore.

Related issue in Doctrine2 tracker: http://www.doctrine-project.org/jira/browse/DDC-3706

**Comment by Don87** [comment]
+1 But for me your workaround is not functioning, I get a different error message

Malformed action line [1] expected a simple value for field [_id] but found [Start_Object]

**Comment by Don87** [comment]
Nothing official about this yet? I know not many have joins on the table id but is it possible to fix this?

**Comment by rparsi** [comment]
@korotovsky Can you get around the problem by making `@id` field an `integer` and storing the related data in another field?
