### ISSUE TITLE
RFC: add new event to modify collection of objects when populating database

### ISSUE THREAD

**Issue by borNfreee** [FriendsOfSymfony/FOSElasticaBundle#887]
Hi,

This bundle has useful `POST_TRANSFORM` event where new field could be added to the `Document`. I need to query database to fetch the value and add it as a new field. So there are 100 additional SQL queries when 100 records are populated.

Of course, it would be greate to make 1 SQL query with `SELECT ... WHERE id IN(1,2,3,4...)` and then update each entity with fetched values.
So i suggest to add an event before each Entity is transformed to elastic Document, here:

``` php
// elastica-bundle/Persister/ObjectPersister.php

public function insertMany(array $objects)
{
    $documents = array();

    // <--------- Here I need a way to modify collection
    $event = new TransformCollectionEvent(objects);
    $this->dispatcher->dispatch(TransformEvent::TRANSFORM_COLLECTION, $event);
    $objects = $event->getObjects();
    // end of new code

    foreach ($objects as $object) {
        $documents[] = $this->transformToElasticaDocument($object);
    }
    try {
        $this->type->addDocuments($documents);
    } catch (BulkException $e) {
        $this->log($e);
    }
}
```

What do you think? If it's ok, I can send a PR.
Please advice.

**Comment by merk** [comment]
The proposed location of the event isnt specific to transformation, i'd create events for each of the *many functions in the Persister - it will allow other operations on objects being added and help moving towards singular service instances rather than an instance per type.

INSERT_OBJECTS, REPLACE_OBJECTS, etc
