### ISSUE TITLE
Resolve deprecated uses of get/setFactoryService and get/setFactoryMethod

### ISSUE THREAD

**Issue by samjarrett** [FriendsOfSymfony/FOSElasticaBundle#889]
Symfony 2.6 deprecated Definition::getFactoryService, Definition::setFactoryService, Definition::setFactoryMethod, Definition::getFactoryMethod,  Definition::setFactoryClass and Definition::getFactoryClass in favour of a simplified setFactory() method instead. 

FOSElasticaBundle uses these methods in various places, and causes errors to be triggered throughout the application, particularly when building the container (incl. actions like clearing/building cache). 

Mostly this seems to be in `FOSElasticaExtension.php` and the various configuration XML files inside `Resources/config`.

**Comment by merk** [comment]
I'm happy to merge a PR as long as it maintains support for symfony 2.3

**Comment by aequasi** [comment]
Can we create a new branch/version that doesn't need to support 2.3? Not supporting the new LTS seems pretty bad.

**Comment by aequasi** [comment]
I'm not entirely sure supporting 2.3 is really feasible either, considering most of the deprecations were added in either 2.5 or 2.6.

**Comment by merk** [comment]
Symfony 2.3 is supported until mid 2016, and I'm not willing to maintain multiple branches for this support. It should be possible to handle both ways of doing it in the Extension.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/894

**Comment by XWB** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/894
