### ISSUE TITLE
Elastica dont return pertinent results 

### ISSUE THREAD

**Issue by houss2040** [FriendsOfSymfony/FOSElasticaBundle#890]
I want to get indexed Product with category slug, i have two slug of category : "fruit" and "fruit-sec" , i want to extract only product that have "fruit-sec" slug category , but it return to me "fruit" and "fruit-sec" result ... 
This my index 
```
[......]
"hits": {
      "total": 8,
      "max_score": 1,
      "hits": [
         {
            "_index": "searchproduct",
            "_type": "produit",
            "_id": "556887fda98a93d02600002d",
            "_score": 1,
            "_source": {
               "tags": [
                  "value_3",
                  "value_4",
                  "value_5"
               ],
               "category": {
                  "slug": "fruit"
               }
            }
         },
         {
            "_index": "searchproduct",
            "_type": "produit",
            "_id": "55688277a98a933431000034",
            "_score": 1,
            "_source": {
               "tags": [
                  "Traditionnelle"
               ],
               "category": {
                  "slug": "fruit-sec"
               }
            }
[.....]
}
```

And this is my request : 

```
 $boolQuery = new \Elastica\Query\Bool();
 $_subQuery = new \Elastica\Query\Match();
/*
* listSlugs = array("fruit-sec");
*/
 $_subQuery->setFieldQuery("category.slug", $listSlugs);
  $boolQuery->addMust($_subQuery);

$produits = $finderproduct->find($boolQuery);

```

**Comment by GeoffroyR** [comment]
This seems a correct response for the query you are showing.
Have a look at the documentation of elasticsearch: https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-analysis.html

Hint: You should store the field category.slug as "not_analyzed":
category:
  type: object
  properties:
    slug:
       type: string
       fields:
         raw: {type: string, index: not_analyzed}

If you still think there is an issue, you should post your mapping but this doesn't seem to be related to the bundle. For usage questions you should post them on SO.

**Comment by houss2040** [comment]
Hello , thanks for response.
I found a solution,   i change mapping with id 
``
category:
  type: object
  properties:
    id: ~
``

Then , 

``
$boolQuery = new \Elastica\Query\Bool();
$boolQueryForCat = new \Elastica\Query\Bool();
$_subQuery = new \Elastica\Query\Match();
 $_subQuery->setFieldQuery("category.id", $id);
 $boolQueryForCat->addShould($_subQuery);
 $boolQuery->addMust($boolQueryForCat);
``
