### ISSUE TITLE
"Immediate" configuration option breaks auto-update

### ISSUE THREAD

**Issue by GeoffroyR** [FriendsOfSymfony/FOSElasticaBundle#895]
Could found three reports related to this issue: #796  #741 #654

The "immediate" option is not working (did it ever work?) and breaks the auto-update feature.
Looking at the code, it's a switch to use preFlush in place of postFlush.
Problem is that at "preFlush" no event was triggered as the bundle listens to postPersist and postUpdate which are triggered after.

Commit 22a5d67d05d2df4fe46ca6e80f4b21198f2d3b19 should be reverted completely.

**Comment by nurikabe** [comment]
This was a backwards-compatibility concession that worked for I think about ten full minutes until @merk started in with some heavy refactoring.  Given that the original behavior which "immediate" was meant to replicate never made sense anyway I think we should deprecate and tag a release.

**Comment by chrisciampoli** [comment]
I have the same issue, yet the problem persists after removing the immediate config setting.

playlist:
                    mappings:
                        dynamic_date_formats: ["yyyy-MM-dd", "dd-MM-yyyy"]
                        id: ~
                        name: ~
                        shared:
                          type: boolean
                        videos:
                          type: nested
                    persistence:
                        driver: mongodb
                        model: Document\Playlist
                        provider: ~
                        listener: ~
                        finder: ~
                        model_to_elastica_transformer:
                          service: playlist_transformer
I still get no triggered event when a new document is created, or an existing is updated.

**Comment by raphox** [comment]
Hi @GeoffroyR 

See my codes:

```php
public function updateAction(Request $request, $id)
    {
...
        $em     = $this->getDoctrine()->getManager();
        $entity = $em->getRepository('MisterVagaCompanyBundle:Vacancy')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Vacancy entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            $flash->success('Registro atualizado com sucesso.');

            return $this->redirect($this->generateUrl('mister_vaga_company_vacancy_edit', array('id' => $id)));
        }
...
    }
```

When I debug CORE code of FOSElasticaBundle:

```php
namespace FOS\ElasticaBundle\Persister;
...
class ObjectPersister implements ObjectPersisterInterface
{
...
    /**
     * Bulk update an array of objects in the type.  Create document if it does not already exist.
     *
     * @param array $objects array of domain model objects
     */
    public function replaceMany(array $objects)
    {
        var_dump(array(
            $objects,
            $this->transformToElasticaDocument($objects[0])
        ));
        exit();
```

Old data:

```
'salary' => float 1400
```

Im receiving this:

```php
array (size=2)
  0 => 
    array (size=1)
      0 => 
        object(MisterVaga\CompanyBundle\Entity\Vacancy)[718]
...
          private 'salary' => float 1500
...
  1 => 
    object(Elastica\Document)[119]
...
          'salary' => float 1500
...
```

Being that my POST data is:

```php
'salary' => float 1500
```

But in other debug slice, we have a error:

```php
namespace Elastica;

class Index implements SearchableInterface
{
...
    public function updateDocuments(array $docs)
    {
        foreach ($docs as $doc) {
            $doc->setIndex($this->getName());
        }

        var_dump(array(
            $docs,
            $this->getClient()
        ));
        exit();
...
```

Result (THE CLIENT HAS A EMPTY CONFIG :( ):

```php
array (size=3)
  0 => 
    object(FOS\ElasticaBundle\Elastica\Client)[142]
...
      protected '_config' => 
        array (size=13)
          'host' => null
          'port' => null
          'path' => null
          'url' => null
          'proxy' => null
          'transport' => null
          'persistent' => boolean true
          'timeout' => null
          'connections' => 
            array (size=1)
              ...
          'roundRobin' => boolean false
          'log' => boolean false
          'retryOnConflict' => int 0
          'connectionStrategy' => string 'Simple' (length=6)
```

Im working to resolve this now.

But in the cache of Syfmony, we have:

```php
    protected function getFosElastica_Client_DefaultService()
    {
        $this->services['fos_elastica.client.default'] = $instance = new \FOS\ElasticaBundle\Elastica\Client(array('connections' => array(0 => array('host' => 'localhost', 'port' => 9200, 'logger' => false, 'headers' => array())), 'connectionStrategy' => 'Simple'), '');
        $instance->setStopwatch($this->get('debug.stopwatch', ContainerInterface::NULL_ON_INVALID_REFERENCE));
        return $instance;
    }
```

:(

**Comment by raphox** [comment]
The problem not in configuration.

I found the problem :D

In the documentation of Elastic 1.7 the update process is send by POST request and in Elastic lib by PUT:

```php
namespace Elastica;
...
class Client
{

...
    public function updateDocuments(array $docs)
    {
        if (empty($docs)) {
            throw new InvalidException('Array has to consist of at least one element');
        }

        $bulk = new Bulk($this);

        $bulk->addDocuments($docs, \Elastica\Bulk\Action::OP_TYPE_UPDATE);

        return $bulk->send();
    }
```

```php
namespace Elastica;
...
class Bulk
{
...
    /**
     * @return \Elastica\Bulk\ResponseSet
     */
    public function send()
    {
        $path = $this->getPath();
        $data = $this->toString();

        $response = $this->_client->request($path, Request::PUT, $data, $this->_requestParams);

        return $this->_processResponse($response);
    }
```

If I change:

`$response = $this->_client->request($path, Request::PUT, $data, $this->_requestParams);`

By:

`$response = $this->_client->request($path, Request::POST, $data, $this->_requestParams);`

I fix my problem.

BUT. In the `\Elastica\Client` we the method:

```
    public function updateDocument($id, $data, $index, $type, array $options = array())
    {
...
        $response = $this->request($path, Request::POST, $requestData, $options);
```

WHY we have `updateDocument` that use Bulk and `updateDocuments` that use your his own request` method`?

I'm in desperate need of help.

**Comment by raphox** [comment]
This problem in Elastica.

Fixed by https://github.com/ruflin/Elastica/pull/1011 (Unreleased) :(

Someone suggests a way for my application work?

**Comment by ewgRa** [comment]
@raphox It is released in 3.x. Since Elastica haven't release branches - there is no backport this change to 2.x. Unless if it is bug, probably there is possibility to backport it.

Btw, here https://github.com/ruflin/Elastica/pull/1011#issuecomment-165065074 we discuss it and there is notice that ES understand both PUT and POST. Can you check please again, that when you change PUT to POST it start working?

And which one ES version you have?

**Comment by raphox** [comment]
Yes @ewgRa , when I change my code:

```php
// Class \Elastica\Client
    public function updateDocument($id, $data, $index, $type, array $options = array())
    {
...
        $response = $this->request($path, Request::POST, $requestData, $options);
```

My changes on Doctrine's entities change my index on Elastic.

See my https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/895#issuecomment-174238687 to fix this problem.

Regards.

**Comment by ewgRa** [comment]
> To fix my problem I override dependencies of FOSElasticaBundle inserting in my composer.json

It is not right. Each Elastica release work with specific ES version.

dev-master now is ES 2.x. And you seems have ES 1.x.

I will take a look later more carefully, maybe find something. For now it looks strange.

**Comment by raphox** [comment]
My request is:

```
curl -XPOST 'localhost:9200/mistervaga_prod/mistervaga_company_vacancy/215/_update' -d '
{"doc":{"id":215,"company.id":2712,"position.id":1,"contract_type":0,"period":["Manhã","Tarde"],"remuneration_period":2,"remuneration":0,"salary":1569,"salary_range_min":null,"salary_range_max":null,"education_minimum":0,"previous_experience":0,"deficiency":0,"address_state":"AM","address_city":"teste","labels":null,"created":"2016-01-23T20:49:08-02:00","updated":"2016-01-23T22:05:51-02:00","exclusive":false,"enabled":1,"page_content":" Auxiliar | Super Miss Idiomas Código da vaga: 000000215 Atualizado em: 23\/01\/2016 22:05 Publicada em: 23\/01\/2016 20:49 Vagas disponíveis 1 Remuneração Salário Salário (R$) 1.553,00 Tipo de contrato Efetivo (CLT) Observações do contrato teste xyz123 Périodo do contrato Manhã, Tarde Observações do périodo Não informado Benéficios teste Atividades teste Escolaridade necessária Ensino Fundamental Incompleto Experiências anteriores Não é necessária experiência anterior Requisitos Não informado Deficiência Oportunidade exclusiva para portadores de deficiência Cidade teste Estado AM "},"doc_as_upsert":true}'

If I use -XPOST` it works, but if I use `-XPUT` the request does not generate effect in Elastic.

**Comment by ewgRa** [comment]
For update it is right: https://github.com/elastic/elasticsearch/blob/1.7/rest-api-spec/api/update.json
It support only post.

But update it is not a bulk. Bulk support and post, and put.

Seems you mix this two cases.

**Comment by ewgRa** [comment]
Which one Elastica version you use?

I check Client::updateDocument - seems it always was POST and it is not use Bulk.

For Bulk it was PUT yes, but for Bulk PUT is supported.

Can you check again carefully? Reinstall or revert your changes in Elastica and so on.

**Comment by raphox** [comment]
Hi @ewgRa, thank you for support until now.

The setting that really works is:

```
persistence:
    driver: orm
    model: MisterVaga\CompanyBundle\Entity\Vacancy
    provider: ~
    listener:
        immediate: false
    finder: ~
```

If I change the `immediante` to `~` (equal to https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md#d-defining-index-types) or `true`. The update stops working and even appears in the application log.

I have no time now. But in the short time I have had here, I could see that the process does not come to call the method `replaceMany` of `FOS\ElasticaBundle\Persister\ObjectPersister`.

**Comment by VincentChalnot** [comment]
Hey ! Just for your information, I have the same bug with immediate: ~
It works with listener: ~

**Comment by ConneXNL** [comment]
I have a problem where i have to call flush on the doctrine orm entity manager twice. Calling it only once updates the database but not the ES for some reason. 

Is this related?

**Comment by gitruslan** [comment]
Hi guys i've got the same problem , after research and analyze code i found problem. 
When we want to use immediate: true
and after persist, than flush one entity ( with entity manager) 
In friendsofsymfony/elastica-bundle/Doctrine/Listener.php

1. method which called is preFlush (tries to save data into ES, but scheduledForInsertion - still empty)
2. method postPersist (which collects entity and fills scheduledForInsertion array )

That's why ES can insert data
You can change this on 
listener: ~ 
or 
listener:
    insert: true
    update: true
    delete: true

It works for me.

**Comment by XWB** [comment]
The `immediate` option has been removed.
