### ISSUE TITLE
URGENT: You have requested a non-existent service "fos_elastica.index_manager"

### ISSUE THREAD

**Issue by edouardkombo** [FriendsOfSymfony/FOSElasticaBundle#907]
I have installed all versions from 3.1.4 to dev-master, this is my configuration:

	fos_elastica:
		clients:
			default: { host: localhost, port: 9200 }
		serializer:
			callback_class: FOS\ElasticaBundle\Serializer\Callback
			serializer: serializer
		indexes:
			entrepatients:
				index_name: entrepatients
				client: default
				settings:
					index:
						analysis:
							analyzer:
								custom_search_analyzer:
									type: custom
									tokenizer: standard
									filter   : [standard, lowercase, asciifolding]
								custom_index_analyzer:
									type: custom
									tokenizer: standard
									filter   : [standard, lowercase, asciifolding, custom_filter]
							filter:
								custom_filter:
									type: edgeNGram
									side: front
									min_gram: 1
									max_gram: 20
				types:
					Tags:
						mappings:
							slug: { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string }
							#slug: { type: string }
						persistence:
							driver: orm # orm, mongodb, propel are available
							model:  Application\Sonata\ClassificationBundle\Entity\Tag
							provider: ~
							finder: ~
							provider: ~
							listener: ~ # by default, listens to "insert", "update" and "delete"
					Users:
						mappings:
							username: { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string }
							email: { search_analyzer: custom_search_analyzer, index_analyzer: custom_index_analyzer, type: string }
						persistence:
							driver: orm
							model:  Application\Sonata\UserBundle\Entity\User
							provider: ~
							finder: ~
							provider: ~
							listener: ~ # by default, listens to "insert", "update" and "delete"

When I execute:
    
    app/console fos:elastica:populate

This is the error I got, like if my services weren't loaded:
  
    You have requested a non-existent service "fos_elastica.index_manager"

Please help !

**Comment by edouardkombo** [comment]
It was a mistake, I didn't included my fos_elastic config inside the config.yml.

Solved.

**Comment by ajielee** [comment]
@edouardkombo I got the same probleme, and I do included `fos_elastica` config inside `config.yml`, but it still doesn't work.
