### ISSUE TITLE
Assigning MongoID on object instantiation breaks indexing (3.0 Alpha 3 and up)

### ISSUE THREAD

**Issue by wackerl91** [FriendsOfSymfony/FOSElasticaBundle#909]
Hey there,

I've been running into an issue with indexing documents after updating this bundle from Alpha 1 to 3.0.10.:

On document creation the _id field on the index is not the document id (like it used to be before) but instead some other hash - which results in errors since ElasticSearch cannot get documents with those IDs from Doctrine.

After some digging I found out that this starts to happen once 3.0.0-ALPHA3 is installed. My guess is because "#415: BC BREAK: document indexing occurs in postFlush rather than the pre\* events previously." not only changed _when_ the bundle listens for changes but also how (the 'immediate' option should revert this behaviour to how it worked before and this was the first thing I've tried to no avail).
Strange enough, once one of the documents get updated, the _id value on ElasticSearch index is replaced with the actual document id.

My first workaround was to explicitly specifying the path for the _id field and add a mapping for id:

```
location:
                    _id:
                        path: "id"
                    mappings:
                        id:
                            type: string
```

which (in my opinion) isn't really a solution of the actual problem.

So after some more digging I found that we're generating a new MongoID on object instantiation:

```
    public function __construct()
    {
        $this->id = new \MongoId();
    }
```

If I stop doing this everything works smooth. Problem is we actually need new MongoIDs as soon as we construct a new object, so neither of the solutions I've found are actually viable for us.

Since this worked perfectly fine until ALPHA3 my guess is really that something crucial has changed on how FOSElasticaBundle fills the index.

Environment: 
Symfony 2.3.x
ElasticSearch: 1.0.3
FOSElasticaBundle 3.0.0-ALPHA3 and up

I'd really appreciate it if there was a non-workaround solution for this. If you need any more details please tell me, I'm happy to provide them.

Cheers!

**Comment by XWB** [comment]
Closing as we don't have any Mongodb maintainers.
