### ISSUE TITLE
Populate command as a leak of memory due to Doctrine2 EM

### ISSUE THREAD

**Issue by Raffaello** [FriendsOfSymfony/FOSElasticaBundle#912]
It is required to restart the connection after every bulk insertion, because EM of doctrine will cache in memory the entites and will downgrade performance as well as use more memory.

Something like this with doctrine EM:

```
//$em->clear();
$em->close();
$em = $em->create($em->getConnection(), $em->getConfiguration());
```

**Comment by damienalexandre** [comment]
Hey,

`$em->clear();` is supposed to deal with that (removing the entities).

Do you run the command in "prod" env and have [you read this](https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/620fcf523b506155372dca6f0fea9f48c3659c6a/Resources/doc/types.md#turning-on-the-persistence-backend-logger-in-production)? Doctrine can leak a lot via it's logger.

**Comment by Raffaello** [comment]
It should be the same as run the command with `--no-debug` paramter. right?

Anyway I'll give it a try on Monday in prod with no debug etc...
Thank you very much, I missed that part, I hope it will be enough. :+1: 

---
But for some past experience, I already managed some massive insertion with doctrine and even with SQLlogger(null) and EM cleared, there is still a memory leaking and after a while a downgrade in performance due to the caching mechanism that store in memory to avoid fetching from the DB, but when the cache it's quite huge, it has some negative effect on performance and memory usage.
The only way I found useful to no rewrite in raw SQL, it was resetting the connection after X insertion, so It flush/empty the cache and restore a "normal" performance and memory usage.

This is issue is quite notable because the memory is still growing and slow down the objects per sec.
(anyway I give a feedback on monday about that configuration that I missed)

thanks

**Comment by Raffaello** [comment]
I tried with your suggestion, even with `--no-debug` paramter in `prod` environment.
Is still present a memory leaking. 
Looking into the process and the memory it's growing

**Comment by Raffaello** [comment]
here the memory leak:

./app/console fos:ela:pop --index asset_search_v13 --batch-size=1000
  344000/2628794 [===>------------------------]  13%
Populating asset_search_v13/assetsearch
Fatal error: Allowed memory size of 1585446912 bytes exhausted (tried to allocate 986301 bytes) in /var/www/alpha.api.bridgemanimages.com/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php on line 157
[2015-10-02 18:17:04] php.EMERGENCY: Fatal Error: Allowed memory size of 1585446912 bytes exhausted (tried to allocate 986301 bytes) {"type":1,"file":"/var/www/alpha.api.bridgemanimages.com/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php","line":157,"level":-1,"stack":[]}

Fatal error: Uncaught exception 'Symfony\Component\Debug\Exception\OutOfMemoryException' with message 'Error: Allowed memory size of 1585446912 bytes exhausted (tried to allocate 986301 bytes)' in /var/www/alpha.api.bridgemanimages.com/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php:157
Stack trace:
#0 {main}
  thrown in /var/www/alpha.api.bridgemanimages.com/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php on line 157

**Comment by makasim** [comment]
I am not sure this is still relevant, correct me if I am wrong. The bundle now does $em->clear after each iteration and disables logs.
