### ISSUE TITLE
Implement Index Templates support

### ISSUE THREAD

**Issue by torinaki** [FriendsOfSymfony/FOSElasticaBundle#916]
Starting from Elastica version 1.1 it supports index templates:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html
This functionality support is missing in FOSElasticaBundle and it will be great to implement it.

**Comment by XWB** [comment]
Closed via https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/917
