### ISSUE TITLE
fos:elastica:populate get driver info for propel compatibility

### ISSUE THREAD

**Issue by Lionel09** [FriendsOfSymfony/FOSElasticaBundle#921]
I'm trying to make this command "propel" compatible, is it a way to get the driver used by an index in the `fos:elastica:populate` command?

In fact, some options are specific to doctrine and are useless in Propel, I want to test the driver to remove them. If you have a better idea, tell me.

**Comment by XWB** [comment]
Closing as we don't have Propel maintainers.
