### ISSUE TITLE
Mongodb & ElasticSerach

### ISSUE THREAD

**Issue by jiguillen** [FriendsOfSymfony/FOSElasticaBundle#922]
Hi! I'm implementing a filtering data system , in my project, some filters already exist  that use doctrine ODM for searching. I need add a filter that uses FOSElastica with data which has been filtered with Mongo previously.

I've thought add two parameters in a custom query builder, but I don't know if that is possible.

Could I do this? Are there another options?

Thanks!

**Comment by XWB** [comment]
Closing as we don't have Mongodb maintainers.
