### ISSUE TITLE
Unable to save the index when creating new entity

### ISSUE THREAD

**Issue by zanardigit** [FriendsOfSymfony/FOSElasticaBundle#925]
Sorry for a newbie question, but I get the following exception when trying to save a new entity and I have no idea how to fix it:

    IllegalArgumentException[Malformed action/metadata line [1], expected a simple value for field [_id] but found [START_OBJECT]] [] []

The `populate` command works fine. Updating an existing entity works fine. The exception is correct, because this is an extract of the JSON passed to ES:

    {"path":"_bulk","method":"PUT","data":"{\"index\":{\"_index\":\"app\",\"_type\":\"user\",\"_id\":{}}}...

and you can see `_id` is an empty object, while on update it's complete:

    {"path":"_bulk","method":"PUT","data":"{\"update\":{\"_index\":\"app\",\"_type\":\"user\",\"_id\":\"0ac35136-7109-4b45-91c6-7bf6dd7b6bc6\"}}\n

The only difference is that I am using UUID instead if autoincrement id on this app. 
I var_dumped the entity before persist and it's complete, i.e. the `id` field is filled correctly on a new entity.

Is there any special configuration I need to do while using UUID?

**Comment by zanardigit** [comment]
I think I found a solution. Shortly: the `getId` method in my entity casts the UUID to string.

# Details

After digging through FosElasticaBundle code, I see that the ID is retrieved using the standard property accessor component. And of course the property accessor component just ask the entity for it. The entity method is like this:

    public function getId()
    {
        return $this->id;
    }

and of course it returns an UUID **object**. But usually when we ask for the id, what we really want is the string and not the UUID object, so I changed the method to this:

    public function getId()
    {
        return (string)$this->id;
    }

To make FosElasticaBundle more compatible out-of-the-box in such situation, we could change a line in the method `ModelToElasticaAutoTransformer::transform` from:

    $identifier = $this->propertyAccessor->getValue($object, $this->options['identifier']);

to

    $identifier = (string)$this->propertyAccessor->getValue($object, $this->options['identifier']);

I will issue a PR and then you will see if it makes sense to merge. Thank you for this bundle!

**Comment by Issam7** [comment]
Hello

I have the same error actually,
`IllegalArgumentException[Malformed action/metadata line [1], expected a simple value for field [_id] but found [START_OBJECT]]`

Any news about this ?

**Comment by zanardigit** [comment]
@Issam7 if you read my comment and the comments in the attached PR, you should be able to fix it. 
You have a few options.

1. The simplest one: make sure your `getId` method returns a string (cast to string)
2. The advanced one: create a separate method that returns a string and change your mapping so that that method is used to retrieve the entity id

**Comment by Issam7** [comment]
@zanardigit Thanks, 
I found actually that the ID is a Join OneToOne, so it's an object in php (I'm not fun of this way but I can do nothing about it), 

So, I changed the identifier in config.yml to point to the id of the object and it seems working.
something like:
```
...
identifier : 'object'
...
```
to
```
...
identifier : 'object.id'
...
```

Thanks again.
