### ISSUE TITLE
Doubt: Is needed to use an extra persistence layer to use "entities"?

### ISSUE THREAD

**Issue by castarco** [FriendsOfSymfony/FOSElasticaBundle#929]
Hello,

I'm new with FOSElasticaBundle, and I can't find any example of using this bundle where an Elasticsearch's type is mapped to an "entity/document" without having to use an extra persistence layer like SQL DBs through Doctrine ORM or MongoDB through Doctrine ODM. Is it possible?

Can I create an "entity" class with the goodies of Doctrine without having to use MongoDB or another SQL db?

Thanks for your help and your timne.

**Comment by zanardigit** [comment]
If I understand correctly, you plan to use ElasticSearch as the persistence layer of Doctrine, **instead** of MySQL or MongoDB. Is that right?

**Comment by castarco** [comment]
@zanardigit Yes, I'm not using it only for searches, but for storing some structured data that can be understood as entities.

**Comment by nextima** [comment]
+1. We have the same scenario. 

We store some objects only in elasticSearch, without other persistence layer.
