### ISSUE TITLE
Unable to add extended_bounds to a DateHistogram

### ISSUE THREAD

**Issue by nitrobear** [FriendsOfSymfony/FOSElasticaBundle#931]
I don't find how add extended_bounds with min and max parameters in a DateHistogram Aggregation.

Is it possible ?

**Comment by ewgRa** [comment]
On low level by use setParam. But better to make PR for this. Can you do this?

**Comment by XWB** [comment]
This belongs in https://github.com/ruflin/Elastica

https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Aggregation/DateHistogram.php#L71
