### ISSUE TITLE
Background indexing

### ISSUE THREAD

**Issue by mseshachalam** [FriendsOfSymfony/FOSElasticaBundle#934]
The bundle indexes the changes in real time using Doctrine's listeners. This is a overhead in the web process for in my view. Is there any way we can index these in background processes. May be using Gearman Workers ? Any pointers on how to do this ?

**Comment by waldemarnt** [comment]
Hey mate,
Gearman is a possibility I guess, but you can use https://github.com/pda/pheanstalk too to do it as a worker.

Tell me if you need some examples.

**Comment by grzegorzgg** [comment]
I need some examples.
If you can.

**Comment by damienalexandre** [comment]
Any broker will do the job,
but that's not a feature for this bundle to cover from my POV.

What you need to do is disabling the FOSElastica listener, and build your own. Then, send some messages to a broker, and make the worker to treat them.
