### ISSUE TITLE
Fatal error: Call to undefined function Elastica\Transport\curl_init()

### ISSUE THREAD

**Issue by olive64** [FriendsOfSymfony/FOSElasticaBundle#936]
Hi,

I have this issue on mac osx 10.10.5: 

Fatal error: Call to undefined function Elastica\Transport\curl_init()

PHP 5.4.43 (cli) (built: Jul 10 2015 23:16:12)

php_curl ok

thanks in advance for responses

**Comment by ewgRa** [comment]
This is definitely curl extension not installed or enabled.

Did you have this problem when you run it from console? Or from php-fpm for example?

If first, what you have:
php -i | grep curl 

If second:
phpinfo(); die;
- load page and check that Curl extension is loaded. If not loaded, try restart php service.

**Comment by olive64** [comment]
php -i | grep curl
Configure Command =>  './configure'  '--prefix=/usr/local/php5' '--with-apxs2=/usr/sbin/apxs' '--with-config-file-scan-dir=/usr/local/php5/php.d' '--with-libxml-dir=shared,/usr' '--with-openssl=/usr' '--with-zlib=/usr' '--with-zlib-dir=/usr' '--with-gd' '--with-ldap' '--with-xmlrpc' '--enable-exif' '--enable-soap' '--enable-wddx' '--enable-ftp' '--enable-sockets' '--with-bz2=/usr' '--enable-zip' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-mbstring' '--enable-bcmath' '--enable-calendar' '--with-mhash' '--enable-fpm' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--enable-pcntl' '--enable-dtrace' '--with-icu-dir=/usr/local/php5' '--with-mssql=shared,/usr/local/php5' '--with-pdo-dblib=shared,/usr/local/php5' '--with-xsl=shared,/usr/local/php5' '--with-imap=shared,../imap-2007f' '--with-kerberos=/usr' '--with-imap-ssl=/usr' '--with-gettext=/usr/local/php5' '--with-curl=shared,/usr/local/php5' '--with-png-dir=/usr/local/php5' '--with-jpeg-dir=/usr/local/php5' '--enable-gd-native-ttf' '--with-freetype-dir=/usr/local/php5' '--with-pgsql=shared,/usr/local/php5' '--with-pdo-pgsql=shared,/usr/local/php5' '--with-mcrypt=shared,/usr/local/php5' '--with-tidy=/usr/local/php5' '--with-gmp=shared,/usr/local/php5' '--with-readline=shared,/usr/local/php5'
/usr/local/php5/php.d/50-extension-curl.ini,
curl
libcurl => 7.38.0 => 7.38.0
Request engine support => php_streams, curl

**Comment by ewgRa** [comment]
You have fatal also in CLI? You don't answer where you have problem.

Because for CLI curl can be enabled, and for php-fpm for example disabled. If you have fatal in php-fpm there is no sense to check that extension loaded in cli.

**Comment by olive64** [comment]
i don't use php-fpm

**Comment by ewgRa** [comment]
apache?

**Comment by ewgRa** [comment]
Please answer:

1. In which one sapi you have problem? CLI?

2. Provide full stack trace.

**Comment by olive64** [comment]
( ! ) Fatal error: Call to undefined function Elastica\Transport\curl_init() in /Users/olr/Sites/mb/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php on line 194
Call Stack
#	Time	Memory	Function	Location
1	0.0175	242176	{main}( )	../app.php:0
2	0.1682	1680136	Symfony\Component\HttpKernel\Kernel->handle( )	../app.php:28
3	0.5417	6452384	Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle( )	../bootstrap.php.cache:2444
4	0.5418	6453936	Symfony\Component\HttpKernel\HttpKernel->handle( )	../bootstrap.php.cache:3222
5	0.5418	6454512	Symfony\Component\HttpKernel\HttpKernel->handleRaw( )	../bootstrap.php.cache:3071
6	1.0348	16939952	call_user_func_array:{/Users/olr/Sites/mb/app/bootstrap.php.cache:3109} ( )	../bootstrap.php.cache:3109
7	1.0348	16940376	MoocsBundle\Controller\MbController->searchAction( )	../bootstrap.php.cache:3109
8	1.1404	17137176	FOS\ElasticaBundle\Finder\TransformedFinder->find( )	../MbController.php:60
9	1.1404	17137424	FOS\ElasticaBundle\Finder\TransformedFinder->search( )	../TransformedFinder.php:38
10	1.1517	17219496	Elastica\Type->search( )	../TransformedFinder.php:80
11	1.1596	17307216	Elastica\Search->search( )	../Type.php:353
12	1.1602	17342184	FOS\ElasticaBundle\Elastica\Client->request( )	../Search.php:455
13	1.1679	17384152	Elastica\Client->request( )	../Client.php:47
14	1.1680	17386064	Elastica\Request->send( )	../Client.php:621
15	1.2149	17468912	Elastica\Transport\Http->exec( )	../Request.php:171
16	1.2149	17469936	Elastica\Transport\Http->_getConnection( )	../Http.php:50

**Comment by ewgRa** [comment]
You don't answer on 1.

But anyway. 99.9% that curl extension not loaded in env where you try run this code. Check it.

**Comment by olive64** [comment]
Fix, issue with apachectl, the curl extension d'ont load. work with httpd. 

thanks ewgRa for your help

**Comment by gopavasanth** [comment]
Facing this error Thank's in advance

[b744cc08828eb14874f651bf] /core/index.php/Special:Version Error from line 216 of /var/www/html/core/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php: Call to undefined function Elastica\Transport\curl_init()

Backtrace:

#0 /var/www/html/core/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php(51): Elastica\Transport\Http->_getConnection(boolean)
#1 /var/www/html/core/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Request.php(171): Elastica\Transport\Http->exec(Elastica\Request, array)
#2 /var/www/html/core/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Client.php(662): Elastica\Request->send()
#3 /var/www/html/core/extensions/CirrusSearch/includes/Version.php(51): Elastica\Client->request(string)
#4 /var/www/html/core/extensions/CirrusSearch/includes/Hooks.php(413): CirrusSearch\Version->get()
#5 /var/www/html/core/includes/Hooks.php(177): CirrusSearch\Hooks::onSoftwareInfo(array)
#6 /var/www/html/core/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#7 /var/www/html/core/includes/specials/SpecialVersion.php(239): Hooks::run(string, array)
#8 /var/www/html/core/includes/specials/SpecialVersion.php(139): SpecialVersion::softwareInformation()
#9 /var/www/html/core/includes/specialpage/SpecialPage.php(522): SpecialVersion->execute(NULL)
#10 /var/www/html/core/includes/specialpage/SpecialPageFactory.php(578): SpecialPage->run(NULL)
#11 /var/www/html/core/includes/MediaWiki.php(287): SpecialPageFactory::executePath(Title, RequestContext)
#12 /var/www/html/core/includes/MediaWiki.php(851): MediaWiki->performRequest()
#13 /var/www/html/core/includes/MediaWiki.php(523): MediaWiki->main()
#14 /var/www/html/core/index.php(43): MediaWiki->run()
#15 {main}

**Comment by ewgRa** [comment]
@gopavasanth it is same problem as @olive64 had. There is nothing to add, just make sure that this extension installed and loaded. Simplest way - call "phpinffo();" inside code and try to find something about curl extension.
