### ISSUE TITLE
Wrong tag 3.0.13 on master branch instead of the 3.0.x branch

### ISSUE THREAD

**Issue by djlemmings** [FriendsOfSymfony/FOSElasticaBundle#939]
Hello,

I just found out that the tag for the release 3.0.13 was done on the "master" branch instead of the 3.0.x one, making a whole lot of change in the code and my project to stop working properly. I know I have to switch to 3.1 branch someday but it takes time.

If you could fix the tag position that would help a lot.

Thanks.

**Comment by XWB** [comment]
I just fixed the 3.0.13 release.

**Comment by djlemmings** [comment]
Thanks!
