### ISSUE TITLE
Disable listeners

### ISSUE THREAD

**Issue by cbacelar** [FriendsOfSymfony/FOSElasticaBundle#940]
hi,

i'm having problem on update any entity (probably a version problem), is there a way to stop listeners? so i will run "fos:elastica:populate" manually every day, because the search is working fine.

thanks.

**Comment by xleliberty** [comment]
Hi, 
yes you can.

Just modify your configuration file 
your_entity:
    persistence:
        listeners:
            insert: false
            update: false
            delete: false

**Comment by cbacelar** [comment]
thanks and sorry, now i found in documentation.
