### ISSUE TITLE
hybridTransform ignores setting ignore_missing

### ISSUE THREAD

**Issue by rudott** [FriendsOfSymfony/FOSElasticaBundle#948]
When setting the ignore_missing param in the search config, the Transformer ignores missing doctrine entities. This works like a charm.

But when you need the hybrid versions it will create an Exception when there are missing elasticaObjects. Eg: Notice: Undefined offset: 1

File Transformer/ElasticaToModelTransformerCollection.php:
public function hybridTransform(array $elasticaObjects)
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/620fcf523b506155372dca6f0fea9f48c3659c6a/Transformer/ElasticaToModelTransformerCollection.php#L79

**Comment by XWB** [comment]
Closing this as `ignore_missing` doesn't exist anymore.
