### ISSUE TITLE
Any document for searching across types?

### ISSUE THREAD

**Issue by Hoannv** [FriendsOfSymfony/FOSElasticaBundle#952]
ElasticSearch is supported for searching across types and indexes.

But I didn't find any document instructs how to use it with foselasticabundle. Can you give me some links of document ?

**Comment by damienalexandre** [comment]
This is an Elastica question,
you will need to manipulate search indexes and types on the [Search](https://github.com/ruflin/Elastica/blob/master/lib/Elastica/Search.php) object.
