### ISSUE TITLE
No way to disable the bundle from configuration

### ISSUE THREAD

**Issue by Adirelle** [FriendsOfSymfony/FOSElasticaBundle#955]
For some automated tests, I'd like to disable the bundle entirely (because right now I can't setup a test ElasticSearch cluster). However, there is no easy way to do this.

Would it be possible to add an "enabled" flag in the bundle configuration so it could be disabled by adding this in config_test.yml ?

``` yml
fos_elastica:
  enabled: false
```

**Comment by behramcelen** [comment]
You can enable this bundle only on prod dev. from AppKernel like https://github.com/symfony/symfony-standard/blob/master/app/AppKernel.php#L21. And revise your config file according to your environment

If you do not understand i can send an snippet.
