### ISSUE TITLE
Elastic update

### ISSUE THREAD

**Issue by shubaivan** [FriendsOfSymfony/FOSElasticaBundle#961]
I have "friendsofsymfony/elastica-bundle": "~3.0" "ruflin/elastica": "~2.1,<2.3", and php 5.5.9 and we update elasticsearch from 1.7.3 to 2.0 and when I try update or create index like fos:elastica:populate I have error

    Error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) {"type":1,"file":"/home/ivan/host/aog-code /vendor/ruflin/elastica/lib/Elastica/Exception/ResponseException.php"
    ......
    Error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]])

I try find how to solved this problem, after update, and could not find. I try update FOSElasticaBundle
to dev-master / 3.2.x-dev but still have problem. Now there is a solution for elasticsearch 2.0?

**Comment by ewgRa** [comment]
Hi, seems same that here https://github.com/ruflin/Elastica/issues/974

**Comment by bobvandevijver** [comment]
This should be solved when this bundle upgrades the `composer.json` for `ruflin/elastica` to `~3.0` instead of `~2.1`.

**Comment by XWB** [comment]
Duplicate.
