### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by enachesilviu** [FriendsOfSymfony/FOSElasticaBundle#964]
I think you could adjust the requirements on Elastica client version since the actual version this bundle uses throws this error whilst on PHP 7 (RC 7):

Compile Error: Cannot use 'Elastica\Filter\Bool' as class name as it is reserved

On ruflin/elastica library project they seem to have addressed this issue already:

https://github.com/ruflin/Elastica/issues/903

**Comment by Mohammadtrabelsi** [comment]
Did you solve this problem ?
