### ISSUE TITLE
Suggests not accessible when using FOSElasticaBundle with KnpPager

### ISSUE THREAD

**Issue by likeitlikeit** [FriendsOfSymfony/FOSElasticaBundle#968]
When using suggests in conjunction with KnpPager, there is no (obvious?) way to get the suggests out of the results. It appears that a `getSuggests()` method on `PaginatorAdapterInterface` is missing. Aggregations and Facets are already supported there.

**Comment by XWB** [comment]
Will be added in https://github.com/FriendsOfSymfony/FOSElasticaBundle/pull/1214
