### ISSUE TITLE
mongodb single collection inheritance

### ISSUE THREAD

**Issue by serhiimelnik** [FriendsOfSymfony/FOSElasticaBundle#973]
I can't figure out how to setup fos_elastica configuration with @MongoDB\InheritanceType("SINGLE_COLLECTION").
Any advices are appreciated.

**Comment by christoph-hautzinger** [comment]
did you find a solution @serhiimelnik ?

**Comment by serhiimelnik** [comment]
@christoph-hautzinger I wrote own `model_to_elastica_transformer`
