### ISSUE TITLE
Symfony 3.0.0 Release Issue

### ISSUE THREAD

**Issue by cecric** [FriendsOfSymfony/FOSElasticaBundle#974]
Hello the FOS team !
I get an issue with the brand new release of Symfony (3.0.0). When I try to update the version of symfony on my website with composer, I get an error with FosElasticaBundle. 
So, to check if the problem came not from other bundles, I try to start from an empty project and just add the FosElasticaBundle with the command in your documentation : 
>composer require friendsofsymfony/elastica-bundle

And I get the same error. Here it is the error log: 

>Using version ^3.1 for friendsofsymfony/elastica-bundle
>./composer.json has been updated
>Loading composer repositories with package information
>Updating dependencies (including require-dev)
>Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>    - Conclusion: remove symfony/symfony v3.0.0
>    - Conclusion: don't install symfony/symfony v3.0.0
>    - friendsofsymfony/elastica-bundle 3.1.0 requires symfony/property-access ~2.2 -> satisfiable by symfony/property-access[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
>    - friendsofsymfony/elastica-bundle v3.1.1 requires symfony/property-access ~2.2 -> satisfiable by symfony/property-access[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
>    - friendsofsymfony/elastica-bundle v3.1.2 requires symfony/property-access ~2.2 -> satisfiable by symfony/property-access[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
>    - friendsofsymfony/elastica-bundle v3.1.3 requires symfony/property-access ~2.2 -> satisfiable by symfony/property-access[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
>    - friendsofsymfony/elastica-bundle v3.1.4 requires symfony/property-access ~2.2 -> satisfiable by symfony/property-access[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
>    - friendsofsymfony/elastica-bundle v3.1.5 requires symfony/property-access ~2.3 -> satisfiable by symfony/property-access[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
>    - friendsofsymfony/elastica-bundle v3.1.6 requires symfony/property-access ~2.3 -> satisfiable by symfony/property-access[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.8.0].
>   - don't install symfony/property-access v2.2.0|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.2.1|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.2.10|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.2.11|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.2.2|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.2.3|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.2.4|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.2.5|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.2.6|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.2.7|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.2.8|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.2.9|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.0|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.1|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.10|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.11|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.12|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.13|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.14|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.15|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.16|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.17|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.18|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.19|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.2|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.20|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.21|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.22|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.23|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.24|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.25|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.26|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.27|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.28|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.29|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.3|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.30|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.31|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.32|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.33|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.34|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.35|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.4|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.5|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.6|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.7|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.8|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.3.9|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.4.0|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.4.1|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.4.10|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.4.2|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.4.3|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.4.4|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.4.5|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.4.6|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.4.7|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.4.8|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.4.9|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.0|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.1|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.10|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.11|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.12|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.2|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.3|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.4|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.5|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.6|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.7|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.8|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.5.9|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.0|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.1|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.10|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.11|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.12|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.2|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.3|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.4|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.5|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.6|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.7|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.8|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.6.9|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.7.0|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.7.1|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.7.2|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.7.3|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.7.4|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.7.5|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.7.6|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.7.7|don't install symfony/symfony v3.0.0
>    - don't install symfony/property-access v2.8.0|don't install symfony/symfony v3.0.0
>    - Installation request for symfony/symfony 3.0.* -> satisfiable by symfony/symfony[v3.0.0].
>    - Installation request for friendsofsymfony/elastica-bundle ^3.1 -> satisfiable by friendsofsymfony/elastica-bundle[3.1.0, v3.1.1, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6].
>
>
>Installation failed, reverting ./composer.json to its original content.

I don't really know where it came from, so I hope you'll find the solution.
Thank you in advance to any help :) 
Have a nice day

**Comment by merk** [comment]
We do not currently provide a stable release with symfony 3.0 support.

Use "friendsofsymfony/elastica-bundle: ~3.2@dev".

For the future, when reporting this kind of issue please always include your composer.json file - it helps diagnose the issue.

I'll leave this issue open for others to come across until we release a stable 3.2 release.

**Comment by cecric** [comment]
Thank you Merk for this answer !
I'll try to do not forget the composer.json the next time ! Sorry about this :)

**Comment by cmodijk** [comment]
@merk is there an estimated release date for the 3.2 version?

**Comment by LuisLunaGo** [comment]
¿Para cuando la versión 3.2?
Gracias.

**Comment by eidicon** [comment]
Is there any news about the 3.2 stable release?

**Comment by XWB** [comment]
A new release has been published.

**Comment by amold** [comment]
`{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle"
        },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
    "autoload-dev": {
        "psr-4": { "Tests\\": "tests/" },
        "files": [ "vendor/symfony/symfony/src/Symfony/Component/VarDumper/Resources/functions/dump.php" ]
    },
    "require": {
        "php": ">=5.5.9",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "incenteev/composer-parameter-handler": "^2.0",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^3.0.2",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "3.3.*",
        "twig/twig": "^1.0||^2.0",
		"symfony/assetic-bundle": "2.1.*",
		"doctrine/migrations": "dev-master",
		"doctrine/doctrine-migrations-bundle": "dev-master",
		"jms/security-extra-bundle": "1.2.*",
        "jms/di-extra-bundle": "1.1.*",
		"friendsofsymfony/user-bundle": "*",
        "stof/doctrine-extensions-bundle": "~1.1@dev",
        "knplabs/knp-snappy-bundle": "dev-master"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "config": {
        "platform": {
            "php": "5.5.9"
        },
        "sort-packages": true
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "3.3-dev"
        }
    }
}
`

Here is my "composer.json" file. I'm still getting same error when I run the "composer update" command.
Please help me to solved this issue ASAP.

I'm getting below errors:
'Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install symfony/symfony v3.3.6
    - Conclusion: remove symfony/symfony v3.3.5
    - Conclusion: don't install symfony/symfony v3.3.5
    - Conclusion: don't install symfony/symfony v3.3.4
    - Conclusion: don't install symfony/symfony v3.3.3
    - Installation request for jms/security-extra-bundle 1.2.* -> satisfiable by jms/security-extra-bundle[1.2.0].
    - Conclusion: don't install symfony/symfony v3.3.2
    - Conclusion: don't install symfony/symfony v3.3.1
    - jms/security-extra-bundle 1.2.0 requires symfony/framework-bundle 2.1.* -> satisfiable by symfony/framework-bundle[v2.1.0, v2.1.1, v2.1.10
.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9].
    - don't install symfony/framework-bundle v2.1.0|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.1|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.10|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.11|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.12|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.13|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.2|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.3|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.4|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.5|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.6|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.7|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.8|don't install symfony/symfony v3.3.0
    - don't install symfony/framework-bundle v2.1.9|don't install symfony/symfony v3.3.0
    - Installation request for symfony/symfony 3.3.* -> satisfiable by symfony/symfony[v3.3.0, v3.3.1, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6].'

Please provide me solution on the same.
Thanks in advance!!!....

**Comment by iammichiel** [comment]
You should not post your problem is someone else's report. Plus the issue has been closed.
