### ISSUE TITLE
Index Files with FOSElastica ?

### ISSUE THREAD

**Issue by Cyr69** [FriendsOfSymfony/FOSElasticaBundle#981]
Hello,

What is that I can index files (pdf, word etc?) with FOSElastica? If yes, how do I have to proceed?

Thanks advance !

Bests Regards

**Comment by phreaknerd** [comment]
You won't. You will have to parse the file with another tool (like apache tika) to extract the content and then pass this to the entity or directly to elasticsearch.

**Comment by Cyr69** [comment]
It okay with Apache Tika ! Thanks you.
