### ISSUE TITLE
No more Facets in Elastica/ResultSet

### ISSUE THREAD

**Issue by azianfr** [FriendsOfSymfony/FOSElasticaBundle#982]
Hello,

i'm using your Paginator with the ruflin/Elastica package.
You are using Facets which is not used anymore by the package i'm using.

ruflin/Elastica@288b0a5

As you can see, everything related to facets has been deleted by the author, can you please fix it ?

edit : According the changelog of Elasticsearch 2.0, there is no more facets

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_removed_features.html

**Comment by merk** [comment]
The aggregation feature replaced facets
