### ISSUE TITLE
geo_point type mapping is ignored

### ISSUE THREAD

**Issue by falsecrypt** [FriendsOfSymfony/FOSElasticaBundle#984]
It seems to me that the `type: 'geo_point'` mapping does not work. I've already tried all possible format-combinations: lat, lon as Properties, lat, lon as String (`"41.12,-71.34"`), lat, lon as Array (`[41.12,-71.34]`) and none of these works. When i use a query like:

```
   "filter": {
      "geo_distance": {
         "distance": "15km",
         "location": [ 40, -70]
         }
      }
```

i get an error: `failed to find geo_point field [location]` or `field [location] is not a geo_point field` if the format was a string. Can someone tell me whats wrong? Is this type supported by `FOSElasticaBundle`? I'm using elastica-bundle v3.1.7 and symfony 2.8

**Comment by damienalexandre** [comment]
- Can you call `GET /your_index/your_type/_mapping` and check that the field is properly mapped as **get_point**?
- Do you have another type in this index with a name **location**, but not mapped as **geo_point**?
- What have you tried?
- Elastica support GeoPoint, you can look at this example: https://github.com/ruflin/Elastica/blob/master/test/lib/Elastica/Test/Filter/GeoDistanceTest.php
- Their is a `addGeoPoint` method, but it's only adding `array('lat' => $latitude, 'lon' => $longitude);` in your key.

Good luck!

**Comment by falsecrypt** [comment]
Hi, thanks for your reply. Of course the first thing i've tried was to check the mapping in ES with /_mapping request. And it was always wrong: if my format was `location: {lat: ..., lon: ...}` then it became just an object with properties(both with type `double`) in ES. If i have chosen a format like: `location: "40,-70"` then the mapping type was `type: string`. I tested it with only one (not nested) `location`-property. By the way: `type: nested` didn't work either. I ended up writing my own `custom provider` and created the whole mapping manually. Now it works.

**Comment by jguittard** [comment]
+1

**Comment by sheldon-sminq** [comment]
+1

**Comment by JoppeDC** [comment]
I'm still running into this issue. ES has it indexed as a geo_point type, but elastica keeps throwing `PartialShardFailureException` with `failed to find geo_point field`
