### ISSUE TITLE
How to use percolate?

### ISSUE THREAD

**Issue by klinkin** [FriendsOfSymfony/FOSElasticaBundle#989]
How to use percolate?

**Comment by damienalexandre** [comment]
The percolator is a very rich API, we can't answer you if you do not explain what you are trying to do.

Have a look at those links (official documentation and Elastica exemple):
- https://www.elastic.co/guide/en/elasticsearch/reference/current/search-percolate.html
- https://github.com/ruflin/Elastica/blob/master/test/lib/Elastica/Test/PercolatorTest.php
