### ISSUE TITLE
FOSElasticaBundle compatibility with Magento 

### ISSUE THREAD

**Issue by price2b** [FriendsOfSymfony/FOSElasticaBundle#995]
This is an off-topic and sorry in advance but, could someone tell me if FOSElasticaBundle could work with Magento based on the fact that symfony elements are included in the platform http://symfony.com/projects/magento ?. 

brgds!

**Comment by merk** [comment]
Its a question for the Magento ecosystem, I do not know anything about what magento is doing with the symfony components.

**Comment by price2b** [comment]
thank you!.
