### ISSUE TITLE
Upgrade Elastica to 3.0.1

### ISSUE THREAD

**Issue by JarJak** [FriendsOfSymfony/FOSElasticaBundle#996]
That version has fixed BC break that still exists in 2.3.1:
https://github.com/ruflin/Elastica/pull/1016

**Comment by JarJak** [comment]
https://github.com/ruflin/Elastica/pull/1016

**Comment by mediamonks-robert** [comment]
+1

**Comment by merk** [comment]
There is nothing to upgrade, the constraints in 3.2@dev allow you to use Elastica 2.x or 3.x.

**Comment by mediamonks-robert** [comment]
According to https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/composer.json it is restricted to ruflin/elastica ~2.1:

"ruflin/elastica": "~2.1",

Can you point me to the version which also supports ~3.0 then perhaps?

**Comment by merk** [comment]
Sorry you're right - I thought I committed the change allowing ~3.0. It broke a lot of tests and I dont have time to make it compatible.

If someone wants to send a PR that maintains Elastica 2.x compatibility, I'd be happy to merge.

**Comment by mediamonks-robert** [comment]
Thanks for re-opening :) I think the only thing that was broken was the pagination described here:

https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/969 which I can do a PR for tomorrow. Not sure about other compatibility though. Maybe a separate branch can be made to at least allow others to create PR's for the bundle?

**Comment by merk** [comment]
There was a major problem with the mapping system in FOSElasticaBundle relying on the $type->delete() call instead of deleting whole indexes and deprecated methods in Elastica that will take quite a bit of work to get right, and it has led me to the attitude that we need to rewrite the entire mapping metadata handling code to be more robust and logical and release that as 4.0 of this bundle.

See the roadmap post: https://github.com/FriendsOfSymfony/FOSElasticaBundle/issues/986

**Comment by AliHichem** [comment]
+1, This bundle is great but we love to have it with elasticsearch v2

**Comment by Isinlor** [comment]
+1 as well

**Comment by JarJak** [comment]
It might not be needed - see https://github.com/ruflin/Elastica/pull/1016#issuecomment-170888362

**Comment by steffenbrem** [comment]
@JarJak This bundle still needs to update the version constraint in order for us to use the latest elastica.

**Comment by AliHichem** [comment]
@steffenbrem +1

**Comment by mathielen** [comment]
+1

**Comment by jorge07** [comment]
+1

**Comment by imilyukov** [comment]
+1

**Comment by Floyd25** [comment]
Any updates here? How come it's so hard to bump the version number to ~3.0 ?

**Comment by flobox** [comment]
+1

**Comment by XWB** [comment]
Use the master branch for Elastica 3 support.
